process.on('uncaughtException',e=>{console.error(e.message,e.detail||'',e.where||'');process.exit(1)});
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const c='00000000-0000-0000-0000-000000000001',bu='00000000-0000-0000-0000-000000000002',loc='00000000-0000-0000-0000-000000000003',user='00000000-0000-0000-0000-000000000004';
await db.exec(`create role authenticated;create role anon;create schema auth;
set test.company='${c}';set test.bu='${bu}';set test.loc='${loc}';set test.actor='${user}';set test.allow='true';
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function current_company_id() returns uuid language sql stable as $$select current_setting('test.company')::uuid$$;
create function current_business_unit_id() returns uuid language sql stable as $$select current_setting('test.bu')::uuid$$;
create function current_operating_location_id() returns uuid language sql stable as $$select current_setting('test.loc')::uuid$$;
create function legacy_data_user_id() returns uuid language sql as $$select auth.uid()$$;
create function has_company_access(uuid) returns boolean language sql stable as $$select $1=current_company_id()$$;
create function has_module_permission(uuid,text,text) returns boolean language sql stable as $$select $1=current_company_id() and current_setting('test.allow')::boolean$$;
create function has_transport_action_permission(uuid,text) returns boolean language sql stable as $$select has_module_permission($1,'transport',$2)$$;
create function assert_module_permission(text,text) returns void language plpgsql as $$begin if auth.uid() is null or not current_setting('test.allow')::boolean then raise exception 'Permission required';end if;end$$;
create function transport_finance_assert(text) returns void language sql as $$select assert_module_permission('transport',$1)$$;
create table companies(id uuid primary key);create table business_units(id uuid primary key,company_id uuid);
create table employees(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,employee_code text,name text,designation text,department text,is_active boolean);
create table chart_of_accounts(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,code text,name text,type text,detail_type text,account_role text,parent_head text,normal_balance text,description text,is_active boolean default true,is_group boolean default false,allow_manual_entries boolean default true);
create table transport_drivers(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,driver_name text,employee_id uuid,driver_type text,supplier_id uuid,is_active boolean,notes text);
create table journal_entries(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,business_unit_id uuid,operating_location_id uuid,entry_no text,entry_date date,description text,status text,payment_mode text,party_name text,trans_type text,payment_amount numeric,created_by uuid,source_module text,source_document_type text,reversal_of_entry_id uuid,created_at timestamptz default now());
create table journal_lines(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,business_unit_id uuid,entry_id uuid,account text,account_id uuid,debit numeric,credit numeric,party_name text,base_debit numeric,base_credit numeric);
create table ledgers(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,operating_location_id uuid,account_id uuid,entry_date date,journal_entry_id uuid,debit numeric,credit numeric);
create table employee_salary_accruals(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,employee_id uuid,salary_month date,monthly_salary numeric,journal_entry_id uuid,voucher_no text);
create table employee_salary_payments(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,business_unit_id uuid,employee_id uuid,salary_month date,payment_date date,amount numeric,journal_entry_id uuid,voucher_no text);
create table employee_salary_profiles(company_id uuid,employee_id uuid,monthly_salary numeric,effective_from date);
create table transport_trips(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,operating_location_id uuid,driver_id uuid,trip_date date,driver_pay numeric);
create table transport_driver_month_adjustments(company_id uuid,business_unit_id uuid,operating_location_id uuid,employee_id uuid,month date,kind text,amount numeric);
create table transport_driver_month_closings(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,operating_location_id uuid,employee_id uuid,month date,opening_balance numeric,trip_pay numeric,allowance numeric,bonus numeric,other_earning numeric,loan_deduction numeric,other_deduction numeric,payments numeric,closing_balance numeric,journal_entry_id uuid,posted_by uuid);
create table account_mappings(company_id uuid,mapping_key text,account_id uuid);
create function transport_assert_company_employee_driver(e uuid) returns void language plpgsql as $$begin if not exists(select 1 from transport_drivers where company_id=current_company_id() and business_unit_id=current_business_unit_id() and employee_id=e and driver_type='company' and supplier_id is null and is_active) then raise exception 'Company driver required';end if;end$$;
create function post_journal_entry(je uuid) returns void language plpgsql as $$begin
if (select count(*) from journal_lines where entry_id=je)<2 or (select sum(debit-credit) from journal_lines where entry_id=je)<>0 then raise exception 'Unbalanced journal';end if;
insert into ledgers(company_id,business_unit_id,operating_location_id,account_id,entry_date,journal_entry_id,debit,credit) select j.company_id,j.business_unit_id,j.operating_location_id,l.account_id,j.entry_date,je,l.debit,l.credit from journal_entries j join journal_lines l on l.entry_id=j.id where j.id=je;
update journal_entries set status='posted' where id=je;end$$;
create function transport_driver_month_preview(uuid,date) returns jsonb language sql as $$select '{"legacy":true}'::jsonb$$;
create function transport_driver_post_month(uuid,date) returns jsonb language sql as $$select '{"legacy":true}'::jsonb$$;
create function get_employee_salary_summary(uuid,date) returns jsonb language sql as $$select '{"legacy":true}'::jsonb$$;
create function accrue_employee_salary(uuid,date) returns jsonb language sql as $$select '{"legacy":true}'::jsonb$$;
create function post_salary_payment(uuid,date,date,uuid,uuid,numeric,text default null,text default null) returns jsonb language sql as $$select '{"legacy":true}'::jsonb$$;
create view employee_salary_ledger as select p.company_id,p.business_unit_id,p.employee_id,e.employee_code,e.name employee_name,e.designation,e.department,p.salary_month,p.payment_date entry_date,p.voucher_no document_no,'Payment'::text entry_type,0::numeric debit,p.amount credit,p.journal_entry_id from employee_salary_payments p join employees e on e.id=p.employee_id;
create view transport_driver_account_movements as select ''::text event_id,null::uuid company_id,null::uuid business_unit_id,null::uuid operating_location_id,null::uuid trip_id,null::uuid employee_id,''::text party_name,null::uuid journal_entry_id,0::numeric amount,''::text event_type,''::text trip_no,''::text entry_no,null::date event_date,''::text description,now() created_at,0::numeric debit,0::numeric credit where false;
insert into companies values('${c}');insert into business_units values('${bu}','${c}');
`);
await db.exec(readFileSync(new URL('../migrations/20261009071103_driver_salary_settlement_accounts.sql',import.meta.url),'utf8'));
const coa=(await db.query(`insert into chart_of_accounts(company_id,name,type,detail_type) values('${c}','Waqas Driver Advance','asset','other_current_asset'),('${c}','Asif Driver Payable','liability','other_current_liability'),('${c}','Salary Expense','expense','Salaries'),('${c}','Cash','asset','Cash on Hand') returning id,name`)).rows;
const acct=Object.fromEntries(coa.map(x=>[x.name,x.id]));
await db.exec(`insert into account_mappings values('${c}','salary_expense','${acct['Salary Expense']}');
insert into journal_entries(company_id,business_unit_id,operating_location_id,entry_no,entry_date,status,source_document_type) values('${c}','${bu}','${loc}','COB','2026-09-01','posted','cutover_opening_balances');
insert into ledgers(company_id,business_unit_id,operating_location_id,account_id,entry_date,journal_entry_id,debit,credit) select '${c}','${bu}','${loc}','${acct['Waqas Driver Advance']}','2026-09-01',id,2000,0 from journal_entries where entry_no='COB';
insert into ledgers(company_id,business_unit_id,operating_location_id,account_id,entry_date,journal_entry_id,debit,credit) select '${c}','${bu}','${loc}','${acct['Asif Driver Payable']}','2026-09-01',id,0,500 from journal_entries where entry_no='COB';`);
const scalar=async(sql)=>Object.values((await db.query(sql)).rows[0])[0];
assert.equal((await scalar('select transport_link_opening_salary_accounts()')).linked,2);
assert.equal((await scalar('select transport_link_opening_salary_accounts()')).linked,0);
assert.equal(Number(await scalar('select count(*) from ledgers')),2); // No duplicated opening.
const employees=(await db.query('select id,name from employees')).rows;
const waqas=employees.find(x=>x.name==='Waqas').id,asif=employees.find(x=>x.name==='Asif').id;
let v=await scalar(`select transport_driver_month_preview('${waqas}','2026-10-01')`);
assert.equal(v.configured,false);assert.equal(v.closing_balance,-2000);
await assert.rejects(()=>db.query(`select transport_driver_post_month('${waqas}','2026-10-01')`),/Configure basic salary/);
await db.exec(`insert into employee_salary_profiles values('${c}','${waqas}',1200,'2026-10-01');insert into transport_trips(company_id,business_unit_id,operating_location_id,driver_id,trip_date,driver_pay) select '${c}','${bu}','${loc}',id,'2026-10-10',1800 from transport_drivers where employee_id='${waqas}';`);
v=await scalar(`select transport_driver_month_preview('${waqas}','2026-10-01')`);
assert.equal(v.basic_salary,1200);assert.equal(v.trip_pay,1800);assert.equal(v.opening_balance,-2000);assert.equal(v.closing_balance,1000);
await assert.rejects(()=>db.query(`select accrue_employee_salary('${waqas}','2026-10-01')`),/Driver Monthly Khata/);
v=await scalar(`select transport_driver_post_month('${waqas}','2026-10-01')`);assert.equal(v.closing_balance,1000);
assert.equal(Number(await scalar(`select sum(credit-debit) from ledgers where account_id='${acct['Waqas Driver Advance']}'`)),1000);
assert.equal(Number(await scalar(`select sum(debit) from journal_lines where account_id='${acct['Salary Expense']}'`)),3000);
await assert.rejects(()=>db.query(`select transport_driver_post_month('${waqas}','2026-10-01')`),/locked/);
v=await scalar(`select post_salary_payment('${waqas}','2026-10-01','2026-10-31','${acct['Waqas Driver Advance']}','${acct.Cash}',1000)`);
assert.equal(v.remaining_balance,0);assert.equal(Number(await scalar('select count(*) from employee_salary_accruals')),0);
v=await scalar(`select transport_driver_month_preview('${waqas}','2026-10-01')`);assert.equal(v.locked,true);assert.equal(v.payments,1000);assert.equal(v.closing_balance,0);
// A further salary advance stays in the same salary account and does not become a loan.
v=await scalar(`select post_salary_payment('${waqas}','2026-11-01','2026-11-05','${acct['Waqas Driver Advance']}','${acct.Cash}',2000)`);
assert.equal(v.remaining_balance,-2000);assert.equal(v.salary_advance,2000);
v=await scalar(`select transport_driver_month_preview('${waqas}','2026-11-01')`);assert.equal(v.opening_balance,0);assert.equal(v.basic_salary,1200);assert.equal(v.payments,2000);assert.equal(v.closing_balance,-800);
const movements=(await db.query(`select sum(debit-credit) balance from transport_driver_account_movements where employee_id='${waqas}'`)).rows[0];assert.equal(Number(movements.balance),-2000);
assert.equal(Number(await scalar('select count(*) from employee_salary_ledger')),5); // 2 original openings + month + 2 payments.
assert.equal(Number(await scalar(`select sum(debit-credit) from employee_salary_ledger where employee_id='${waqas}'`)),-2000);
assert.equal(Number(await scalar(`select sum(debit-credit) from employee_salary_ledger where employee_id='${asif}'`)),500);
// Scope/permission rejects and unchanged legacy dispatch.
await db.exec("set test.allow='false'");await assert.rejects(()=>db.query(`select transport_driver_month_preview('${waqas}','2026-11-01')`),/permissions required/);
await db.exec("set test.allow='true';set test.actor=''");await assert.rejects(()=>db.query('select transport_link_opening_salary_accounts()'),/required/);
await db.exec(`set test.actor='${user}';set test.company='00000000-0000-0000-0000-000000000099'`);await assert.rejects(()=>db.query(`select transport_driver_month_preview('${waqas}','2026-11-01')`),/Company driver/);
await db.exec(`set test.company='${c}'`);
assert.equal((await scalar(`select get_employee_salary_summary('00000000-0000-0000-0000-000000000098','2026-10-01')`)).legacy,true);
// New company drivers can enable a salary balance account without a loan/opening.
const fresh=await scalar(`insert into employees(company_id,name,is_active) values('${c}','New driver',true) returning id`);
await db.exec(`insert into transport_drivers(company_id,business_unit_id,driver_name,employee_id,driver_type,is_active) values('${c}','${bu}','New driver','${fresh}','company',true)`);
const beforeLedgers=Number(await scalar('select count(*) from ledgers'));
const freshAccount=await scalar(`select transport_enable_driver_salary_account('${fresh}')`);
assert.equal(await scalar(`select transport_enable_driver_salary_account('${fresh}')`),freshAccount);
assert.equal(Number(await scalar('select count(*) from ledgers')),beforeLedgers);
assert.equal(await scalar(`select detail_type from chart_of_accounts where id='${freshAccount}'`),'Driver Salary Balance');
await assert.rejects(()=>db.query(`select post_salary_payment('${waqas}','2026-11-01','2026-11-05','${acct['Salary Expense']}','${acct.Cash}',1)`),/driver salary balance account/);
// Security-invoker movements and mapping selection respect tenant RLS.
for(const table of ['employees','ledgers','journal_entries'])await db.exec(`alter table ${table} enable row level security;create policy tenant on ${table} to authenticated using(company_id=current_company_id());grant select on ${table} to authenticated;`);
await db.exec('grant usage on schema auth to authenticated;set role authenticated');
assert.equal(Number(await scalar('select count(*) from driver_salary_accounts')),3);
await db.exec("set test.company='00000000-0000-0000-0000-000000000099'");assert.equal(Number(await scalar('select count(*) from driver_salary_accounts')),0);assert.equal(Number(await scalar('select count(*) from driver_salary_account_movements')),0);
await db.exec('reset role');await db.exec(readFileSync(new URL('../migrations/20261009135235_transport_driver_month_end_guard.sql',import.meta.url),'utf8'));
const beforeGuard=await db.query('select count(*)::integer n from journal_entries');
await assert.rejects(()=>db.query(`select transport_driver_post_month('${waqas}',date_trunc('month',current_date)::date)`),/month must finish/);
await assert.rejects(()=>db.query(`select transport_driver_post_month('${waqas}',(date_trunc('month',current_date)+interval '1 month')::date)`),/month must finish/);
assert.equal((await db.query('select count(*)::integer n from journal_entries')).rows[0].n,beforeGuard.rows[0].n);
console.log('PASS current/future month guard; no journal created');
await db.close();console.log('Driver salary rehearsal PASS: opening linkage/idempotency, basic + trip earnings, advance→payable→settled→advance, post-lock payments, roll-forward, no duplicate accrual, per-driver balances, legacy dispatch and tenant isolation.');
