import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`
create role authenticated;
create role anon;
create table customers(id uuid,company_id uuid,name text);
create table party_ledgers(company_id uuid,business_unit_id uuid,operating_location_id uuid,party_id uuid,party_type text,entry_date date,debit numeric,credit numeric);
create table customer_invoice_aging(sales_order_id uuid,user_id uuid,customer_id uuid,customer_name text,invoice_no text,invoice_date date,due_date date,invoice_amount numeric,paid_amount numeric,outstanding_amount numeric,payment_status text,days_outstanding int,overdue_days int,aging_status text,aging_bucket text,company_id uuid,business_unit_id uuid,operating_location_id uuid);
create table sales_margin_report(company_id uuid,business_unit_id uuid,invoice_date date,net_sales_amount numeric,gross_profit numeric);
create table purchase_register_report(company_id uuid,business_unit_id uuid,order_date date,total numeric);
create table invoice_payment_allocations(company_id uuid,business_unit_id uuid,allocation_date date,amount numeric);
create table stock_godown_report(company_id uuid,business_unit_id uuid,stock_value numeric);
create table ledgers(company_id uuid,business_unit_id uuid,entry_date date,account_id uuid,debit numeric,credit numeric);
create table chart_of_accounts(id uuid,type text);
create table account_mappings(company_id uuid,account_id uuid,mapping_key text);
`);
await db.exec(readFileSync(new URL('../migrations/20261009062256_opening_aware_reporting.sql',import.meta.url),'utf8'));
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',customer='00000000-0000-0000-0000-000000000003',account='00000000-0000-0000-0000-000000000004',invoice='00000000-0000-0000-0000-000000000005';
await db.exec(`insert into customers values('${customer}','${a}','Opening customer');
insert into party_ledgers values('${a}',null,null,'${customer}','customer',current_date-40,300,0);
insert into customer_invoice_aging values('${invoice}',null,'${customer}','Opening customer','INV1',current_date-10,null,150,50,100,'partial',10,0,'partial','No Due Date','${a}',null,null);
insert into chart_of_accounts values('${account}','asset');
insert into account_mappings values('${a}','${account}','accounts_receivable'),('${b}','${account}','accounts_receivable');
insert into ledgers values('${a}',null,current_date-40,'${account}',300,0),('${b}',null,current_date-40,'${account}',999,0);`);
let result=await db.query('select source_type,outstanding_amount,invoice_amount,due_date,overdue_days from customer_receivable_aging_report order by source_type');
assert.equal(result.rows.length,2);assert.equal(Number(result.rows[1].outstanding_amount),200);assert.equal(Number(result.rows[1].invoice_amount),0);assert.equal(result.rows[1].due_date,null);assert.equal(result.rows[1].overdue_days,0);
result=await db.query('select sum(outstanding_amount) total from customer_receivable_aging_report');assert.equal(Number(result.rows[0].total),300);
result=await db.query(`select receivables from business_unit_performance_report where company_id='${a}'`);assert.equal(Number(result.rows[0].receivables),300);assert.equal(result.rows.length,1);
result=await db.query(`select current_ar from monthly_business_performance_report where company_id='${a}' and month_start=date_trunc('month',current_date)::date`);assert.equal(Number(result.rows[0].current_ar),300);
result=await db.query(`select current_ar from monthly_business_performance_report where company_id='${a}' and month_start<date_trunc('month',current_date)::date`);assert.equal(result.rows[0].current_ar,null);
// Security-invoker views obey the underlying company RLS; test in isolation.
for(const table of ['customers','party_ledgers','customer_invoice_aging','sales_margin_report','purchase_register_report','invoice_payment_allocations','stock_godown_report','ledgers','account_mappings']) await db.exec(`alter table ${table} enable row level security;create policy tenant on ${table} to authenticated using(company_id=current_setting('test.company')::uuid);grant select on ${table} to authenticated;`);
await db.exec(`grant select on chart_of_accounts,business_unit_performance_report,monthly_business_performance_report to authenticated;set test.company='${a}';set role authenticated;`);
result=await db.query('select * from business_unit_performance_report');assert.equal(result.rows.length,1);assert.equal(result.rows[0].company_id,a);
result=await db.query('select sum(outstanding_amount) total from customer_receivable_aging_report');assert.equal(Number(result.rows[0].total),300);
await db.exec(`reset role; update party_ledgers set credit=400;`);
result=await db.query(`select outstanding_amount from customer_receivable_aging_report where source_type='Opening / Unallocated'`);assert.equal(Number(result.rows[0].outstanding_amount),-200);
await db.close();console.log('Opening reporting: residuals, signed credits, ledger-only BU, current MIS and tenant RLS passed.');
