// Isolated synthetic rehearsal: actual service posting and service-credit functions.
// Tenant/permission context and canonical journal materialization are fixture adapters.
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
process.on('uncaughtException',error=>{console.error(error.message);process.exit(1);});
const db=new PGlite();const sql=p=>readFileSync(new URL(`../migrations/${p}`,import.meta.url),'utf8');
const company='00000000-0000-0000-0000-000000000001',bu='00000000-0000-0000-0000-000000000002',loc='00000000-0000-0000-0000-000000000003',user='00000000-0000-0000-0000-000000000004',customer='00000000-0000-0000-0000-000000000005',vehicle='00000000-0000-0000-0000-000000000006',vehicle2='00000000-0000-0000-0000-000000000007',ar='00000000-0000-0000-0000-000000000010',sales='00000000-0000-0000-0000-000000000011',service='00000000-0000-0000-0000-000000000012',vat='00000000-0000-0000-0000-000000000013',cashAccount='00000000-0000-0000-0000-000000000014';
await db.exec(`create role authenticated;create role anon;create schema auth;
set test.company='${company}';set test.bu='${bu}';set test.location='${loc}';set test.allowed='true';set test.actor='${user}';
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor'),'')::uuid$$;
create function current_company_id() returns uuid language sql as $$select current_setting('test.company')::uuid$$;
create function current_business_unit_id() returns uuid language sql as $$select current_setting('test.bu')::uuid$$;
create function current_operating_location_id() returns uuid language sql as $$select current_setting('test.location')::uuid$$;
create function has_module_permission(uuid,text,text) returns boolean language sql as $$select current_setting('test.allowed')::boolean$$;
create function assert_module_permission(text,text) returns void language plpgsql as $$begin if not current_setting('test.allowed')::boolean then raise exception 'Permission denied';end if;end$$;
create function transport_finance_assert(text) returns void language plpgsql as $$begin perform assert_module_permission('transport','post');end$$;
create function legacy_data_user_id() returns uuid language sql as $$select auth.uid()$$;
create function fixed_tax_rate_on(uuid,text,date) returns numeric language sql as $$select 15::numeric$$;
create function discount_amount_for(text,text) returns numeric language sql as $$select 0::numeric$$;
create function fx_mapping_account(uuid,uuid,text,text) returns uuid language sql as $$select case $3 when 'accounts_receivable' then '${ar}'::uuid when 'sales_revenue' then '${sales}'::uuid when 'service_revenue' then '${service}'::uuid when 'output_vat' then '${vat}'::uuid end$$;
create function transport_financial_append_only() returns trigger language plpgsql as $$begin raise exception 'Immutable evidence';end$$;
create table companies(id uuid primary key,base_currency_code text);
create table business_units(id uuid primary key,company_id uuid,unit_type text,is_active bool);
create table customers(id uuid primary key,company_id uuid,user_id uuid,name text,is_active bool,account_id uuid);
create table suppliers(id uuid primary key,company_id uuid,name text);
create table transport_vehicles(id uuid primary key,company_id uuid,business_unit_id uuid,vehicle_no text,is_active bool);
create table transport_trips(id uuid primary key,company_id uuid,business_unit_id uuid,transport_source_company text,transport_source_trip_id text,sales_order_id uuid);
create table chart_of_accounts(id uuid primary key,company_id uuid,code text,name text,type text,is_active bool,is_group bool);
create table sales_orders(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,business_unit_id uuid,operating_location_id uuid,order_no text,customer_id uuid,order_date date,status text,invoice_type text,tax_percent numeric,currency_code text,exchange_rate numeric,document_kind text,payment_mode text,created_by uuid,transport_source_company text,transport_source_invoice_id text,total numeric default 0,posted_at timestamptz,posted_by uuid,updated_at timestamptz,customer_name_snapshot text);
create table purchase_orders(id uuid primary key,company_id uuid,business_unit_id uuid,operating_location_id uuid,supplier_id uuid,document_kind text,status text,total numeric,tax_percent numeric,order_no text,order_date date);
create table sales_order_lines(order_id uuid);
create table consolidated_sales_invoices(main_sales_order_id uuid);
create table sales_service_lines(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,order_id uuid,description text,amount numeric,tax_percent numeric,revenue_account_id uuid,source_module text,source_id uuid,created_by uuid,unique(order_id,source_module,source_id));
create table purchase_service_lines(order_id uuid,amount numeric);
create table sales_order_charges(order_id uuid,company_id uuid,business_unit_id uuid,amount numeric,tax_percent numeric,account_id uuid);
create table journal_entries(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,business_unit_id uuid,operating_location_id uuid,entry_no text,entry_date date,description text,status text,party_name text,trans_type text,source_module text,source_document_type text,source_document_id uuid,reversal_of_entry_id uuid,created_at timestamptz default now());
create table journal_lines(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid,business_unit_id uuid,operating_location_id uuid,entry_id uuid,account_id uuid,account text,debit numeric default 0,credit numeric default 0,party_type text,party_id uuid,party_name text,amount_basis text);
create table ledgers(entry_id uuid,entry_date date,company_id uuid,account_id uuid,debit numeric,credit numeric);
create table party_ledgers(entry_id uuid,entry_date date,company_id uuid,party_id uuid,debit numeric,credit numeric);
create table transport_customer_documents(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,operating_location_id uuid,customer_id uuid,sales_order_id uuid unique,paid_amount numeric,created_by uuid,document_kind text,journal_entry_id uuid);
create table transport_supplier_documents(purchase_order_id uuid,journal_entry_id uuid);
create table return_notes(id uuid primary key,user_id uuid,company_id uuid,business_unit_id uuid,operating_location_id uuid,note_no text,note_type text,sales_order_id uuid,purchase_order_id uuid,party_type text,party_id uuid,party_name text,note_date date,reason text,status text,subtotal numeric,tax_total numeric,total numeric,cost_total numeric,journal_entry_id uuid);
create table transport_service_note_lines(id uuid primary key default gen_random_uuid(),company_id uuid,business_unit_id uuid,note_id uuid,side text,order_id uuid,net_amount numeric,vat_amount numeric,created_by uuid);
create table invoice_payment_allocations(sales_order_id uuid,journal_entry_id uuid,amount numeric,allocation_date date);
create table purchase_payment_allocations(purchase_order_id uuid,journal_entry_id uuid,amount numeric,allocation_date date);
create table transport_service_cost_links(purchase_order_id uuid,journal_entry_id uuid);
create table transport_service_refunds(side text,order_id uuid,journal_entry_id uuid,amount numeric);
create view transport_active_journals with(security_invoker=true) as select j.* from journal_entries j where status='posted' and not exists(select 1 from journal_entries r where r.reversal_of_entry_id=j.id and r.status='posted');
create sequence invoice_sequence;
create function transport_choose_invoice_number(text,text) returns text language sql as $$select coalesce($2,'AUTO-'||nextval('invoice_sequence'))$$;
create function post_journal_entry(uuid) returns jsonb language plpgsql as $$begin
 if (select sum(debit-credit) from journal_lines where entry_id=$1)<>0 then raise exception 'Unbalanced';end if;
 update journal_entries set status='posted' where id=$1;
 insert into ledgers select l.entry_id,j.entry_date,l.company_id,l.account_id,l.debit,l.credit from journal_lines l join journal_entries j on j.id=l.entry_id where l.entry_id=$1;
 insert into party_ledgers select l.entry_id,j.entry_date,l.company_id,l.party_id,l.debit,l.credit from journal_lines l join journal_entries j on j.id=l.entry_id where l.entry_id=$1 and party_id is not null;
 return '{}'::jsonb;end$$;
create view transport_party_document_sources with(security_invoker=true) as select 'customer'::text side,s.id order_id,s.company_id,s.business_unit_id,s.operating_location_id,s.customer_id party_id,s.customer_name_snapshot party_name,s.order_no,s.order_date,s.total original_gross,0::numeric original_net,null::uuid journal_entry_id,''::text kind,array[]::uuid[] trip_ids,''::text trip_no,''::text entry_no,null::date posted_date from sales_orders s where false;
create view transport_vehicle_contributions with(security_invoker=true) as select ''::text event_id,null::uuid company_id,null::uuid business_unit_id,null::uuid operating_location_id,null::uuid trip_id,''::text trip_no,null::uuid account_id,''::text account_name,null::date event_date,''::text entry_no,''::text event_type,''::text category,''::text expense_accounts,0::numeric revenue,0::numeric cost where false;
insert into companies values('${company}','SAR');insert into business_units values('${bu}','${company}','transport',true);
insert into customers values('${customer}','${company}','${user}','ENERCO',true,'${ar}');
insert into transport_vehicles values('${vehicle}','${company}','${bu}','7979',true),('${vehicle2}','${company}','${bu}','5731',true);
insert into chart_of_accounts values('${ar}','${company}','1100','Receivables','asset',true,false),('${sales}','${company}','4100','Sales Revenue','revenue',true,false),('${service}','${company}','4200','Service Revenue','revenue',true,false),('${vat}','${company}','2100','VAT','liability',true,false),('${cashAccount}','${company}','1000','Cash','asset',true,false);
`);
const core=sql('20261007104000_transport_customer_revenue_account.sql');await db.exec(core.slice(core.indexOf('create or replace function public.post_service_sales_invoice_core'),core.indexOf('create or replace function public.transport_create_charged_service_document_accounted')));
await db.exec(`create function post_sales_invoice(uuid) returns jsonb language sql as $$select post_service_sales_invoice_core($1)$$;`);
const adjustments=sql('20261001100200_transport_financial_adjustments.sql');await db.exec(adjustments.slice(adjustments.indexOf('create function public.transport_post_service_note'),adjustments.indexOf('create function public.transport_adjust_rate')));
await db.exec(sql('20261010070701_transport_external_invoice_import.sql'));
await db.exec(sql('20261010081645_fix_external_invoice_preview_removed_legacy_source.sql'));
const balances=sql('20261001100300_transport_financial_evidence_views.sql');await db.exec(balances.slice(balances.indexOf('create view public.transport_service_document_balances'),balances.indexOf('create view public.transport_trip_financial_summary')));
const row={source_reference:'16512',invoice_no:'2026-03098',invoice_date:'2026-08-31',customer:'ENERCO',sale_type:'Credit',vehicle_no:'7979',amount:3000,tax_percent:15,tax_amount:450,bill_amount:3450,description:'Delivery',reference_trip_no:'16512',reference_date:'2026-06-04',driver_name:'ASIF',from_location:'DAMMAM',to_location:'HAITH'};
const rows=[row,{...row,source_reference:'16521',reference_trip_no:'16521',reference_date:'2026-06-05',vehicle_no:'5731',amount:4250,tax_amount:637.5,bill_amount:4887.5}, {...row,source_reference:'CASH1',invoice_no:'',sale_type:'Cash',tax_percent:0,tax_amount:0,bill_amount:3000}];
const query=(text,params=[])=>db.query(text,params);
const value=async(text,params=[])=>(await query(text,params)).rows[0];
await db.exec(`create or replace function fixed_tax_rate_on(uuid,text,date) returns numeric language sql as $$select null::numeric$$;`);
const missingVat=await value(`select transport_preview_external_invoices('Twakkal',$1::jsonb) result`,[JSON.stringify(rows)]);
assert.match(missingVat.result.rows[0].import_reason,/No active Sales VAT/);
assert.equal(missingVat.result.rows[2].import_status,'New');
await db.exec(`create or replace function fixed_tax_rate_on(uuid,text,date) returns numeric language sql as $$select 15::numeric$$;`);
const preview=await value(`select transport_preview_external_invoices('Twakkal',$1::jsonb) result`,[JSON.stringify(rows)]);assert.equal(preview.result.rows.every(r=>r.import_status==='New'),true);
let result=await value(`select transport_import_external_invoices('Twakkal',$1,$2::jsonb) result`,[sales,JSON.stringify(rows)]);assert.equal(result.result.invoices,2);
assert.equal((await value('select count(*) n from transport_trips')).n,0);assert.equal((await value('select count(*) n from ledgers')).n,0);
const orders=(await query('select * from sales_orders order by order_no')).rows;const order=orders.find(o=>o.order_no==='2026-03098');const cash=orders.find(o=>o.payment_mode==='Cash');assert.equal(cash.invoice_type,'Sale Invoice');assert.equal(new Date(order.order_date).toISOString().slice(0,10),'2026-08-31');
await query('select post_sales_invoice($1)',[order.id]);await query('select post_sales_invoice($1)',[cash.id]);
assert.equal(Number((await value('select sum(credit-debit) n from ledgers where account_id=$1',[sales])).n),10250);
assert.equal(Number((await value('select sum(credit-debit) n from ledgers where account_id=$1',[vat])).n),1087.5);
assert.equal(Number((await value('select sum(debit-credit) n from party_ledgers')).n),11337.5);
assert.equal((await value('select count(*) n from transport_party_document_sources')).n,2);
assert.equal(Number((await value('select sum(revenue) n from transport_vehicle_contributions')).n),10250);
assert.equal((await value('select count(*) n from transport_customer_documents where paid_amount<>0')).n,0);
await assert.rejects(query(`select transport_import_external_invoices('Twakkal',$1,$2::jsonb)`,[sales,JSON.stringify(rows)]),/Import blocked/);
const ext=(await query('select * from transport_external_invoice_register where sales_order_id=$1 order by source_reference',[order.id])).rows;
const request='00000000-0000-0000-0000-000000000099';const credits=[{line_id:ext[0].id,amount:100},{line_id:ext[1].id,amount:200}];
result=await value(`select transport_post_external_invoice_note($1,$2,'credit','2026-09-01','Agreed reduction',$3::jsonb) result`,[request,order.id,JSON.stringify(credits)]);assert.equal(result.result.net,300);
const journals=(await value('select count(*) n from journal_entries')).n;
await query(`select transport_post_external_invoice_note($1,$2,'credit','2026-09-01','Agreed reduction',$3::jsonb)`,[request,order.id,JSON.stringify(credits)]);assert.equal((await value('select count(*) n from journal_entries')).n,journals);
await assert.rejects(query(`select transport_post_external_invoice_note(gen_random_uuid(),$1,'credit','2026-09-01','Over credit',$2::jsonb)`,[order.id,JSON.stringify([{line_id:ext[0].id,amount:4000}])]),/remaining value/);
assert.equal(Number((await value('select sum(revenue) n from transport_vehicle_contributions')).n),9950);
result=await value(`select transport_post_external_invoice_note(gen_random_uuid(),$1,'debit','2026-09-02','Additional amount',$2::jsonb) result`,[order.id,JSON.stringify([{line_id:ext[1].id,amount:500}])]);assert.ok(result.result.debit_order_id);
assert.equal(Number((await value('select sum(credit-debit) n from ledgers where account_id=$1',[sales])).n),10450);
assert.equal(Number((await value('select sum(debit-credit) n from party_ledgers')).n),11567.5);
assert.equal(Number((await value('select sum(revenue) n from transport_vehicle_contributions')).n),10450);
assert.equal((await value('select count(*) n from transport_party_document_sources')).n,3);
// A standard allocated receipt reduces receivables, not revenue; original and debit balances stay separate.
const receipt=(await value(`insert into journal_entries(user_id,company_id,business_unit_id,operating_location_id,entry_no,entry_date,status) values($1,$2,$3,$4,'RCPT','2026-09-03','draft') returning id`,[user,company,bu,loc])).id;
await query(`insert into journal_lines(user_id,company_id,business_unit_id,operating_location_id,entry_id,account_id,account,debit,credit,party_type,party_id) values($1,$2,$3,$4,$5,$6,'AR',0,1000,'customer',$7),($1,$2,$3,$4,$5,$8,'Cash',1000,0,null,null)`,[user,company,bu,loc,receipt,ar,customer,cashAccount]);
await query('select post_journal_entry($1)',[receipt]);
await query(`insert into invoice_payment_allocations values($1,$2,1000,'2026-09-03')`,[order.id,receipt]);
const balance=await value(`select * from transport_service_document_balances where side='customer' and order_id=$1`,[order.id]);
assert.equal(Number(balance.billed_gross),7992.5);assert.equal(Number(balance.paid_gross),1000);assert.equal(Number(balance.outstanding_gross),6992.5);
assert.equal(Number((await value('select sum(debit-credit) n from party_ledgers')).n),10567.5);assert.equal(Number((await value('select sum(debit-credit) n from ledgers where account_id=$1',[ar])).n),10567.5);
assert.equal(Number((await value('select sum(revenue) n from transport_vehicle_contributions')).n),10450);
// Reversal changes the attributed source, never creates another invoice or vehicle line.
const original=(await value('select journal_entry_id id from transport_customer_documents where sales_order_id=$1',[cash.id])).id;
await query(`insert into journal_entries(company_id,business_unit_id,operating_location_id,entry_no,entry_date,status,reversal_of_entry_id) values($1,$2,$3,'REV','2026-09-03','posted',$4)`,[company,bu,loc,original]);
assert.equal(Number((await value('select sum(revenue) n from transport_vehicle_contributions')).n),7450);
// Atomic validation: mixed valid/invalid file cannot leave a partial draft.
const before=(await value('select count(*) n from sales_orders')).n;
await assert.rejects(query(`select transport_import_external_invoices('Twakkal',$1,$2::jsonb)`,[sales,JSON.stringify([{...row,source_reference:'NEW1',invoice_no:'NEW1'},{...row,source_reference:'NEW2',invoice_no:'NEW2',vehicle_no:'MISSING'}])]),/Import blocked/);assert.equal((await value('select count(*) n from sales_orders')).n,before);
await db.exec(`set test.allowed='false';`);await assert.rejects(query(`select transport_import_external_invoices('Twakkal',$1,$2::jsonb)`,[sales,JSON.stringify(rows)]),/Permission denied/);await db.exec(`set test.allowed='true';`);
// Authenticated invoker views observe branch RLS on the new evidence tables.
for(const t of ['sales_orders','sales_service_lines','customers','journal_entries','transport_customer_documents','return_notes'])await db.exec(`grant select on ${t} to authenticated;`);
await db.exec(`grant usage on schema auth to authenticated;grant select on transport_active_journals,transport_party_document_sources,transport_vehicle_contributions to authenticated;set role authenticated;`);
assert.equal((await value('select count(*) n from transport_external_invoice_register')).n,4);
await db.exec(`set test.location='00000000-0000-0000-0000-000000000088';`);assert.equal((await value('select count(*) n from transport_external_invoice_register')).n,0);assert.equal((await value('select count(*) n from transport_external_vehicle_contributions')).n,0);
await db.close();console.log('External invoice rehearsal PASS: grouped vehicles, independent invoice dates, cash/credit, canonical AR/revenue/VAT, no trips or auto receipts, duplicates, atomic failure, credit/debit, allocated receipts/outstanding, idempotence, reversals, permission and branch RLS.');
