import { useCallback, useEffect, useState } from "react";
import { Check, Loader2, Plus, ShieldCheck, X } from "lucide-react";
import SearchableSelect from "@/components/SearchableSelect";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";
import { ErrorBanner, PageHeader, formatDate } from "@/components/ui";

type Step={step_no:number;approver_role:string;min_approvals:number};
type Workflow={id:string;name:string;document_type:string;business_unit_id:string|null;is_active:boolean;conditions:Record<string,unknown>;approval_steps:Step[]};
type RequestRow={id:string;document_type:string;document_id:string;status:string;requested_by:string|null;requested_at:string;current_step_no:number;request_context:Record<string,unknown>;approval_workflows:{name:string}|null};
const ROLES=["company_owner","admin","accounts","sales","purchase","store","production","transport"];
const DOCUMENTS=["sales_invoice","purchase_invoice","sales_order","purchase_order","journal_entry","stock_adjustment","payment","credit_note","debit_note","work_order"];
const roleLabel=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function ApprovalWorkflowSettings(){
  const{activeCompany,activeBusinessUnit,isPlatformOwner,user}=useAuth();
  const companyId=activeCompany?.company_id||"",businessUnitId=activeBusinessUnit?.business_unit_id||null;
  const allowed=isPlatformOwner||["company_owner","admin"].includes(activeBusinessUnit?.membership_role||activeCompany?.membership_role||"");
  const[workflows,setWorkflows]=useState<Workflow[]>([]),[requests,setRequests]=useState<RequestRow[]>([]);
  const[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
  const[name,setName]=useState(""),[documentType,setDocumentType]=useState("sales_invoice"),[minAmount,setMinAmount]=useState(""),[maxAmount,setMaxAmount]=useState("");
  const[allUnits,setAllUnits]=useState(false),[steps,setSteps]=useState<Step[]>([{step_no:1,approver_role:"admin",min_approvals:1}]);

  const load=useCallback(async()=>{if(!companyId){setLoading(false);return;}setLoading(true);setError("");const[w,r]=await Promise.all([
    supabase.from("approval_workflows").select("id,name,document_type,business_unit_id,is_active,conditions,approval_steps(step_no,approver_role,min_approvals)").eq("company_id",companyId).order("created_at"),
    supabase.from("approval_requests").select("id,document_type,document_id,status,requested_by,requested_at,current_step_no,request_context,approval_workflows(name)").eq("company_id",companyId).order("requested_at",{ascending:false}).limit(100)
  ]);if(w.error||r.error)setError(w.error?.message||r.error?.message||"Approval setup could not be loaded.");setWorkflows((w.data||[]) as unknown as Workflow[]);setRequests((r.data||[]) as unknown as RequestRow[]);setLoading(false);},[companyId]);
  useEffect(()=>{void load();},[load]);

  const addStep=()=>setSteps(v=>[...v,{step_no:v.length+1,approver_role:"admin",min_approvals:1}]);
  const updateStep=(i:number,patch:Partial<Step>)=>setSteps(v=>v.map((s,n)=>n===i?{...s,...patch,step_no:n+1}:s));
  const removeStep=(i:number)=>setSteps(v=>v.filter((_,n)=>n!==i).map((s,n)=>({...s,step_no:n+1})));
  const createWorkflow=async()=>{if(!allowed||!name.trim()||!steps.length){setError("Workflow name and at least one approval step are required.");return;}setBusy("create");setError("");setMessage("");const conditions:Record<string,number>={};if(minAmount!=="")conditions.min_amount=Number(minAmount);if(maxAmount!=="")conditions.max_amount=Number(maxAmount);const{data,error:e}=await supabase.from("approval_workflows").insert({company_id:companyId,business_unit_id:allUnits?null:businessUnitId,document_type:documentType,name:name.trim(),conditions,is_active:true}).select("id").single();if(e){setError(e.message);setBusy("");return;}const{error:se}=await supabase.from("approval_steps").insert(steps.map(s=>({workflow_id:data.id,...s})));if(se){await supabase.from("approval_workflows").delete().eq("id",data.id);setError(se.message);}else{setName("");setMinAmount("");setMaxAmount("");setSteps([{step_no:1,approver_role:"admin",min_approvals:1}]);setMessage("Approval workflow created.");await load();}setBusy("");};
  const toggleWorkflow=async(w:Workflow)=>{setBusy(w.id);setError("");const{error:e}=await supabase.from("approval_workflows").update({is_active:!w.is_active,updated_at:new Date().toISOString()}).eq("id",w.id);if(e)setError(e.message);else{setMessage(w.is_active?"Workflow disabled.":"Workflow enabled.");await load();}setBusy("");};
  const decide=async(id:string,decision:"approved"|"rejected")=>{const notes=window.prompt(`${roleLabel(decision)} notes (optional)`)??"";setBusy(id+decision);setError("");const{error:e}=await supabase.rpc("decide_approval_request",{p_request_id:id,p_decision:decision,p_notes:notes||null});if(e)setError(e.message);else{setMessage(`Request ${decision}.`);await load();}setBusy("");};

  if(!allowed)return <div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><strong>Company Owner / Administrator only.</strong> Approval workflow configuration is protected.</div>;
  if(loading)return <div className="flex min-h-[300px] items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading approval controls...</div>;
  return <div className="space-y-5"><PageHeader title="Approval Workflows" subtitle="Maker-checker steps, amount thresholds and immutable decision history"/>{error&&<ErrorBanner message={error}/>} {message&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-indigo-700"/><h2 className="font-semibold">New Workflow</h2></div><div className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" placeholder="Workflow name" value={name} onChange={e=>setName(e.target.value)}/><SearchableSelect className="input" value={documentType} onChange={e=>setDocumentType(e.target.value)}>{DOCUMENTS.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</SearchableSelect><input className="input" type="number" min="0" placeholder="Minimum amount (optional)" value={minAmount} onChange={e=>setMinAmount(e.target.value)}/><input className="input" type="number" min="0" placeholder="Maximum amount (optional)" value={maxAmount} onChange={e=>setMaxAmount(e.target.value)}/></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={allUnits} onChange={e=>setAllUnits(e.target.checked)}/>Apply to all business units (specific-unit workflow takes priority)</label><div className="mt-4 space-y-2">{steps.map((s,i)=><div key={i} className="grid items-center gap-2 rounded-lg border bg-slate-50 p-3 sm:grid-cols-[80px_1fr_180px_auto]"><strong className="text-sm">Step {i+1}</strong><SearchableSelect className="input" value={s.approver_role} onChange={e=>updateStep(i,{approver_role:e.target.value})}>{ROLES.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</SearchableSelect><label className="text-xs text-slate-600">Minimum approvals<input className="input mt-1 w-full" type="number" min="1" value={s.min_approvals} onChange={e=>updateStep(i,{min_approvals:Math.max(1,Number(e.target.value)||1)})}/></label><button className="btn-secondary" disabled={steps.length===1} onClick={()=>removeStep(i)}>Remove</button></div>)}</div><div className="mt-4 flex justify-between"><button className="btn-secondary" onClick={addStep}><Plus className="h-4 w-4"/>Add Step</button><button className="btn-primary" disabled={!!busy} onClick={()=>void createWorkflow()}>{busy==="create"?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Create Workflow</button></div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Configured Workflows</h2><div className="mt-3 space-y-2">{!workflows.length&&<p className="text-sm text-slate-500">No workflow configured yet.</p>}{workflows.map(w=><div key={w.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><div className="font-semibold">{w.name} <span className={`ml-2 rounded-full px-2 py-0.5 text-xs ${w.is_active?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{w.is_active?"Active":"Disabled"}</span></div><div className="text-xs text-slate-500">{roleLabel(w.document_type)} · {w.business_unit_id?"Current/specific business unit":"All business units"} · {[...(w.approval_steps||[])].sort((a,b)=>a.step_no-b.step_no).map(s=>`${s.step_no}. ${roleLabel(s.approver_role)} (${s.min_approvals})`).join(" → ")}</div></div><button className="btn-secondary" disabled={busy===w.id} onClick={()=>void toggleWorkflow(w)}>{w.is_active?"Disable":"Enable"}</button></div>)}</div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Approval Queue & History</h2><div className="mt-3 overflow-x-auto"><table className="table"><thead><tr><th>Requested</th><th>Workflow / Document</th><th>Step</th><th>Status</th><th>Amount</th><th></th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{formatDate(r.requested_at)}</td><td><div className="font-medium">{r.approval_workflows?.name||roleLabel(r.document_type)}</div><div className="text-xs text-slate-400">{r.document_id}</div></td><td>{r.current_step_no}</td><td className="capitalize">{r.status}</td><td>{String(r.request_context?.amount??"—")}</td><td>{r.status==="pending"&&r.requested_by!==user?.id?<div className="flex gap-2"><button className="btn-secondary text-emerald-700" disabled={!!busy} onClick={()=>void decide(r.id,"approved")}><Check className="h-4 w-4"/>Approve</button><button className="btn-secondary text-red-700" disabled={!!busy} onClick={()=>void decide(r.id,"rejected")}><X className="h-4 w-4"/>Reject</button></div>:<span className="text-xs text-slate-400">{r.requested_by===user?.id&&r.status==="pending"?"Maker cannot decide":"—"}</span>}</td></tr>)}{!requests.length&&<tr><td colSpan={6} className="py-8 text-center text-slate-500">No approval requests yet.</td></tr>}</tbody></table></div></section>
  </div>;
}
