import { useEffect,useMemo,useState,type ReactNode } from "react";
import { CalendarClock,CreditCard,FileText,Loader2,ShieldCheck } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";
import { PageHeader } from "@/components/ui";

type Subscription={status:string;billing_cycle:string;starts_at:string;expires_at:string|null;amount:number;currency_code:string;grace_days:number;auto_renew:boolean;plan:{name:string}|null};
type Invoice={id:string;invoice_number:string;status:string;issue_date:string;due_date:string;currency_code:string;total_amount:number;paid_amount:number};
const title=(value:string)=>value.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function LicenceBillingStatus(){
 const{activeCompany}=useAuth();const companyId=activeCompany?.company_id||"";
 const[sub,setSub]=useState<Subscription|null>(null),[invoices,setInvoices]=useState<Invoice[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!companyId){setLoading(false);return}setLoading(true);void Promise.all([
  supabase.from("company_subscriptions").select("status,billing_cycle,starts_at,expires_at,amount,currency_code,grace_days,auto_renew,plan:subscription_plans(name)").eq("company_id",companyId).in("status",["trial","active","past_due","suspended"]).order("created_at",{ascending:false}).limit(1),
  supabase.from("subscription_invoices").select("id,invoice_number,status,issue_date,due_date,currency_code,total_amount,paid_amount").eq("company_id",companyId).order("issue_date",{ascending:false}).limit(24),
 ]).then(([s,i])=>{const e=s.error||i.error;if(e){setError(e.message);return}setSub((s.data?.[0]??null) as unknown as Subscription|null);setInvoices((i.data??[]) as Invoice[])}).finally(()=>setLoading(false))},[companyId]);
 const due=useMemo(()=>invoices.reduce((sum,row)=>sum+Math.max(0,Number(row.total_amount)-Number(row.paid_amount)),0),[invoices]);
 const daysLeft=sub?.expires_at?Math.ceil((new Date(sub.expires_at).getTime()-Date.now())/86400000):null;
 if(loading)return <div className="flex min-h-[300px] items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading licence...</div>;
 return <div className="space-y-5"><PageHeader title="Licence & Billing" subtitle="Your NAVILO plan, renewal date, limits and subscription invoice history"/>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<ShieldCheck className="h-5 w-5"/>} label="Licence Status" value={title(sub?.status||activeCompany?.company_status||"not configured")}/><Card icon={<CreditCard className="h-5 w-5"/>} label="Plan" value={sub?.plan?.name||"Custom"}/><Card icon={<CalendarClock className="h-5 w-5"/>} label="Renewal / Expiry" value={sub?.expires_at?new Date(sub.expires_at).toLocaleDateString():"No expiry"}/><Card icon={<FileText className="h-5 w-5"/>} label="Outstanding" value={`${sub?.currency_code||invoices[0]?.currency_code||""} ${due.toFixed(2)}`.trim()}/></div>
  {daysLeft!==null&&daysLeft<=30&&<div className={`rounded-lg border p-3 text-sm ${daysLeft<0?"border-red-200 bg-red-50 text-red-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{daysLeft<0?`Licence expired ${Math.abs(daysLeft)} day(s) ago.`:`Licence expires in ${daysLeft} day(s).`} Contact the NAVILO Platform Owner for renewal.</div>}
  <section className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">Subscription Details</h2><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Detail label="Billing cycle" value={title(sub?.billing_cycle||"custom")}/><Detail label="Contract amount" value={`${sub?.currency_code||""} ${Number(sub?.amount||0).toFixed(2)}`.trim()}/><Detail label="Grace period" value={`${sub?.grace_days??0} days`}/><Detail label="Auto renew" value={sub?.auto_renew?"Enabled":"Not enabled"}/></div></section>
  <section className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">Billing History</h2><p className="mt-1 text-xs text-slate-500">Read-only company record. Payments and licence changes are controlled by the NAVILO Platform Owner.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b text-slate-500"><tr><th className="p-2">Invoice</th><th className="p-2">Issued</th><th className="p-2">Due</th><th className="p-2">Status</th><th className="p-2 text-right">Total</th><th className="p-2 text-right">Balance</th></tr></thead><tbody>{invoices.map(row=><tr key={row.id} className="border-b"><td className="p-2 font-semibold">{row.invoice_number}</td><td className="p-2">{row.issue_date}</td><td className="p-2">{row.due_date}</td><td className="p-2">{title(row.status)}</td><td className="p-2 text-right">{row.currency_code} {Number(row.total_amount).toFixed(2)}</td><td className="p-2 text-right font-bold">{(Number(row.total_amount)-Number(row.paid_amount)).toFixed(2)}</td></tr>)}{!invoices.length&&<tr><td colSpan={6} className="p-6 text-center text-slate-400">No subscription invoices issued yet.</td></tr>}</tbody></table></div></section>
 </div>;
}
function Card({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-indigo-700">{icon}<span className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</span></div><div className="mt-2 text-lg font-black text-slate-900">{value}</div></div>}
function Detail({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><div className="text-xs text-slate-500">{label}</div><div className="font-semibold text-slate-900">{value}</div></div>}
