import { useCallback,useEffect,useMemo,useState } from "react";
import { Check,ChevronRight,Loader2,Plus,RefreshCw,Send,X } from "lucide-react";
import SearchableSelect from "@/components/SearchableSelect";
import { PageHeader,formatCurrency,formatDate } from "@/components/ui";
import { supabase } from "@/lib/supabase";

type Side="sales"|"purchase";type Line={id:string;item_id:string;description:string|null;qty:number;unit_rate:number;tax_percent:number;remaining_qty?:number;item?:{name:string;sku:string|null;unit:string|null}|null};
type Doc={id:string;document_type:string;document_no:string;document_date:string;party_id:string|null;party_name:string|null;status:string;total:number;source_document_id:string|null;created_by:string;preinvoice_document_lines:Line[]};
type Option={id:string;name:string;sku?:string|null;unit?:string|null};
const FLOW={sales:["sales_quotation","sales_order","stock_reservation","dispatch"],purchase:["purchase_requisition","purchase_rfq","purchase_order","goods_receipt"]} as const;
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());const n=(v:unknown)=>Number(v)||0;
export default function PreInvoiceWorkspace({side}:{side:Side}){const types=FLOW[side];const[docs,setDocs]=useState<Doc[]>([]),[items,setItems]=useState<Option[]>([]),[parties,setParties]=useState<Option[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");const[open,setOpen]=useState(false),[selectedType,setSelectedType]=useState<string>(types[0]),[source,setSource]=useState<Doc|null>(null),[partyId,setPartyId]=useState(""),[notes,setNotes]=useState(""),[lines,setLines]=useState([{item_id:"",qty:"",unit_rate:"",tax_percent:"0",source_line_id:""}]);const[linkTarget,setLinkTarget]=useState("");const[candidates,setCandidates]=useState<{id:string;no:string;type:string}[]>([]);
 const load=useCallback(async()=>{setLoading(true);setError("");const[d,i,p]=await Promise.all([supabase.from("preinvoice_documents").select("id,document_type,document_no,document_date,party_id,party_name,status,total,source_document_id,created_by,preinvoice_document_lines(id,item_id,description,qty,unit_rate,tax_percent,item:items(name,sku,unit))").in("document_type",[...types]).order("created_at",{ascending:false}),supabase.from("items").select("id,name,sku,unit").eq("is_active",true).order("name"),supabase.from(side==="sales"?"customers":"suppliers").select("id,name").eq("is_active",true).order("name")]);if(d.error||i.error||p.error)setError(d.error?.message||i.error?.message||p.error?.message||"Workflow could not be loaded.");setDocs((d.data||[]) as unknown as Doc[]);setItems((i.data||[]) as Option[]);setParties((p.data||[]) as Option[]);setLoading(false);},[side]);useEffect(()=>{void load();},[load]);
 const reset=()=>{setOpen(false);setSource(null);setSelectedType(types[0]);setPartyId("");setNotes("");setLines([{item_id:"",qty:"",unit_rate:"",tax_percent:"0",source_line_id:""}]);};
 const openNew=()=>{reset();setOpen(true)};const openConvert=async(d:Doc)=>{const idx=types.indexOf(d.document_type as never);if(idx<0||idx===types.length-1)return;const next=types[idx+1];const progress=await supabase.from("preinvoice_line_progress").select("id,item_id,remaining_qty,unit_rate,tax_percent").eq("document_id",d.id);if(progress.error){setError(progress.error.message);return;}const rows=(progress.data||[]).filter(x=>n(x.remaining_qty)>0).map(x=>({item_id:x.item_id,qty:String(x.remaining_qty),unit_rate:String(x.unit_rate),tax_percent:String(x.tax_percent),source_line_id:x.id}));if(!rows.length){setError("No remaining quantity is available for conversion.");return;}setSource(d);setSelectedType(next);setPartyId(d.party_id||"");setNotes(`Converted from ${d.document_no}`);setLines(rows);setOpen(true);};
 const addLine=()=>setLines(v=>[...v,{item_id:"",qty:"",unit_rate:"",tax_percent:"0",source_line_id:""}]);const change=(i:number,k:string,v:string)=>setLines(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r));
 const save=async()=>{const party=parties.find(x=>x.id===partyId);if(!lines.length||lines.some(x=>!x.item_id||n(x.qty)<=0)){setError("Every line requires an item and positive quantity.");return;}setBusy("save");setError("");const payload=lines.map(x=>({...x,qty:n(x.qty),unit_rate:n(x.unit_rate),tax_percent:n(x.tax_percent),uom:items.find(i=>i.id===x.item_id)?.unit||null}));const{error:e}=await supabase.rpc("create_preinvoice_document",{p_document_type:selectedType,p_document_date:new Date().toISOString().slice(0,10),p_party_id:partyId||null,p_party_name:party?.name||source?.party_name||null,p_source_document_id:source?.id||null,p_valid_until:null,p_expected_date:null,p_terms:null,p_notes:notes||null,p_lines:payload});if(e)setError(e.message);else{setMessage(`${label(selectedType)} created.`);reset();await load();}setBusy("");};
 const transition=async(d:Doc,action:string)=>{let reason:string|null=null;if(action==="cancel"){reason=window.prompt("Cancellation reason");if(!reason)return;}setBusy(d.id+action);setError("");const{error:e}=await supabase.rpc("transition_preinvoice_document",{p_document_id:d.id,p_action:action,p_reason:reason});if(e)setError(e.message);else{setMessage(`${d.document_no} ${action} complete.`);await load();}setBusy("");};
 const loadTargets=async(d:Doc)=>{setSource(d);setLinkTarget("");if(d.document_type==="goods_receipt"){const q=await supabase.from("purchase_orders").select("id,order_no,status").eq("status","posted").order("order_date",{ascending:false});setCandidates((q.data||[]).map(x=>({id:x.id,no:x.order_no,type:"purchase_invoice"})));}else{const[a,g]=await Promise.all([supabase.from("sales_orders").select("id,order_no,status").eq("status","posted").order("order_date",{ascending:false}),supabase.from("gate_passes").select("id,pass_no,status").order("pass_date",{ascending:false})]);setCandidates([...(a.data||[]).map(x=>({id:x.id,no:x.order_no,type:"sales_invoice"})),...(g.data||[]).map(x=>({id:x.id,no:x.pass_no,type:"gate_pass"}))]);}};
 const linkFinal=async()=>{const target=candidates.find(x=>`${x.type}:${x.id}`===linkTarget);if(!source||!target)return;setBusy("link");const{error:e}=await supabase.rpc("link_preinvoice_posting_document",{p_source_document_id:source.id,p_target_type:target.type,p_target_id:target.id});if(e)setError(e.message);else{setMessage(`${source.document_no} linked to ${target.no}.`);setSource(null);setCandidates([]);setLinkTarget("");}setBusy("");};
 const grouped=useMemo(()=>types.map(t=>({type:t,rows:docs.filter(d=>d.document_type===t)})),[docs,types]);if(loading)return <div className="flex min-h-[300px] items-center justify-center"><Loader2 className="mr-2 animate-spin"/>Loading commercial workflow...</div>;
 return <div className="space-y-5"><PageHeader title={`${side==="sales"?"Sales":"Purchase"} Pre-Invoice Workflow`} subtitle={side==="sales"?"Quotation → Order → Reservation → Dispatch":"Requisition → RFQ → Purchase Order → Goods Receipt"}/>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button><button className="btn-primary" onClick={openNew}><Plus className="h-4 w-4"/>New {label(types[0])}</button></div><div className="grid gap-4 xl:grid-cols-4">{grouped.map(g=><section key={g.type} className="rounded-xl border bg-white p-3 shadow-sm"><h2 className="mb-3 font-bold">{label(g.type)} <span className="text-xs text-slate-400">({g.rows.length})</span></h2><div className="space-y-2">{g.rows.map(d=>{const idx=types.indexOf(d.document_type as never);return <article key={d.id} className="rounded-lg border p-3 text-xs"><div className="flex justify-between gap-2"><strong>{d.document_no}</strong><span className="capitalize">{d.status}</span></div><div className="mt-1 text-slate-500">{formatDate(d.document_date)} · {d.party_name||"Internal"}</div><div className="mt-1 font-semibold">{formatCurrency(n(d.total))}</div><div className="mt-3 flex flex-wrap gap-1">{d.status==="draft"&&<button className="btn-secondary h-7" onClick={()=>void transition(d,"submit")}>Submit</button>}{d.status==="submitted"&&<button className="btn-secondary h-7" onClick={()=>void transition(d,"approve")}><Check className="h-3 w-3"/>Approve</button>}{d.status==="approved"&&<button className="btn-secondary h-7" onClick={()=>void transition(d,"post")}>Post</button>}{["draft","submitted","approved"].includes(d.status)&&<button className="btn-secondary h-7 text-red-700" onClick={()=>void transition(d,"cancel")}><X className="h-3 w-3"/>Cancel</button>}{["approved","posted"].includes(d.status)&&idx<types.length-1&&<button className="btn-primary h-7" onClick={()=>void openConvert(d)}>Convert<ChevronRight className="h-3 w-3"/></button>}{d.status==="posted"&&idx===types.length-1&&<button className="btn-primary h-7" onClick={()=>void loadTargets(d)}>Link Final</button>}</div></article>})}{!g.rows.length&&<div className="py-8 text-center text-xs text-slate-400">No documents</div>}</div></section>)}</div>
 {open&&<div className="fixed inset-0 z-[180] overflow-y-auto bg-black/50 p-4"><div className="mx-auto my-6 max-w-4xl rounded-xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-bold">{label(selectedType)}</h2><p className="text-xs text-slate-500">{source?`Source: ${source.document_no}`:"New starting document"}</p></div><button onClick={reset}><X/></button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><SearchableSelect className="input" value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">Internal / no party</option>{parties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</SearchableSelect><input className="input" placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="mt-4 space-y-2">{lines.map((l,i)=><div key={i} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[2fr_1fr_1fr_1fr_auto]"><SearchableSelect className="input" disabled={!!source} value={l.item_id} onChange={e=>change(i,"item_id",e.target.value)}><option value="">Select item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</SearchableSelect><input className="input" type="number" min="0.0001" step="0.0001" placeholder="Qty" value={l.qty} onChange={e=>change(i,"qty",e.target.value)}/><input className="input" type="number" min="0" step="0.01" placeholder="Rate" value={l.unit_rate} onChange={e=>change(i,"unit_rate",e.target.value)}/><input className="input" type="number" min="0" step="0.01" placeholder="Tax %" value={l.tax_percent} onChange={e=>change(i,"tax_percent",e.target.value)}/><button disabled={lines.length===1} onClick={()=>setLines(x=>x.filter((_,n)=>n!==i))}><X className="h-4 w-4"/></button></div>)}</div><div className="mt-4 flex justify-between"><button className="btn-secondary" disabled={!!source} onClick={addLine}><Plus className="h-4 w-4"/>Add Line</button><button className="btn-primary" disabled={busy==="save"} onClick={()=>void save()}><Send className="h-4 w-4"/>Create</button></div></div></div>}
 {source&&candidates.length>0&&!open&&<div className="fixed inset-0 z-[180] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-5"><h2 className="font-bold">Link {source.document_no} to Final Document</h2><p className="mt-1 text-xs text-slate-500">Item quantities are validated; over-linking is blocked.</p><SearchableSelect className="input mt-4" value={linkTarget} onChange={e=>setLinkTarget(e.target.value)}><option value="">Select posted invoice / gate pass</option>{candidates.map(x=><option key={`${x.type}:${x.id}`} value={`${x.type}:${x.id}`}>{label(x.type)} · {x.no}</option>)}</SearchableSelect><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>{setSource(null);setCandidates([])}}>Close</button><button className="btn-primary" disabled={!linkTarget||busy==="link"} onClick={()=>void linkFinal()}>Link & Validate</button></div></div></div>}
 </div>}
