import {useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/auth/AuthContext';
export default function TransportDriverPayUpload({onChanged}:{onChanged?:()=>void}={}){
 const {activeCompany,activeBusinessUnit}=useAuth();const [rows,setRows]=useState<{trip_id:string;trip_no:string;amount:number;reason:string;error:string}[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [request,setRequest]=useState('');
 async function template(){const x=await import('xlsx');const w=x.utils.book_new();x.utils.book_append_sheet(w,x.utils.aoa_to_sheet([['Trip No','Driver Charge','Reason'],['TRIP-0001',0,'Agreed per-trip charge']]),'Driver charges');x.writeFile(w,'Transport-Driver-Charges-Template.xlsx')}
 async function parse(file:File){setError('');setRows([]);try{const x=await import('xlsx');const w=x.read(await file.arrayBuffer());const data=x.utils.sheet_to_json<Record<string,unknown>>(w.Sheets[w.SheetNames[0]],{defval:''});if(!data.length||data.length>500)throw Error('Upload 1–500 charges per reviewed batch');const lookup=new Map<string,string>();const names=[...new Set(data.map(r=>String(r['Trip No']).trim()))];for(let i=0;i<names.length;i+=200){const {data:trips,error}=await supabase.from('transport_trips').select('id,trip_no').eq('company_id',activeCompany?.company_id).eq('business_unit_id',activeBusinessUnit?.business_unit_id).in('trip_no',names.slice(i,i+200));if(error)throw error;trips?.forEach(t=>lookup.set(t.trip_no,t.id))}const seen=new Set<string>();setRows(data.map(r=>{const no=String(r['Trip No']).trim();const amount=Number(r['Driver Charge']);const reason=String(r.Reason||'').trim();const error=!lookup.has(no)?'Trip not found':seen.has(no)?'Duplicate Trip':r['Driver Charge']===''||!Number.isFinite(amount)||amount<0||Math.abs(amount*100-Math.round(amount*100))>0.000001?'Nonnegative charge, up to 2 decimals required':!reason?'Reason required':'';seen.add(no);return {trip_id:lookup.get(no)||'',trip_no:no,amount,reason,error}}));setRequest(crypto.randomUUID())}catch(e:any){setError(e.message)}}
 async function save(){setBusy(true);setError('');try{const r=await supabase.rpc('transport_driver_charge_upload',{p_request_id:request,p_rows:rows.map(({trip_id,amount,reason})=>({trip_id,amount,reason}))});if(r.error)throw r.error;setRows([]);onChanged?.();setError('Reviewed driver charges saved. Accrual and payment remain canonical Payroll transactions.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <details className="my-3 rounded border p-3"><summary>Upload agreed Driver charges from Excel · zero allowed</summary><p>Amounts set the per-trip obligation. Trips with existing payroll attribution require the existing correction workflow.</p><button className="btn" data-navilo-keep-local-action="true" onClick={()=>void template()}>Download template</button><input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void parse(f);e.target.value=''}}/>{error&&<p role="status">{error}</p>}<div className="max-h-64 overflow-auto"><table className="w-full"><thead><tr><th>Trip</th><th>Driver Charge</th><th>Reason</th><th>Validation</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.trip_no}</td><td>{r.amount}</td><td>{r.reason}</td><td>{r.error||'Ready'}</td></tr>)}</tbody></table></div><button className="btn-primary" disabled={busy||!rows.length||rows.some(r=>r.error)} onClick={()=>void save()}>{busy?'Saving…':'Save reviewed charges'}</button></details>;
}
