import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import * as XLSX from 'xlsx';
import {useAuth} from '@/auth/AuthContext';
import {supabase} from '@/lib/supabase';
import {fetchAllPages} from '@/lib/fetchAllPages';
import SearchableSelect from '@/components/SearchableSelect';
import {parseExternalInvoiceRows,type ExternalInvoiceRow} from './transportExternalInvoiceImport';
type Preview=ExternalInvoiceRow&{import_status:string;import_reason:string};
export default function TransportExternalInvoiceImport(){
 const {activeCompany,activeBusinessUnit}=useAuth();const scope=`${activeCompany?.company_id}/${activeBusinessUnit?.business_unit_id}`;
 const input=useRef<HTMLInputElement>(null);const generation=useRef(0);const submitting=useRef(false);
 const [source,setSource]=useState('Twakkal'),[account,setAccount]=useState(''),[accounts,setAccounts]=useState<{id:string;name:string}[]>([]),[rows,setRows]=useState<Preview[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[file,setFile]=useState('');
 useEffect(()=>{const request=++generation.current;setRows([]);setFile('');setError('');setMessage('');setAccount('');setAccounts([]);setBusy(false);
 if(!activeCompany?.company_id)return;
 void Promise.all([fetchAllPages<{id:string;name:string}>((from,to)=>supabase.from('chart_of_accounts').select('id,name').eq('company_id',activeCompany.company_id).eq('type','revenue').eq('is_active',true).eq('is_group',false).order('id').range(from,to)),supabase.from('account_mappings').select('account_id').eq('company_id',activeCompany.company_id).eq('mapping_key','sales_revenue').maybeSingle()]).then(([list,mapping])=>{if(request!==generation.current)return;if(mapping.error)throw mapping.error;setAccounts(list);if(list.some(a=>a.id===mapping.data?.account_id))setAccount(mapping.data!.account_id);}).catch(e=>{if(request===generation.current)setError(e.message)});
 return()=>{generation.current++};
 },[scope]);
 function download(){const headers=['TRIP NO.','DATE','TRUCK TYPE','PO-DO-JOB NO.','INVOICED','Invoice / Bill Date','COMPANY NAME','DRIVER NAME-MOBILE','OWNER','PLATE #','FROM','TO','RATE WITH COMPANY','TAX (%)','TAX AMOUNT','BILL AMOUNT','Cash/Credit','Discription'];const sample=['16512','2026-06-04','Small Dyna','PO007206','2026-03098','2026-08-31','Customer A','Driver','Owner','7979','Dammam','Haith',3000,15,450,3450,'Credit','Transport service'];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([headers,sample]),'Invoices');XLSX.writeFile(wb,'NAVILO-External-Transport-Invoices.xlsx');}
 async function choose(e:React.ChangeEvent<HTMLInputElement>){const selected=e.target.files?.[0];e.target.value='';if(!selected||submitting.current||busy)return;const request=generation.current;setBusy(true);setError('');setMessage('');setRows([]);setFile('');try{if(selected.size>5*1024*1024)throw new Error('Maximum file size is 5 MB.');if(!source.trim())throw new Error('Enter the source company.');const wb=XLSX.read(await selected.arrayBuffer(),{type:'array',cellDates:true});const data=parseExternalInvoiceRows(XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:''}));if(request!==generation.current)return;const preview=await supabase.rpc('transport_preview_external_invoices',{p_source_company:source.trim(),p_rows:data});if(preview.error)throw preview.error;if(request===generation.current){setRows(preview.data.rows);setFile(selected.name);}}catch(e:any){if(request===generation.current)setError(e.message||'Unable to read invoices.');}finally{if(request===generation.current)setBusy(false);}}
 async function run(){if(submitting.current||busy||!account||!rows.length||rows.some(r=>r.import_status!=='New'))return;const request=generation.current;submitting.current=true;setBusy(true);setError('');setMessage('');try{const result=await supabase.rpc('transport_import_external_invoices',{p_source_company:source.trim(),p_revenue_account_id:account,p_rows:rows.map(({import_status,import_reason,...r})=>r)});if(result.error)throw result.error;if(request===generation.current){setMessage(`${result.data.invoices} draft invoice(s) / cash bill(s), ${result.data.lines} vehicle lines imported. Review and post in Sales. No trips or receipts were created.`);setRows([]);setFile('');}}catch(e:any){if(request===generation.current)setError(e.message||'Import failed.');}finally{submitting.current=false;if(request===generation.current)setBusy(false);}}
 const totals=rows.reduce((a,r)=>({net:a.net+r.amount,vat:a.vat+r.tax_amount,total:a.total+r.bill_amount}),{net:0,vat:0,total:0});
 return <div className="space-y-2"><p className="text-xs text-slate-600">Import ready invoices without creating trips. INVOICED supplies the number; Invoice / Bill Date supplies the posting date. Cash uses zero VAT and automatic numbering when blank. CLEARED is treated as blank. Payments are recorded separately.</p><div className="flex flex-wrap items-end gap-2"><label className="text-xs">Source company<input className="input" aria-label="External source company" value={source} disabled={busy} onChange={e=>{setSource(e.target.value);setRows([]);setFile('');}}/></label><label className="text-xs">Revenue account<SearchableSelect nativeCompatibility preserveLabel aria-label="External revenue account" className="input" value={account} disabled={busy} onChange={e=>setAccount(e.target.value)}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></label><button className="btn" disabled={busy} onClick={download}>Download Template</button><button className="btn" disabled={busy} onClick={()=>input.current?.click()}>Choose File</button><input ref={input} type="file" accept=".xlsx,.xls,.csv" aria-label="External invoice file" className="hidden" onChange={e=>void choose(e)}/><button className="btn-primary" disabled={busy||!account||!rows.length||rows.some(r=>r.import_status!=='New')} onClick={()=>void run()}>{busy?'Checking…':'Import Draft Invoices'}</button></div>{error&&<p role="alert" className="text-xs text-red-700">{error}</p>}{message&&<p role="status" className="text-xs text-emerald-700">{message}</p>}{file&&<p className="text-xs">{file} · {rows.length} lines · Net {totals.net.toFixed(2)} · VAT {totals.vat.toFixed(2)} · Total {totals.total.toFixed(2)}</p>}{rows.length>0&&<div className="max-h-64 overflow-auto border"><table className="w-full text-left text-xs"><thead><tr>{['Invoice','Invoice date','Customer','Type','Vehicle','Net','VAT','Total','Status','Reason'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.source_reference}><td>{r.invoice_no||'Auto cash bill'}</td><td>{r.invoice_date}</td><td>{r.customer}</td><td>{r.sale_type}</td><td>{r.vehicle_no}</td><td>{r.amount.toFixed(2)}</td><td>{r.tax_amount.toFixed(2)}</td><td>{r.bill_amount.toFixed(2)}</td><td>{r.import_status}</td><td>{r.import_reason}</td></tr>)}</tbody></table></div>}<Link className="text-xs text-blue-700 underline" to="/sales">Review Sales invoices / cash bills</Link></div>;
}
