import {useTransportOutputPermissions} from './useTransportOutputPermissions';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {useAuth} from '@/auth/AuthContext';
import {supabase} from '@/lib/supabase';
import {fetchAllPages} from '@/lib/fetchAllPages';
import TransportPartyReports from './TransportPartyReports';
import TransportAccountStatement from './TransportAccountStatement';
import {exportPartyReport,type ReportTable} from './transportPartyExport';
import {financialNumber} from './transportFinancialTypes';
type Trip={id:string;trip_no:string;trip_date:string;customer_name:string|null;vehicle_no:string|null;driver_name:string|null;financial_status:string;billed_customer_net:number;billed_supplier_net:number;driver_accrued:number;other_cost_net:number;trip_profit:number;customer_outstanding_gross:number;supplier_outstanding_gross:number;driver_outstanding:number};
export default function TransportReports(){
 const outputAllowed=useTransportOutputPermissions();
 const {activeCompany,activeBusinessUnit}=useAuth();const [mode,setMode]=useState<'party'|'driver'|'vehicle'|'profit'>('party');const [rows,setRows]=useState<Trip[]>([]);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await fetchAllPages<Trip>((start,end)=>supabase.from('transport_financial_register').select('id,trip_no,trip_date,customer_name,vehicle_no,driver_name,financial_status,billed_customer_net,billed_supplier_net,driver_accrued,other_cost_net,trip_profit,customer_outstanding_gross,supplier_outstanding_gross,driver_outstanding').order('id').range(start,end)))}catch(e:any){setRows([]);setError(e?.message||'Unable to load posted profitability.')}finally{setLoading(false)}},[activeCompany?.company_id,activeBusinessUnit?.business_unit_id]);
 useEffect(()=>{void load()},[load]);
 const matching=useMemo(()=>rows.filter(r=>(!from||r.trip_date>=from)&&(!to||r.trip_date<=to)),[rows,from,to]);
 const report:ReportTable={title:'Transport posted Trip profitability',description:`${activeCompany?.company_name||''} / ${activeBusinessUnit?.business_unit_name||''} / active branch · Trip dates ${from||'Beginning'} to ${to||'all dates'} · Current posted financial evidence in company base currency. Draft operational rates are excluded. Profit is net of VAT; outstanding is gross.`,columns:['Trip','Trip date','Customer','Vehicle','Driver','Financial status','Posted revenue net','Posted cost net','Posted profit','Customer outstanding gross','Supplier outstanding gross','Driver outstanding'],rows:matching.map(r=>[r.trip_no,r.trip_date,r.customer_name||'',r.vehicle_no||'',r.driver_name||'',r.financial_status,Number(r.billed_customer_net||0),Number(r.billed_supplier_net||0)+Number(r.driver_accrued||0)+Number(r.other_cost_net||0),r.trip_profit==null?'':Number(r.trip_profit),Number(r.customer_outstanding_gross||0),Number(r.supplier_outstanding_gross||0),Number(r.driver_outstanding||0)])};
 async function output(format:'print'|'pdf'|'xlsx'){if(!(format==='print'?outputAllowed.print:outputAllowed.export))return;try{await exportPartyReport(report,format)}catch(e:any){setError(e?.message||'Export failed')}}
 return <div className="space-y-3"><h1 className="text-xl font-bold">Transport Reports</h1><div className="flex flex-wrap gap-2">{([['party','Customer and Supplier'],['driver','Driver statement'],['vehicle','Vehicle statement'],['profit','Posted Trip profitability']] as const).map(([key,label])=><button className={mode===key?'btn-primary':'btn'} key={key} onClick={()=>setMode(key)}>{label}</button>)}</div>
 {mode==='party'&&<TransportPartyReports onClose={()=>setMode('profit')} onChanged={load}/>}{mode==='driver'&&<TransportAccountStatement kind="driver"/>}{mode==='vehicle'&&<TransportAccountStatement kind="vehicle"/>}
 {mode==='profit'&&<section className="rounded border bg-white p-3 text-xs"><div className="flex flex-wrap gap-2"><label>Trip date From<input type="date" className="input" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Trip date To<input type="date" className="input" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn" onClick={()=>void load()}>Refresh</button></div>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p role="status">Loading posted evidence…</p>:from&&to&&from>to?<p role="alert">From must be on or before To.</p>:!error&&<><p className="my-2" data-business-data>{report.description}</p><div className="mb-2 flex gap-2">{(['print','pdf','xlsx'] as const).map(f=><button className="btn" data-navilo-keep-local-action="true" key={f} disabled={!(f==='print'?outputAllowed.print:outputAllowed.export)} onClick={()=>void output(f)}>{f==='xlsx'?'Excel':f.toUpperCase()}</button>)}</div><div className="max-h-[60vh] overflow-auto"><table className="w-full whitespace-nowrap text-left"><thead><tr>{report.columns.map(c=><th className="p-2" key={c}>{c}</th>)}</tr></thead><tbody data-business-data>{report.rows.map((r,i)=><tr className="border-t" key={i}>{r.map((v,k)=><td className="p-2" key={k}>{typeof v==='number'?financialNumber(v):v}</td>)}</tr>)}</tbody></table></div></>}
 </section>}</div>;
}
