// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import TransportInitialRate from './TransportInitialRate';
const mock=vi.hoisted(()=>({rpc:vi.fn(),allowed:true,fail:false}));
vi.mock('@/auth/AuthContext',()=>({useAuth:()=>({activeCompany:{company_id:'c'},activeBusinessUnit:{business_unit_id:'b'}})}));
vi.mock('@/lib/supabase',()=>({supabase:{rpc:mock.rpc}}));
beforeEach(()=>{mock.allowed=true;mock.fail=false;mock.rpc.mockReset();mock.rpc.mockImplementation(async(name:string)=>({data:name==='has_transport_action_permission'?mock.allowed:null,error:name==='transport_finalize_initial_customer_rate'&&mock.fail?{message:'Rate already finalized'}:null}))});afterEach(cleanup);
const trip={id:'t',trip_no:'T-1',customer_name:'Customer',from_location:'A',to_location:'B',customer_rate_state:'pending' as const};
describe('One-time dashboard rate',()=>{
 it('requires permission and a finite two-decimal rate',async()=>{mock.allowed=false;render(<TransportInitialRate trip={trip} onClose={vi.fn()} onChanged={async()=>{}}/>);fireEvent.change(screen.getByLabelText('Customer rate excluding VAT'),{target:{value:'20'}});await waitFor(()=>expect(mock.rpc).toHaveBeenCalled());expect((screen.getByRole('button',{name:'Finalize Rate'}) as HTMLButtonElement).disabled).toBe(true)});
 it('finalizes through the one-time RPC and refreshes the register',async()=>{const changed=vi.fn(async()=>{});const close=vi.fn();render(<TransportInitialRate trip={trip} onClose={close} onChanged={changed}/>);const field=screen.getByLabelText('Customer rate excluding VAT');fireEvent.change(field,{target:{value:'20.123'}});await waitFor(()=>expect(mock.rpc).toHaveBeenCalled());expect((screen.getByRole('button',{name:'Finalize Rate'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(field,{target:{value:'20.12'}});fireEvent.click(screen.getByRole('button',{name:'Finalize Rate'}));await waitFor(()=>expect(close).toHaveBeenCalled());expect(mock.rpc).toHaveBeenCalledWith('transport_finalize_initial_customer_rate',{p_trip_id:'t',p_amount:20.12});expect(changed).toHaveBeenCalledTimes(1)});
 it('shows the competing finalization error without silently calling an override',async()=>{mock.fail=true;render(<TransportInitialRate trip={trip} onClose={vi.fn()} onChanged={async()=>{}}/>);fireEvent.change(screen.getByLabelText('Customer rate excluding VAT'),{target:{value:'50'}});await waitFor(()=>expect((screen.getByRole('button',{name:'Finalize Rate'}) as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Finalize Rate'}));await screen.findByText('Rate already finalized');expect(mock.rpc.mock.calls.some(([name])=>name==='transport_finalize_customer_rate')).toBe(false)});
});
