import {useAuth} from '@/auth/AuthContext';
import {supabase} from '@/lib/supabase';
import {useEffect,useRef,useState} from 'react';
import NaviloDateInput from '@/components/NaviloDateInput';
import {formatNaviloDate} from '@/lib/naviloDate';
import ConfigurableReport from './ConfigurableReport';
import type {ReportTable} from './transportPartyExport';
export default function TransportTripReports({side='customer',accountKind,party='',accountId=''}:{accountId?:string;party?:string;side?:'customer'|'supplier';accountKind?:'driver'|'vehicle'}){
 const {activeCompany,activeBusinessUnit}=useAuth();const [rows,setRows]=useState<any[]>([]);const [summary,setSummary]=useState<any>({});const [filters,setFilters]=useState({from:'',to:'',search:'',posting:'posted',party:''});const [page,setPage]=useState(0);const [count,setCount]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const generation=useRef(0);
 useEffect(()=>{const token=++generation.current;setLoading(true);setError('');const timer=setTimeout(()=>{if(filters.from&&filters.to&&filters.from>filters.to){setError('From must be on or before To');setLoading(false);return}void supabase.rpc('transport_trip_report',{p_side:side,p_limit:500,p_offset:page*500,p_filters:{...filters,party,account:accountId,accountKind}}).then(({data,error})=>{if(token!==generation.current)return;if(error){setError(error.message);setRows([])}else{setRows(data?.rows||[]);setCount(data?.count||0);setSummary(data?.summary||{})}setLoading(false)});},200);return()=>{clearTimeout(timer);generation.current++}},[side,party,accountId,accountKind,filters,page,activeCompany?.company_id,activeBusinessUnit?.business_unit_id]);
 function filter(key:string,value:string){setFilters(f=>({...f,[key]:value}));setPage(0)}
 function makeReport(rows:any[]):ReportTable{return {title:`Transport ${accountKind||side} Trip-wise statement`,description:`${activeCompany?.company_name||''} / ${activeBusinessUnit?.business_unit_name||''} · ${filters.posting} ${side} invoices · Trip dates ${filters.from||'Beginning'} to ${filters.to||'all dates'} · ${count} matching trips. Revenue ${Number(summary.revenue||0).toFixed(2)} · Cost ${Number(summary.cost||0).toFixed(2)} · Contribution ${Number(summary.profit||0).toFixed(2)} · Margin ${summary.revenue?((summary.profit||0)/summary.revenue*100).toFixed(2):'0.00'}%. Totals cover the complete filter. Unposted agreed rates are estimates, excluded from posted balances. Vehicle and driver are current operational labels.`,columns:['Trip','Date','Customer','Supplier / Owner','Vehicle','Driver','From','To','Job / PO / DO','Truck type','Ownership at Trip','Customer invoice','Supplier invoice','Agreed customer rate','Agreed supplier rent','Agreed driver charge','Posted revenue net','Posted supplier cost net','Posted driver charge','Posted other cost net','Posted contribution','Margin %','Customer outstanding gross','Supplier outstanding gross','Driver outstanding'],rows:rows.map(r=>[r.trip_no,formatNaviloDate(r.trip_date),r.customer_name||'',r.owner_name||'',r.vehicle_no||'',r.driver_name||'',r.from_location||'',r.to_location||'',r.po_do_job_no||'',r.truck_type_name||'',r.ownership_class||'Unattributed',r.customer_posted?'Posted':'Unposted',r.supplier_posted?'Posted':'Unposted',Number(r.customer_rate||0),Number(r.agreed_supplier_rent||0),Number(r.driver_pay||0),Number(r.billed_customer_net||0),Number(r.billed_supplier_net||0),Number(r.driver_accrued||0),Number(r.other_cost_net||0),Number(r.billed_customer_net||0)-Number(r.billed_supplier_net||0)-Number(r.driver_accrued||0)-Number(r.other_cost_net||0),r.billed_customer_net?(Number(r.billed_customer_net||0)-Number(r.billed_supplier_net||0)-Number(r.driver_accrued||0)-Number(r.other_cost_net||0))/Number(r.billed_customer_net)*100:0,Number(r.customer_outstanding_gross||0),Number(r.supplier_outstanding_gross||0),Number(r.driver_outstanding||0)])};}
 const report=makeReport(rows);
 async function allExport(){const all:any[]=[];for(let offset=0;;offset+=500){const r=await supabase.rpc('transport_trip_report',{p_side:side,p_limit:500,p_offset:offset,p_filters:{...filters,party,account:accountId,accountKind}});if(r.error)throw r.error;all.push(...r.data.rows);if(all.length>=r.data.count||!r.data.rows.length)break}return makeReport(all)}
 return <div className="my-3 rounded border p-3 space-y-2"><div className="flex flex-wrap gap-2"><label>Invoice posting<select className="input" value={filters.posting} onChange={e=>filter('posting',e.target.value)}><option value="posted">Posted only</option><option value="unposted">Unposted only</option><option value="all">All trips</option></select></label><label>From<NaviloDateInput className="input" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label>To<NaviloDateInput className="input" value={filters.to} onChange={e=>filter('to',e.target.value)}/></label><label>Trip / Party / Driver / Vehicle / Route<input className="input" value={filters.search} onChange={e=>filter('search',e.target.value)}/></label></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p role="status">Loading filtered trips…</p>:!error&&<><div className="flex gap-2"><button className="btn" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous 500</button><span>{page*500+Math.min(count,1)}–{Math.min((page+1)*500,count)} / {count}</span><button className="btn" disabled={(page+1)*500>=count} onClick={()=>setPage(p=>p+1)}>Next 500</button></div><ConfigurableReport loadExport={allExport} report={report} preferenceKey={`${activeCompany?.company_id}:${side}:${accountKind||'party'}:trips`}/><p>Excel, PDF and print include all matching trips. Totals cover the complete filter.</p></>}</div>;
}
