import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/auth/AuthContext';
import NaviloDateInput from '@/components/NaviloDateInput';
import {financialNumber} from './transportFinancialTypes';

type Row={id:string;trip_no:string;trip_date:string;financial_status?:string|null;customer_id?:string|null;customer_name?:string|null;vehicle_no?:string|null;driver_name?:string|null;from_location?:string|null;to_location?:string|null;po_do_job_no?:string|null;customer_rate?:number|null;customer_rate_state?:string|null;billed_customer_net?:number|null;sale_type?:string|null};
const fmt=(v:string)=>{if(!v)return '—';const [y,m,d]=v.slice(0,10).split('-').map(Number);return `${String(d).padStart(2,'0')}-${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m-1]}-${String(y).slice(-2)}`};

export default function TransportBulkCustomerRate({onClose,onChanged}:{onClose:()=>void;onChanged:()=>Promise<void>}){
 const {activeCompany,activeBusinessUnit}=useAuth();
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<string[]>([]),[amounts,setAmounts]=useState<Record<string,string>>({});
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[reason,setReason]=useState('Bulk customer rate'),[withTax,setWithTax]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[correction,setCorrection]=useState<Row|null>(null),[correctionAmount,setCorrectionAmount]=useState('');
 async function load(){const r=await supabase.rpc('transport_financial_register_page',{p_limit:1000,p_offset:0});if(r.error)throw r.error;setRows((r.data??[]) as Row[])}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[activeCompany?.company_id,activeBusinessUnit?.business_unit_id]);
 const posted=(r:Row)=>Number(r.billed_customer_net??0)>0;
 const statuses=useMemo(()=>[...new Set(rows.map(r=>r.financial_status).filter((x):x is string=>!!x))].sort(),[rows]);
 const visible=rows.filter(r=>!status||r.financial_status===status).filter(r=>!search||[r.trip_no,r.customer_name,r.vehicle_no,r.driver_name,r.from_location,r.to_location,r.po_do_job_no].some(v=>String(v??'').toLowerCase().includes(search.toLowerCase())));
 const toggle=(id:string,on:boolean)=>setSelected(v=>on?[...new Set([...v,id])]:v.filter(x=>x!==id));
 async function finalize(){if(!selected.length||!reason.trim())return;setBusy(true);setError('');setMessage('');let done=0;try{for(const id of selected){const row=rows.find(r=>r.id===id)!;if(posted(row))continue;const amount=Number(amounts[id]??row.customer_rate??'');if(!(amount>=0))throw new Error(`Enter valid rate for ${row.trip_no}`);const x=await supabase.rpc('transport_finalize_customer_rate',{p_trip_id:id,p_amount:amount,p_source:'manual',p_reason:reason.trim()});if(x.error)throw x.error;done++}await load();await onChanged();setSelected([]);setMessage(`${done} customer rate(s) saved/finalized — editable until Sales posting.`)}catch(e:any){setError(`${e?.message||e} · ${done} saved before this error.`)}finally{setBusy(false)}}
 async function post(){if(!selected.length)return;setBusy(true);setError('');setMessage('');let done=0;try{for(const id of selected){const row=rows.find(r=>r.id===id)!;if(posted(row)||row.customer_rate_state!=='finalized')continue;const x=await supabase.rpc('transport_post_customer_bill',{p_trip_id:id,p_date:date,p_with_tax:withTax});if(x.error)throw x.error;done++}await load();await onChanged();setSelected([]);setMessage(`${done} finalized customer rate(s) posted to canonical Sales / Accounts Receivable.`)}catch(e:any){setError(`${e?.message||e} · ${done} posted before this error.`)}finally{setBusy(false)}}
 async function correct(){if(!correction||!reason.trim()||correctionAmount==='')return;setBusy(true);setError('');try{const x=await supabase.rpc('transport_adjust_rate',{p_trip_id:correction.id,p_side:'customer',p_new_rate:Number(correctionAmount),p_reason:reason.trim(),p_date:date,p_rent_id:null,p_reference:'Bulk customer rate correction'});if(x.error)throw x.error;await load();await onChanged();setCorrection(null);setCorrectionAmount('');setMessage(`Posted rate corrected for ${correction.trip_no}; canonical AR adjustment created.`)}catch(e:any){setError(e?.message||'Rate correction failed')}finally{setBusy(false)}}
 return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-900/40 p-3"><section className="flex max-h-[88vh] w-full max-w-[1180px] flex-col overflow-hidden rounded-lg bg-white p-2 text-[10px] shadow-xl">
 <div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">Bulk Customer Rate</h2><p className="text-[9px] text-slate-500">Select trips → finalize rates → post canonical Sales/AR. Posted rates use controlled correction only.</p></div><button className="btn" disabled={busy} onClick={onClose}>Close</button></div>
 {error&&<p className="my-2 text-red-700">{error}</p>}{message&&<p className="my-2 text-emerald-700">{message}</p>}
 <div className="my-2 grid grid-cols-12 items-end gap-1 rounded border bg-slate-50 p-1 text-[9px]"><label className="col-span-2">Date<NaviloDateInput className="input h-7" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="col-span-4">Reason<input className="input h-7 w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="col-span-2"><input type="checkbox" checked={withTax} onChange={e=>setWithTax(e.target.checked)}/> With VAT</label><label className="col-span-2">Trip Status<select className="input h-7" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="btn h-7" onClick={()=>setSelected(visible.filter(r=>!posted(r)).map(r=>r.id))}>Select All Unposted</button><label className="col-span-12">Search<input className="input h-7 w-full" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <div className="min-h-0 flex-1 overflow-y-auto border"><table className="w-full table-fixed text-left"><thead className="sticky top-0 bg-slate-100"><tr><th className="w-[5%] p-1">Sel.</th><th>Trip</th><th>Date</th><th>Company</th><th>Route</th><th>Vehicle</th><th>Sale Type</th><th>Rate</th><th>Status</th></tr></thead><tbody>{visible.map(r=>{const lock=posted(r);return <tr key={r.id} className="h-9 border-t"><td><input type="checkbox" disabled={lock||busy} checked={selected.includes(r.id)} onChange={e=>toggle(r.id,e.target.checked)}/></td><td className="font-semibold">{r.trip_no}</td><td>{fmt(r.trip_date)}</td><td>{r.customer_name||'—'}</td><td>{r.from_location||'—'} → {r.to_location||'—'}</td><td>{r.vehicle_no||'—'}</td><td>{r.sale_type||'—'}</td><td><input className="input h-7 w-full" type="number" min="0" step="0.01" disabled={lock||busy} value={lock?String(r.billed_customer_net??''):amounts[r.id]??String(r.customer_rate??'')} onChange={e=>setAmounts(v=>({...v,[r.id]:e.target.value}))}/></td><td>{lock?<div><span className="text-emerald-700">Posted {financialNumber(r.billed_customer_net)}</span><button className="ml-2 font-semibold text-blue-700 underline" onClick={()=>{setCorrection(r);setCorrectionAmount(String(r.billed_customer_net??r.customer_rate??''));setReason('')}}>Correct Rate</button></div>:r.customer_rate_state==='finalized'?<span className="text-blue-700">Finalized — Editable Until Post</span>:<span className="text-amber-700">Pending — Ready to Finalize</span>}</td></tr>})}</tbody></table></div>
 {correction&&<div className="border-t bg-blue-50 p-2"><div className="flex items-end gap-2"><strong>{correction.trip_no} · Posted Rate Correction</strong><span>Current: {financialNumber(correction.billed_customer_net)}</span><label>New Rate<input className="input h-7 w-28" type="number" min="0" step="0.01" value={correctionAmount} onChange={e=>setCorrectionAmount(e.target.value)}/></label><label className="flex-1">Correction Reason<input className="input h-7 w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn-primary h-7" disabled={busy||!reason.trim()} onClick={()=>void correct()}>Save Correction</button><button className="btn h-7" onClick={()=>setCorrection(null)}>Cancel</button></div><p className="mt-1 text-slate-600">Original invoice/receipt history stays unchanged; NAVILO posts only the difference as canonical AR adjustment.</p></div>}
 <div className="mt-2 flex items-center justify-between"><strong>{selected.length} trip(s) selected</strong><div className="flex gap-2"><button className="btn" disabled={busy||!selected.length||!reason.trim()} onClick={()=>void finalize()}>Finalize Selected</button><button className="btn-primary" disabled={busy||!selected.length} onClick={()=>void post()}>Post Finalized Selected</button></div></div>
 </section></div>
}