import { useEffect,useMemo,useState } from "react";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";
type Trip={id:string;trip_no:string;trip_date:string;status:string;ppr_status:string;customer_name:string|null;vehicle_no:string|null;driver_name:string|null;from_location:string|null;to_location:string|null;customer_rate:number;total_cost:number;trip_profit:number};
const money=(v:number)=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
export default function TransportReports(){
 const{activeCompany,activeBusinessUnit}=useAuth();const[rows,setRows]=useState<Trip[]>([]),[from,setFrom]=useState(""),[to,setTo]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{setLoading(true);setError("");let q=supabase.from("transport_trip_register").select("id,trip_no,trip_date,status,ppr_status,customer_name,vehicle_no,driver_name,from_location,to_location,customer_rate,total_cost,trip_profit").order("trip_date",{ascending:false});if(from)q=q.gte("trip_date",from);if(to)q=q.lte("trip_date",to);const{data,error:e}=await q;if(!live)return;if(e)setError(e.message);else setRows((data??[]) as Trip[]);setLoading(false)})();return()=>{live=false}},[activeCompany?.company_id,activeBusinessUnit?.business_unit_id,from,to]);
 const totals=useMemo(()=>rows.reduce((a,r)=>({revenue:a.revenue+Number(r.customer_rate||0),cost:a.cost+Number(r.total_cost||0),profit:a.profit+Number(r.trip_profit||0)}),{revenue:0,cost:0,profit:0}),[rows]);
 const group=(key:"customer_name"|"vehicle_no"|"driver_name")=>Array.from(rows.reduce((m,r)=>{const name=String(r[key]||"Unassigned"),v=m.get(name)||{name,trips:0,revenue:0,cost:0,profit:0};v.trips++;v.revenue+=Number(r.customer_rate||0);v.cost+=Number(r.total_cost||0);v.profit+=Number(r.trip_profit||0);m.set(name,v);return m},new Map<string,{name:string;trips:number;revenue:number;cost:number;profit:number}>()).values()).sort((a,b)=>b.revenue-a.revenue);
 const Table=({title,data}:{title:string;data:ReturnType<typeof group>})=><section className="rounded-xl border bg-white shadow-sm"><h2 className="border-b px-4 py-3 font-bold">{title}</h2><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr>{["Name","Trips","Revenue","Cost","Profit"].map(h=><th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr></thead><tbody>{data.map(r=><tr key={r.name} className="border-t"><td className="px-3 py-2 font-semibold">{r.name}</td><td className="px-3 py-2">{r.trips}</td><td className="px-3 py-2 text-right">{money(r.revenue)}</td><td className="px-3 py-2 text-right">{money(r.cost)}</td><td className="px-3 py-2 text-right font-bold">{money(r.profit)}</td></tr>)}</tbody></table></div></section>;
 return <div className="space-y-4"><section className="rounded-xl border bg-white p-4 shadow-sm"><h1 className="text-xl font-black">Transport Reports</h1><p className="mt-1 text-sm text-slate-500">Trip-based operational reporting from the Transport register. Accounting and Sales remain the financial source of truth.</p><div className="mt-3 flex flex-wrap gap-3"><label className="text-xs font-bold">From<input type="date" className="input ml-2" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs font-bold">To<input type="date" className="input ml-2" value={to} onChange={e=>setTo(e.target.value)}/></label></div></section>{error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<section className="grid gap-3 md:grid-cols-4">{[["Trips",rows.length],["Revenue",money(totals.revenue)],["Cost",money(totals.cost)],["Trip Profit",money(totals.profit)]].map(([k,v])=><div key={k} className="rounded-xl border bg-white p-4"><div className="text-xs font-bold uppercase text-slate-500">{k}</div><div className="mt-1 text-xl font-black">{k==="Trips"?"":"SAR "}{v}</div></div>)}</section>{loading?<div className="rounded-xl border bg-white p-6 text-sm text-slate-500">Loading transport reports…</div>:<><Table title="Customer-wise Transport Performance" data={group("customer_name")}/><Table title="Vehicle-wise Performance" data={group("vehicle_no")}/><Table title="Driver-wise Performance" data={group("driver_name")}/><section className="rounded-xl border bg-white shadow-sm"><h2 className="border-b px-4 py-3 font-bold">Trip Register & Profitability</h2><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr>{["Trip","Date","Customer","Vehicle","Driver","Route","Status","PPR","Revenue","Cost","Profit"].map(h=><th key={h} className="whitespace-nowrap px-3 py-2 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="px-3 py-2 font-bold">{r.trip_no}</td><td className="px-3 py-2">{r.trip_date}</td><td className="px-3 py-2">{r.customer_name||"—"}</td><td className="px-3 py-2">{r.vehicle_no||"—"}</td><td className="px-3 py-2">{r.driver_name||"—"}</td><td className="px-3 py-2">{[r.from_location,r.to_location].filter(Boolean).join(" → ")||"—"}</td><td className="px-3 py-2">{r.status.replaceAll("_"," ")}</td><td className="px-3 py-2">{r.ppr_status.replaceAll("_"," ")}</td><td className="px-3 py-2 text-right">{money(r.customer_rate)}</td><td className="px-3 py-2 text-right">{money(r.total_cost)}</td><td className="px-3 py-2 text-right font-bold">{money(r.trip_profit)}</td></tr>)}</tbody></table></div></section></>}</div>;
}