import NaviloSearchableSelect from "@/components/SearchableSelect";
import {useEffect,useMemo,useRef,useState} from 'react';
import * as XLSX from 'xlsx';
import NaviloDateInput from '@/components/NaviloDateInput';
import {formatNaviloDate} from '@/lib/naviloDate';
import {useAuth} from '@/auth/AuthContext';
import {supabase} from '@/lib/supabase';
import {fetchAllPages} from '@/lib/fetchAllPages';
import {fileDigest,runImportJob,storedImport,saveImport,removeStoredImport,type ImportJob,type ImportRow} from './transportTripImport';
import {HISTORY_COLUMNS,PAYMENT_COLUMNS,parseHistoricalFile,historicalTotals,type HistoricalRow} from './transportHistoricalImport';
import {financialNumber} from './transportFinancialTypes';
type Job=ImportJob&{settings:{cutoff:string;cost_account:string;opening_reviewed:boolean;batch_size?:number};expected:ReturnType<typeof historicalTotals>};
type Status={id:string;file:string;source_hash:string;settings:Job['settings'];completed:number;batches:number;totals:ReturnType<typeof historicalTotals>};
export default function TransportHistoricalImport({validateMasters,onChanged}:{validateMasters:(rows:ImportRow[])=>Promise<ImportRow[]>;onChanged:()=>Promise<void>}){
 const {user,activeCompany,activeBusinessUnit}=useAuth();const scope=`${user?.id}/${activeCompany?.company_id}/${activeBusinessUnit?.business_unit_id}/history`;
 const [rows,setRows]=useState<HistoricalRow[]>([]);const [file,setFile]=useState('');const [hash,setHash]=useState('');
 const [cutoff,setCutoff]=useState('');const [account,setAccount]=useState('');const [reviewed,setReviewed]=useState(false);
 const [accounts,setAccounts]=useState<{id:string;code:string;name:string;type:string;detail_type:string}[]>([]);
 const [job,setJob]=useState<Job|null>(null);const [status,setStatus]=useState<Status|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [page,setPage]=useState(0);const [initialized,setInitialized]=useState(false);const stop=useRef(false);const submitting=useRef(false);const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;stop.current=false;let live=true;
  void Promise.all([storedImport(scope),fetchAllPages<{id:string;code:string;name:string;type:string;detail_type:string}>((from,to)=>supabase.from('chart_of_accounts').select('id,code,name,type,detail_type').eq('company_id',activeCompany?.company_id).eq('is_active',true).eq('is_group',false).order('id').range(from,to)),supabase.rpc('transport_history_import_status')])
  .then(([saved,coa,s])=>{if(!live)return;setJob(saved as Job|null);setAccounts(coa);if(s.error)throw s.error;setStatus(s.data);const settings=(saved as Job|null)?.settings??s.data?.settings;if(settings){setAccount(settings.cost_account);setCutoff(settings.cutoff);setReviewed(settings.opening_reviewed);}setInitialized(true);})
  .catch(e=>{if(live)setError(e.message)});
  return()=>{live=false;mounted.current=false;stop.current=true;};
 },[scope,activeCompany?.company_id]);
 async function template(){const w=XLSX.utils.book_new();const headers=['DATE','TRUCK TYPE','PO/DO/JOB NO.','INVOICED','COMPANY NAME','DRIVER NAME','OWNER','PLATE #','FROM','TO','PAPER RECEIVED BY','Customer Rate','Supplier Rent','Sale Type (Cash / Credit)','Driver Pay',...HISTORY_COLUMNS];
  XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([headers,['2026-10-01','FLATBED','JOB-1','Yes','Example Customer','Example Driver','Example Supplier','ABC-123','From','To','PPR PENDING',2000,1700,'Credit',0,'OLD-0001','Yes','2026-10-01','No',2000,600,1400,'Yes','2026-10-01','No',1700,1000,700]]),'Trips');
  XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([[...PAYMENT_COLUMNS],['OLD-0001','customer','2026-10-02',600,'YOUR-CASH-CODE','RCPT-1'],['OLD-0001','supplier','2026-10-02',1000,'YOUR-BANK-CODE','PAY-1']]),'Payments');
  const notes=[['Historical Transport import'],['One Source Record ID per real trip. Same-date repeat journeys need distinct IDs.'],['Yes/No posted and VAT flags are independent for customer and supplier. Rates/rent exclude VAT. Gross and remaining include VAT.'],['Payments: one allocation per dated partial payment. Use the existing Chart of Accounts cash/bank code. Repeat a shared voucher reference for separate trip allocations.'],['This creates canonical service invoices, customer receipts and supplier payments. Each trip has its own NAVILO invoice; original invoice reference remains informational.'],['Add explicit historical columns and Payments sheet to an existing BuKu file. PAY TO DRIVER must equal Supplier Paid only when it actually represents supplier rent. Employee payroll and commissions require separately reconciled canonical entries.'],['Opening balances must exclude these imported invoices and payments. Reconcile starting cash/bank balances before confirmation. Closed accounting periods and dated ownership must be resolved through existing controls.'],['One historical dataset per business unit. After posting starts, resume the original file/settings. Completed imports cannot be repeated.']];
  XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet(notes),'Instructions');for(const n of w.SheetNames)w.Sheets[n]['!cols']=(n==='Instructions'?[{wch:130}]:Array.from({length:n==='Trips'?headers.length:PAYMENT_COLUMNS.length},()=>({wch:22})));
  XLSX.writeFile(w,'Transport-Historical-Import-Template.xlsx');
 }
 async function parse(f:File){if(submitting.current||!initialized)return;submitting.current=true;setBusy(true);setError('');setRows([]);
  try{if(f.size>30*1024*1024)throw new Error('Maximum file size 30 MB');const buffer=await f.arrayBuffer();const digest=await fileDigest(buffer);if(status&&digest!==status.source_hash)throw new Error('Restore the original registered historical file. A different dataset cannot be imported.');const history=await parseHistoricalFile(buffer);
   const mapped=await validateMasters(history.map(r=>({...r,supplier_rent:Number(r.supplier_rent)===0?'':r.supplier_rent})));
   const accountIndex=new Map(accounts.filter(a=>['Cash on Hand','Bank Account'].includes(a.detail_type)).map(a=>[a.code,a]));
   const checked=history.map((r,i)=>{const errors=[...r.errors,...mapped[i].errors];const payments=r.payments.map(p=>{const a=accountIndex.get(p.account_code);if(!a)errors.push(`Cash/bank account code ${p.account_code} is missing or inactive`);return {...p,account_id:a?.id,method:a?.detail_type==='Bank Account'?'bank':'cash'};});
    if(r.customer_posted&&!(Number(r.customer_rate)>0))errors.push('Posted customer requires positive Customer Rate');if(r.supplier_posted&&!(Number(r.supplier_rent)>0))errors.push('Posted supplier requires positive Supplier Rent');
    return {...r,payload:mapped[i].payload,payments,errors};});
   if(mounted.current){setRows(checked);setFile(f.name);setHash(digest);setPage(0);}
  }catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Unable to validate history');}finally{submitting.current=false;if(mounted.current)setBusy(false);}
 }
 async function execute(current:Job){if(submitting.current)return;submitting.current=true;stop.current=false;setBusy(true);setError('');
  try{const prepared=await supabase.rpc('transport_prepare_history_import',{p_source_hash:current.sourceHash,p_file_name:current.fileName,p_manifest:current.batches.map(b=>b.rows.map(r=>r.source_id)),p_settings:current.settings});if(prepared.error)throw prepared.error;
   current.serverId=prepared.data.id;current.completed=prepared.data.completed;await runImportJob(current,async batch=>{if(stop.current)throw new Error('Import paused');const r=await supabase.rpc('transport_import_history_batch',{p_job_id:current.serverId,p_batch:current.completed,p_rows:batch.rows});if(r.error)throw r.error;return r.data;},saveImport,j=>{if(mounted.current)setJob({...j} as Job)},()=>stop.current);
   if(mounted.current){setJob({...current});const s=await supabase.rpc('transport_history_import_status');if(s.error)throw s.error;setStatus(s.data);
    if(current.completed===current.batches.length){for(const k of Object.keys(current.expected) as Array<keyof Job['expected']>)if(Math.round(Number(s.data.totals[k])*100)!==Math.round(current.expected[k]*100))throw new Error(`Imported ${k} does not match reviewed workbook total`);await onChanged();}
   }
  }catch(e){if(mounted.current)setError(`${e&&typeof e==='object'&&'message' in e?String(e.message):'Import stopped'}. Completed batches are retained. Resume the unchanged saved job.`);}finally{submitting.current=false;if(mounted.current)setBusy(false);}
 }
 async function start(){if(!rows.length||rows.some(r=>r.errors.length)||!cutoff||!account||!reviewed)return;
  if(rows.some(r=>r.trip_date>cutoff||(r.customer_posted&&r.customer_date>cutoff)||(r.supplier_posted&&r.supplier_date>cutoff)||r.payments.some(p=>p.date>cutoff))){setError('Trip, invoice and payment dates must be on or before cutoff');return;}
  const batchSize=status?status.settings.batch_size??25:5;
  if(!Number.isInteger(batchSize)||batchSize<1||batchSize>25){setError('Saved import batch settings are invalid');return;}
  const batches:Job['batches']=[];for(let i=0;i<rows.length;i+=batchSize){const chunk=rows.slice(i,i+batchSize);batches.push({requestId:crypto.randomUUID(),rowNos:chunk.map(r=>r.rowNo),rows:chunk.map(r=>({source_id:r.source_id,trip:r.payload,customer_posted:r.customer_posted,supplier_posted:r.supplier_posted,customer_date:r.customer_date,supplier_date:r.supplier_date,customer_vat:r.customer_vat,supplier_vat:r.supplier_vat,customer_gross:r.customer_gross,supplier_gross:r.supplier_gross,received:r.received,paid:r.paid,customer_remaining:r.customer_remaining,supplier_remaining:r.supplier_remaining,payments:r.payments}))});}
  const current:Job={id:crypto.randomUUID(),scope,fileName:file,sourceHash:hash,batches,completed:0,total:rows.length,settings:status?.settings??{cutoff,cost_account:account,opening_reviewed:reviewed,batch_size:batchSize},expected:historicalTotals(rows)};
  if(!window.confirm(`Post ${current.total.toLocaleString()} historical trips and their reviewed invoices, receipts and supplier payments? This changes canonical accounting. Opening balances must exclude these transactions.`))return;
  setJob(current);await execute(current);
 }
 function rejected(){const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(rows.filter(r=>r.errors.length).map(r=>({'Source Record ID':r.source_id,'Excel Row':r.rowNo,Errors:r.errors.join('; ')}))),'Errors');XLSX.writeFile(w,'Transport-Historical-Import-Errors.xlsx');}
 async function clearUnposted(){if(submitting.current||!window.confirm('Clear this unposted import review? This is allowed only before any historical Trip or accounting has been saved.'))return;submitting.current=true;setBusy(true);setError('');try{const id=job?.serverId??status?.id;if(id){const r=await supabase.rpc('transport_cancel_empty_history_import',{p_job_id:id});if(r.error)throw r.error;}await removeStoredImport(scope);if(mounted.current){setJob(null);setStatus(null);setRows([]);setFile('');setHash('');setReviewed(false);}}catch(e){if(mounted.current)setError(e&&typeof e==='object'&&'message' in e?String(e.message):'Unable to clear unposted review');}finally{submitting.current=false;if(mounted.current)setBusy(false);}}
 const rowTotals=useMemo(()=>rows.length?historicalTotals(rows):null,[rows]);const totals=rowTotals??job?.expected;const locked=!initialized||busy||Boolean(job)||Boolean(status);const fileLocked=!initialized||busy||Boolean(job)||Boolean(status&&status.completed===status.batches);const view=rows.slice(page*100,(page+1)*100);
 return <section className="space-y-2 p-3 text-xs"><h2 className="font-semibold">One-time Historical Import — up to 20,000 Trips</h2><p>Creates canonical service invoices and dated receipts/supplier payments in company base currency. Daily bulk upload remains operational only. Stable source IDs distinguish genuine repeat journeys on the same date. All rows must pass review.</p>
 {error&&<p role="alert" className="text-red-700">{error}</p>}
 {!initialized&&!error&&<p role="status">Loading historical import workspace…</p>}
 <div className="flex flex-wrap items-center gap-2"><button className="btn" data-navilo-keep-local-action="true" onClick={()=>void template()}>Download historical template</button><label className="btn">{status&&!job?'Restore original historical Excel':'Historical Excel'}<input className="hidden" type="file" accept=".xlsx,.xlsm,.xls" disabled={fileLocked} onChange={e=>{const f=e.target.files?.[0];if(f)void parse(f);e.target.value='';}}/></label><span>{file||job?.fileName||status?.file}</span><label>Cutoff<NaviloDateInput className="input" type="date" disabled={locked} value={cutoff} onChange={e=>setCutoff(e.target.value)}/></label><label>Rent expense account<NaviloSearchableSelect nativeCompatibility preserveLabel className="input" value={account} disabled={locked} onChange={e=>setAccount(e.target.value)}><option value="">Select account</option>{accounts.filter(a=>a.type==='expense').map(a=><option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</NaviloSearchableSelect></label></div>
 <label className="block"><input type="checkbox" checked={reviewed} disabled={locked} onChange={e=>setReviewed(e.target.checked)}/> I reconciled opening balances. These bills/receipts/payments are not already included in NAVILO or its opening balances.</label>
 {totals&&<div className="flex flex-wrap gap-x-4 gap-y-1">{Object.entries(totals).map(([k,v])=><span key={k}>{k.replaceAll('_',' ')}: <strong>{financialNumber(v)}</strong></span>)}</div>}
 {status&&<p role="status">Server confirmed {status.totals.trips.toLocaleString()} trips · {status.completed} / {status.batches} batches. {status.completed===status.batches?'One-time import complete.':''}</p>}
 {(job?.completed===0||(!job&&status?.completed===0))&&<button className="btn" disabled={busy} onClick={()=>void clearUnposted()}>Clear unposted import review</button>}
 {job&&<div role="status">Saved job: {job.batches.slice(0,job.completed).reduce((count,batch)=>count+batch.rows.length,0).toLocaleString()} / {job.total.toLocaleString()} trips confirmed. {busy?<button className="btn ml-2" onClick={()=>{stop.current=true}}>Pause after batch</button>:job.completed<job.batches.length?<button className="btn-primary ml-2" onClick={()=>void execute(job)}>Resume historical import</button>:<strong>All batches confirmed</strong>}<p>Original request IDs are reused after interruption; completed batches are not posted twice. If saved browser data is lost, restore the original file to resume from server progress.</p></div>}
 {!job&&(!status||status.completed<status.batches)&&<button className="btn-primary" disabled={busy||!rows.length||rows.some(r=>r.errors.length)||!cutoff||!account||!reviewed} onClick={()=>void start()}>{busy?'Validating…':status?'Resume from original file':'Confirm and import historical accounting'}</button>}
 {rows.some(r=>r.errors.length)&&<button className="btn" data-navilo-keep-local-action="true" onClick={rejected}>Download validation errors</button>}
 {rows.length>0&&<><div className="flex items-center gap-2"><button className="btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {Math.ceil(rows.length/100)}</span><button className="btn" disabled={(page+1)*100>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</button></div><div className="max-h-96 overflow-auto"><table className="w-full text-left"><thead><tr><th>Source ID</th><th>Date</th><th>Customer</th><th>Received / Remaining</th><th>Supplier paid / Remaining</th><th>Validation</th></tr></thead><tbody>{view.map((r,i)=><tr className="border-t" key={`${r.rowNo}/${i}`}><td>{r.source_id}</td><td>{formatNaviloDate(r.trip_date)}</td><td>{r.customer}</td><td>{financialNumber(r.received)} / {financialNumber(r.customer_remaining)}</td><td>{financialNumber(r.paid)} / {financialNumber(r.supplier_remaining)}</td><td className={r.errors.length?'text-red-700':'text-emerald-700'}>{r.errors.join('; ')||'Ready'}</td></tr>)}</tbody></table></div></>}
 </section>;
}
