// @vitest-environment jsdom
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import TransportHistoricalImport from './TransportHistoricalImport';
import * as XLSX from 'xlsx';
import {parseHistoricalWorkbook} from './transportHistoricalImport';
const mock=vi.hoisted(()=>({rpc:vi.fn(),saved:vi.fn(),parse:vi.fn(),stored:vi.fn(),download:vi.fn(),status:null as any}));
vi.mock('xlsx',async original=>({...await original<any>(),writeFile:mock.download}));
vi.mock('@/auth/AuthContext',()=>({useAuth:()=>({user:{id:'user'},activeCompany:{company_id:'company'},activeBusinessUnit:{business_unit_id:'unit'}})}));
vi.mock('@/lib/supabase',()=>({supabase:{rpc:mock.rpc,from:()=>({select:()=>({eq:()=>({eq:()=>({eq:()=>({order:()=>({range:()=>({data:[],error:null})})})})})})})}}));
vi.mock('@/lib/fetchAllPages',()=>({fetchAllPages:async()=>[{id:'cost',code:'EXP',name:'Transport cost',type:'expense',detail_type:'Transport & Freight'},{id:'cash',code:'CASH',name:'Cash',type:'asset',detail_type:'Cash on Hand'}]}));
vi.mock('./transportTripImport',async original=>({...await original<any>(),fileDigest:async()=> 'a'.repeat(64),storedImport:mock.stored,saveImport:mock.saved}));
vi.mock('./transportHistoricalImport',async original=>({...await original<any>(),parseHistoricalFile:mock.parse}));
const history={rowNo:2,trip_date:'2026-10-01',customer:'Customer',truck_type:'',vehicle:'',driver:'',owner_supplier:'',po_do_job_no:'JOB',from_location:'A',to_location:'B',ppr_status:'pending',customer_rate:'2000',supplier_rent:'',driver_pay:'',sale_type:'credit',source_invoice_no:'',notes:'',ppr_employee:'',ppr_date:'',source_id:'OLD-1',customer_posted:true,supplier_posted:false,customer_date:'2026-10-01',supplier_date:'',customer_vat:false,supplier_vat:false,customer_gross:2000,supplier_gross:0,received:600,paid:0,customer_remaining:1400,supplier_remaining:0,payments:[{side:'customer',date:'2026-10-02',amount:600,account_code:'CASH',reference:'R-1'}],errors:[]};
const totals={trips:1,customer_gross:2000,supplier_gross:0,received:600,paid:0,customer_remaining:1400,supplier_remaining:0};
beforeEach(()=>{cleanup();mock.rpc.mockReset();mock.saved.mockReset();mock.stored.mockReset();mock.parse.mockReset();mock.stored.mockResolvedValue(null);mock.saved.mockResolvedValue(undefined);mock.parse.mockResolvedValue([{...history}]);mock.status=null;mock.rpc.mockImplementation(async(name:string)=>({data:name==='transport_prepare_history_import'?{id:'server-job',completed:0}:name==='transport_import_history_batch'?[{id:'trip',trip_no:'TR-1'}]:mock.status,error:null}));vi.spyOn(window,'confirm').mockReturnValue(true);});
const masters=async(rows:any[])=>rows.map(r=>({...r,payload:{trip_date:r.trip_date,customer_id:'customer',from_location_id:'a',to_location_id:'b',sale_type:r.sale_type,customer_rate:2000},errors:[]}));
async function upload(container:HTMLElement){await waitFor(()=>expect((container.querySelector('input[type=file]') as HTMLInputElement).disabled).toBe(false));const f=new File(['xlsx'],'history.xlsx');Object.defineProperty(f,'arrayBuffer',{value:async()=>new ArrayBuffer(1)});fireEvent.change(container.querySelector('input[type=file]')!,{target:{files:[f]}});await screen.findByText('OLD-1');}
describe('Historical import review boundary',()=>{
 it('downloads a workbook whose Trips and dated partial Payments pass the actual historical parser',async()=>{mock.download.mockClear();render(<TransportHistoricalImport validateMasters={masters} onChanged={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Download historical template'}));expect(mock.download).toHaveBeenCalledOnce();const [book,name]=mock.download.mock.calls[0];expect(name).toBe('Transport-Historical-Import-Template.xlsx');expect(book.SheetNames).toEqual(['Trips','Payments','Instructions']);const parsed=parseHistoricalWorkbook(XLSX.write(book,{type:'array',bookType:'xlsx'}));expect(parsed).toHaveLength(1);expect(parsed[0].errors).toEqual([]);expect(parsed[0]).toMatchObject({source_id:'OLD-0001',received:600,paid:1000,customer_remaining:1400,supplier_remaining:700});});
 it('posts through the separate canonical history endpoint only after review, then reconciles server totals',async()=>{const changed=vi.fn(async()=>{});const {container}=render(<TransportHistoricalImport validateMasters={masters} onChanged={changed}/>);await upload(container);expect(mock.rpc.mock.calls.some(c=>c[0]==='transport_import_history_batch')).toBe(false);
  fireEvent.change(screen.getByPlaceholderText('dd-mmm-yy'),{target:{value:'03-Oct-26'}});fireEvent.change(screen.getByRole('combobox'),{target:{value:'cost'}});fireEvent.click(screen.getByRole('checkbox'));mock.status={file:'history.xlsx',completed:1,batches:1,totals,settings:{cutoff:'2026-10-03',cost_account:'cost',opening_reviewed:true},source_hash:'a'.repeat(64)};
  fireEvent.click(screen.getByRole('button',{name:'Confirm and import historical accounting'}));await waitFor(()=>expect(changed).toHaveBeenCalledOnce());expect(mock.rpc).toHaveBeenCalledWith('transport_import_history_batch',expect.objectContaining({p_job_id:'server-job',p_batch:0,p_rows:[expect.objectContaining({source_id:'OLD-1',received:600,customer_remaining:1400,payments:[expect.objectContaining({account_id:'cash',method:'cash',amount:600})]})]}));expect(mock.saved).toHaveBeenCalled();});
 it('retains source accounting validation errors even when master matching succeeds',async()=>{mock.parse.mockResolvedValue([{...history,errors:['Payment totals do not reconcile']}]);const {container}=render(<TransportHistoricalImport validateMasters={masters} onChanged={async()=>{}}/>);await upload(container);expect(screen.getByText('Payment totals do not reconcile')).toBeTruthy();expect((screen.getByRole('button',{name:'Confirm and import historical accounting'}) as HTMLButtonElement).disabled).toBe(true);});
 it('restores the original file/settings when browser job data is absent but server progress exists',async()=>{mock.status={file:'history.xlsx',completed:0,batches:1,totals:{...totals,trips:0},settings:{cutoff:'2026-10-03',cost_account:'cost',opening_reviewed:true},source_hash:'a'.repeat(64)};const {container}=render(<TransportHistoricalImport validateMasters={masters} onChanged={async()=>{}}/>);await screen.findByText('Restore original historical Excel');await upload(container);expect((screen.getByRole('button',{name:'Resume from original file'}) as HTMLButtonElement).disabled).toBe(false);expect((screen.getByRole('combobox') as HTMLSelectElement).disabled).toBe(true);});
});
