// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import TransportQuickAdd from './TransportQuickAdd';
const mock=vi.hoisted(()=>({rpc:vi.fn(),insert:vi.fn(),update:vi.fn()}));
vi.mock('@/auth/AuthContext',()=>({useAuth:()=>({activeCompany:{company_id:'c',enabled_modules:['transport'],membership_role:'company_owner'},activeBusinessUnit:{business_unit_id:'b',business_unit_type:'transport',enabled_modules:['transport'],membership_role:'company_owner'},isPlatformOwner:false})}));
vi.mock('@/components/DataTable',()=>({default:()=>null}));
vi.mock('@/components/MasterSummaryStrip',()=>({default:()=>null}));
vi.mock('@/components/MasterActionButton',()=>({default:()=>null}));
vi.mock('@/modules/master-data/useTransportMasterClient',()=>({default:()=>client}));
const client:any={rpc:mock.rpc,from:(table:string)=>{const data=table==='suppliers'?[{id:'s',name:'Owner',is_active:true}]:table==='transport_truck_types'?[{id:'tt',name:'Flatbed',is_active:true}]:[];const q:any={select:()=>q,order:()=>q,eq:()=>q,range:()=>Promise.resolve({data,error:null}),single:()=>Promise.resolve({data:{id:'new'},error:null}),insert:(p:any)=>{mock.insert(table,p);return q},update:(p:any)=>{mock.update(table,p);return q},then:(resolve:any,reject:any)=>Promise.resolve({data,error:null}).then(resolve,reject)};return q}};
beforeEach(()=>{mock.rpc.mockReset();mock.rpc.mockResolvedValue({data:{party_id:'new'},error:null});mock.insert.mockReset();mock.update.mockReset()});afterEach(cleanup);
function view(kind:any,onCreated=vi.fn(async()=>{})){const onClose=vi.fn();const result=render(<MemoryRouter><TransportQuickAdd kind={kind} truckTypeId="tt" supplierId="" truckTypes={[]} suppliers={[]} onCreated={onCreated} onClose={onClose}/></MemoryRouter>);return {...result,onCreated,onClose,submit:()=>fireEvent.submit(result.container.querySelector('form')!)};}
describe('Canonical quick master editors',()=>{
 for(const kind of ['customer','supplier'])it(`${kind} preserves tax identity and opening balance fields and saves through the master RPC`,async()=>{const events=view(kind);for(const label of ['English Name','Phone','Address','Tax Status','Amount','Balance Side','Opening Date'])expect(screen.getByLabelText(label)).toBeTruthy();fireEvent.change(screen.getByLabelText('English Name'),{target:{value:'Party'}});fireEvent.change(screen.getByLabelText('Amount'),{target:{value:'125'}});fireEvent.change(screen.getByLabelText('Opening Date'),{target:{value:'02-Oct-26'}});events.submit();await waitFor(()=>expect(events.onCreated).toHaveBeenCalledWith({id:'new',name:'Party'}));expect(mock.rpc).toHaveBeenCalledWith('create_party_with_opening_balance_v2',expect.objectContaining({p_opening_amount:125,p_opening_date:'2026-10-02'}));expect(events.onClose).toHaveBeenCalled()});
 it('validates registered tax identity before posting',async()=>{const events=view('customer');fireEvent.change(screen.getByLabelText('English Name'),{target:{value:'Party'}});fireEvent.click(screen.getByLabelText('Tax Status'));fireEvent.click(screen.getByRole('option',{name:'Registered'}));expect(screen.getByLabelText('NTN')).toBeTruthy();expect(screen.getByLabelText('STRN')).toBeTruthy();events.submit();await screen.findByRole('alert');expect(mock.rpc).not.toHaveBeenCalled()});
 it('retains Driver identity and conditional supplier fields',async()=>{view('driver');fireEvent.change(screen.getByLabelText('Driver Type'),{target:{value:'supplier'}});await screen.findByRole('option',{name:'Owner'});expect(screen.getByLabelText('Supplier *').hasAttribute('required')).toBe(true);for(const label of ['Driver Code','ID / CNIC / Iqama','Driving Licence No','Licence Expiry'])expect(screen.getByLabelText(label)).toBeTruthy()});
 it('creates a supplier vehicle with dated ownership through the canonical atomic RPC',async()=>{mock.rpc.mockResolvedValue({data:'new',error:null});const events=view('vehicle');await screen.findByRole('option',{name:'Flatbed'});fireEvent.change(screen.getByLabelText('Vehicle No / Plate No *'),{target:{value:'ABC'}});fireEvent.change(screen.getByLabelText('Ownership Type'),{target:{value:'supplier'}});fireEvent.change(screen.getByLabelText('Supplier *'),{target:{value:'s'}});fireEvent.change(screen.getByLabelText('Ownership Effective From *'),{target:{value:'02-Oct-26'}});events.submit();await waitFor(()=>expect(events.onCreated).toHaveBeenCalledWith(expect.objectContaining({id:'new'})));expect(mock.rpc).toHaveBeenCalledWith('transport_create_vehicle_master',expect.objectContaining({p_supplier_id:'s',p_owner_type:'supplier',p_truck_type_id:'tt',p_effective_from:'2026-10-02'}));expect(mock.insert).not.toHaveBeenCalled()});
 for(const kind of ['locationFrom','locationTo','truckType'])it(`${kind} uses scoped foundation master fields`,async()=>{const events=view(kind);fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Master'}});if(kind!=='truckType')fireEvent.change(screen.getByLabelText('City / Area'),{target:{value:'Karachi'}});events.submit();await waitFor(()=>expect(events.onCreated).toHaveBeenCalledWith({id:'new',name:'Master'}));expect(mock.insert).toHaveBeenCalledWith(kind==='truckType'?'transport_truck_types':'transport_locations',expect.objectContaining({company_id:'c',business_unit_id:'b',...(kind==='truckType'?{}:{city_area:'Karachi'})}))});
 it('keeps failed saves open and prevents concurrent duplicate posting',async()=>{let finish:any;mock.rpc.mockReturnValue(new Promise(resolve=>{finish=resolve}));const events=view('supplier');fireEvent.change(screen.getByLabelText('English Name'),{target:{value:'Party'}});events.submit();events.submit();expect(mock.rpc).toHaveBeenCalledTimes(1);finish({data:null,error:{message:'Permission denied'}});expect((await screen.findByRole('alert')).textContent).toContain('Permission denied');expect(events.onClose).not.toHaveBeenCalled()});
 it('retries selection after a refresh failure without recreating the party',async()=>{const onCreated=vi.fn().mockRejectedValueOnce(new Error('Refresh failed')).mockResolvedValue(undefined);const events=view('customer',onCreated);fireEvent.change(screen.getByLabelText('English Name'),{target:{value:'Party'}});events.submit();await screen.findByRole('alert');events.submit();await waitFor(()=>expect(events.onClose).toHaveBeenCalled());expect(mock.rpc).toHaveBeenCalledTimes(1);expect(onCreated).toHaveBeenCalledTimes(2)});
});
