import NaviloDateInput from '@/components/NaviloDateInput';
import {useCallback, useEffect, useRef, useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/auth/AuthContext';
import {fetchAllPages} from '@/lib/fetchAllPages';
import {financeActions, financialNumber, type FinancialTrip, type ServiceBalance, type TransportFinanceAction} from './transportFinancialTypes';

type Rent={id:string;supplier_id:string;amount:number;reason:string};
type Option={id:string;name:string};
type Adjustment={id:string;side:string;old_value:number;new_value:number;difference:number;reason:string;reference:string|null;created_by:string;created_at:string;accounting_evidence:Array<{document_id?:string;note_id?:string;journal_entry_id?:string}>};
export default function TransportFinancialPanel({trip,onClose,onChanged}:{trip:FinancialTrip;onClose:()=>void;onChanged:()=>Promise<void>}) {
 const {activeCompany,activeBusinessUnit}=useAuth();
 const company=activeCompany?.company_id;const unit=activeBusinessUnit?.business_unit_id;
 const [mode,setMode]=useState<'customer'|'supplier'|'expense'|'driver'|'correction'|'details'>('customer');
 const [postedRents,setPostedRents]=useState<Set<string>>(new Set());
 const settlementRequest=useRef<{body:string;id:string}|null>(null);
 const [current,setCurrent]=useState(trip);const [balances,setBalances]=useState<ServiceBalance[]>([]);
 const [rents,setRents]=useState<Rent[]>([]);const [suppliers,setSuppliers]=useState<Option[]>([]);
 const [accounts,setAccounts]=useState<Array<Option & {type:string;detail_type:string}>>([]);
 const [adjustments,setAdjustments]=useState<Adjustment[]>([]);const [allowed,setAllowed]=useState<Partial<Record<TransportFinanceAction,boolean>>>({});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [withTax,setWithTax]=useState(false);
 const [supplier,setSupplier]=useState('');const [amount,setAmount]=useState('');const [costAccount,setCostAccount]=useState('');const [cashAccount,setCashAccount]=useState('');
 const [reason,setReason]=useState('');const [reference,setReference]=useState('');const [side,setSide]=useState<'customer'|'supplier'>('customer');
 const [rentId,setRentId]=useState('');const [revised,setRevised]=useState('');const [costKind,setCostKind]=useState('commission');
 const [allocationAmounts,setAllocationAmounts]=useState<Record<string,string>>({});const [fifo,setFifo]=useState('');const [party,setParty]=useState('');
 const [agreedPay,setAgreedPay]=useState('');
 const [settlements,setSettlements]=useState<Array<{id:string;entry_no:string;entry_date:string;trans_type:string;payment_amount:number;payment_mode:string;cash_account_id:string|null}>>([]);
 const [correctSettlement,setCorrectSettlement]=useState<{id:string;entry_no:string;trans_type:string;payment_amount:number;payment_mode:string;cash_account_id:string|null}|null>(null);const [correctAmount,setCorrectAmount]=useState('');
 const [payrollKind,setPayrollKind]=useState<'accrual'|'payment'>('accrual');const [payrollSource,setPayrollSource]=useState('');
 const [payroll,setPayroll]=useState<Array<{id:string;kind:'accrual'|'payment';label:string}>>([]);
 const dialog=useRef<HTMLElement>(null);const generation=useRef(0);const closeButton=useRef<HTMLButtonElement>(null);
 const load=useCallback(async()=>{
  if(!company||!unit)return;const request=++generation.current;
  const [summary,rentRows,customerLinks,supplierLinks,costLinks,accountRows,supplierRows,history,permissions,driverResult]=await Promise.all([
   supabase.from('transport_financial_register').select('*').eq('id',trip.id).single(),
   supabase.from('transport_trip_supplier_rents').select('id,supplier_id,amount,reason').eq('trip_id',trip.id),
   supabase.from('transport_customer_document_trips').select('document_id').eq('trip_id',trip.id),
   supabase.from('transport_supplier_document_rents').select('document_id,rent_id').eq('trip_id',trip.id),
   supabase.from('transport_service_cost_links').select('purchase_order_id').eq('trip_id',trip.id),
   supabase.from('chart_of_accounts').select('id,name,type,detail_type').eq('company_id',company).eq('is_active',true).eq('is_group',false),
   supabase.from('suppliers').select('id,name').eq('company_id',company).eq('is_active',true),
   supabase.from('transport_rate_adjustments').select('*').eq('trip_id',trip.id).order('created_at',{ascending:false}),
   Promise.all(financeActions.map(async action=>{const result=await supabase.rpc('transport_finance_allowed',{p_action:action});if(result.error)throw result.error;return [action,result.data===true] as const})),
   trip.driver_id?supabase.from('transport_drivers').select('employee_id').eq('id',trip.driver_id).single():Promise.resolve({data:null,error:null})
  ]);
  for(const result of [summary,rentRows,customerLinks,supplierLinks,costLinks,accountRows,supplierRows,history,driverResult])if(result.error)throw result.error;
  const [customerDocs,supplierDocs]=await Promise.all([
   customerLinks.data?.length?supabase.from('transport_customer_documents').select('sales_order_id').in('id',customerLinks.data.map(r=>r.document_id)):Promise.resolve({data:[],error:null}),
   supplierLinks.data?.length?supabase.from('transport_supplier_documents').select('purchase_order_id').in('id',supplierLinks.data.map(r=>r.document_id)):Promise.resolve({data:[],error:null})
  ]);
  if(customerDocs.error)throw customerDocs.error;if(supplierDocs.error)throw supplierDocs.error;
  const ids=[...(customerDocs.data??[]).map(r=>r.sales_order_id),...(supplierDocs.data??[]).map(r=>r.purchase_order_id),...(costLinks.data??[]).map(r=>r.purchase_order_id)];
  const docs=ids.length?await supabase.from('transport_service_document_balances').select('*').in('order_id',ids):{data:[],error:null};if(docs.error)throw docs.error;
  let sources:Array<{id:string;kind:'accrual'|'payment';label:string}>=[];
  const employee=driverResult.data?.employee_id;
  if(employee){
   const [accruals,payments]=await Promise.all([
    fetchAllPages<any>((from,to)=>supabase.from('employee_salary_accruals').select('id,voucher_no,monthly_salary').eq('company_id',company).eq('business_unit_id',unit).eq('employee_id',employee).order('id').range(from,to)),
    fetchAllPages<any>((from,to)=>supabase.from('employee_salary_payments').select('id,voucher_no,amount').eq('company_id',company).eq('business_unit_id',unit).eq('employee_id',employee).order('id').range(from,to))
   ]);
   sources=[...accruals.map(r=>({id:r.id,kind:'accrual' as const,label:`${r.voucher_no} / ${financialNumber(r.monthly_salary)}`})),...payments.map(r=>({id:r.id,kind:'payment' as const,label:`${r.voucher_no} / ${financialNumber(r.amount)}`}))];
  }
  if(request!==generation.current)return;
  setCurrent(summary.data);setBalances(docs.data??[]);setRents(rentRows.data??[]);setAccounts(accountRows.data??[]);setSuppliers(supplierRows.data??[]);
  setPostedRents(new Set((supplierLinks.data??[]).map(r=>r.rent_id)));setAdjustments(history.data??[]);setAllowed(Object.fromEntries(permissions));setPayroll(sources);
  const orderIds=(docs.data??[]).map((d:any)=>d.order_id);
  if(orderIds.length){const [ca,pa]=await Promise.all([supabase.from('invoice_payment_allocations').select('journal_entry_id').in('sales_order_id',orderIds),supabase.from('purchase_payment_allocations').select('journal_entry_id').in('purchase_order_id',orderIds)]);const journalIds=[...new Set([...(ca.data??[]),...(pa.data??[])].map((x:any)=>x.journal_entry_id))];if(journalIds.length){const j=await supabase.from('journal_entries').select('id,entry_no,entry_date,trans_type,payment_amount,payment_mode,journal_lines(account_id,debit,credit)').in('id',journalIds).eq('status','posted').in('trans_type',['Customer Receipt','Supplier Payment']).order('entry_date',{ascending:false});if(j.error)throw j.error;setSettlements((j.data??[]).map((x:any)=>({...x,cash_account_id:(x.journal_lines??[]).find((l:any)=>x.trans_type==='Supplier Payment'?Number(l.credit)>0:Number(l.debit)>0)?.account_id??null})));}else setSettlements([])}else setSettlements([]);
 },[company,unit,trip.id,trip.driver_id]);
 useEffect(()=>{let live=true;void load().catch(e=>{if(live)setError(e.message)});closeButton.current?.focus();return()=>{live=false;generation.current++}},[load]);
 async function action(rpc:string,args:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{if(rpc==='transport_post_cost'){const key=`navilo:transport:cost:${company}:${unit}:${trip.id}`;const body=JSON.stringify(args);let intent;try{intent=JSON.parse(sessionStorage.getItem(key)||'null')}catch{}if(!intent||intent.body!==body){intent={body,id:crypto.randomUUID()};sessionStorage.setItem(key,JSON.stringify(intent));}rpc='transport_post_cost_request';args={...args,p_request_id:intent.id};}if(rpc==='transport_settle_documents'&&args.p_allocations){const body=JSON.stringify(args);if(settlementRequest.current?.body!==body)settlementRequest.current={body,id:crypto.randomUUID()};rpc='transport_settle_reviewed_documents';args={...args,p_request_id:settlementRequest.current.id};}const r=await supabase.rpc(rpc,args);if(r.error)throw r.error;await load();await onChanged();setMessage('Saved; balances updated.');if(rpc==='transport_post_cost_request')sessionStorage.removeItem(`navilo:transport:cost:${company}:${unit}:${trip.id}`);settlementRequest.current=null;setAllocationAmounts({});setFifo('');return true}catch(e){setError(e&&typeof e==='object'&&'message' in e?String(e.message):'Action failed');return false}finally{setBusy(false)}}
 const cash=accounts.filter(a=>['Cash on Hand','Bank Account'].includes(a.detail_type));const expenses=accounts.filter(a=>a.type==='expense');
 const method=cash.find(a=>a.id===cashAccount)?.detail_type==='Bank Account'?'bank':'cash';
 const selectedParty=side==='customer'?current.customer_id:party;
 const shown=balances.filter(b=>b.side===side&&(!selectedParty||b.party_id===selectedParty));
 const rent=rents.find(r=>r.id===rentId);const oldRate=side==='customer'?(current.billed_customer_net??current.customer_rate):rent?Number(rent.amount)+adjustments.filter(a=>a.side==='supplier'&&(a as Adjustment & {rent_id:string}).rent_id===rentId).reduce((s,a)=>s+Number(a.difference),0):null;
 const can=(a:TransportFinanceAction)=>allowed[a]===true&&!busy;
 return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/40 p-3" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const items=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]');if(items?.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}}>
 <section ref={dialog} role="dialog" aria-modal="true" aria-labelledby="trip-finance-title" className="max-h-[94vh] w-full max-w-5xl overflow-auto rounded-lg bg-white p-4 text-xs shadow-xl">
 <div className="flex items-center justify-between"><h2 id="trip-finance-title" className="font-bold">{trip.trip_no} · {current.financial_status} · Finance</h2><button ref={closeButton} className="btn" disabled={busy} onClick={onClose}>Close</button></div>
 {error&&<p role="alert" className="my-2 text-red-700">{error}</p>}{message&&<p role="status" className="my-2 text-emerald-700">{message}</p>}
 <div className="my-3 grid grid-cols-2 gap-2 rounded border bg-slate-50 p-2 sm:grid-cols-4">
 <div><strong>Customer</strong><p>Bill: {financialNumber(Number(current.customer_received_gross??0)+Number(current.customer_outstanding_gross??0)-Number(current.customer_credit_gross??0))}</p><p>Received: {financialNumber(current.customer_received_gross)}</p><p>Balance: {financialNumber(current.customer_outstanding_gross)}</p></div>
 <div><strong>Supplier</strong><p>Rent / bills: {financialNumber(Number(current.payment_amount??0)+Number(current.supplier_outstanding_gross??0)-Number(current.supplier_credit_gross??0))}</p><p>Paid: {financialNumber(current.payment_amount)}</p><p>Balance: {financialNumber(current.supplier_outstanding_gross)}</p></div>
 <div><strong>Driver</strong><p>Agreed pay: {financialNumber(current.driver_pay)}</p><p>Accrued: {financialNumber(current.driver_accrued)}</p><p>Paid: {financialNumber(current.driver_paid)}</p><p>Balance: {financialNumber(current.driver_outstanding)}</p></div>
 <div><strong>Posted Trip result · excluding VAT</strong><p>Revenue: {financialNumber(current.billed_customer_net)}</p><p>Other expenses: {financialNumber(current.other_cost_net)}</p><p>Total cost: {financialNumber(Number(current.billed_supplier_net??0)+Number(current.driver_accrued??0)+Number(current.other_cost_net??0))}</p><p>Profit / loss: {financialNumber(current.trip_profit)}</p></div>
 </div>
 <div className="my-2 flex flex-wrap gap-2">{([['customer','Customer'],['supplier','Supplier'],['driver','Driver Pay'],['expense','Add Expense'],['correction','Correct Rate'],['details','View Details']] as const).map(([key,label])=><button key={key} className={mode===key?'btn-primary':'btn'} aria-pressed={mode===key} onClick={()=>{setMode(key);if(key==='customer'||key==='supplier'){setSide(key);setAllocationAmounts({});setFifo('')}}}>{label}</button>)}</div>
 <div className="flex flex-wrap gap-3"><label>Date <NaviloDateInput className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Reference <input className="input" value={reference} onChange={e=>setReference(e.target.value)}/></label>{(mode==='customer'||mode==='supplier'||mode==='expense')&&<label className="self-center"><input type="checkbox" checked={withTax} onChange={e=>setWithTax(e.target.checked)}/> With VAT</label>}<label>Reason <input className="input" value={reason} onChange={e=>setReason(e.target.value)}/></label></div>
 {mode==='customer'&&!current.customer_rate_locked&&<div className="my-3 flex items-end gap-2">
 <button className="btn-primary" disabled={!can('billing')||current.customer_rate_state!=='finalized'} onClick={()=>void action('transport_post_customer_bill',{p_trip_id:trip.id,p_date:date,p_with_tax:withTax})}>Post Customer Bill</button>
 <p className="text-slate-500">Invoice only. Record actual full or partial receipts separately.</p>
 </div>}
 {mode==='details'&&<div className="my-3"><p>Customer credit / refund: {financialNumber(current.customer_credit_gross)} · Supplier credit / recovery: {financialNumber(current.supplier_credit_gross)}</p><button className="btn" disabled={!can('close')||!reason.trim()} onClick={()=>void action('transport_complete_operations',{p_trip_id:trip.id,p_reason:reason})}>Mark Job Complete</button></div>}
 {(mode==='supplier'||mode==='expense')&&<fieldset className="my-3 rounded border p-3"><legend className="font-semibold">{mode==='supplier'?'Supplier / Owner Rent':'Trip Expense'}</legend>
 <div className="flex flex-wrap items-end gap-2"><label>Supplier <select className="input" value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Amount excluding VAT <input className="input" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Expense account <select className="input" value={costAccount} onChange={e=>setCostAccount(e.target.value)}><option value="">Select account</option>{expenses.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
 {mode==='supplier'&&<button className="btn" disabled={!can('rent')||!supplier||!amount||!reason.trim()} onClick={()=>void action('transport_add_supplier_rent',{p_trip_id:trip.id,p_supplier_id:supplier,p_amount:Number(amount),p_reason:reason})}>Finalize Rent</button>}
 {mode==='expense'&&<><label>Cost type <select className="input" value={costKind} onChange={e=>setCostKind(e.target.value)}>{['commission','vehicle_expense','other','driver_expense'].map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></label><button className="btn" disabled={!can('cost')||!supplier||!amount||!costAccount} onClick={()=>void action('transport_post_cost',{p_trip_id:trip.id,p_kind:costKind,p_supplier_id:supplier,p_amount:Number(amount),p_date:date,p_cost_account_id:costAccount,p_with_tax:withTax,p_reference:reference})}>Post Expense</button></>}</div>
 {mode==='supplier'&&rents.map(r=>{const rentAdjustments=adjustments.filter(a=>a.side==='supplier'&&(a as Adjustment & {rent_id:string}).rent_id===r.id);const currentRent=Number(r.amount)+rentAdjustments.reduce((sum,a)=>sum+Number(a.difference),0);const posted=postedRents.has(r.id);return <div key={r.id} className="mt-2 rounded border border-slate-200 bg-slate-50 p-2">
   <div className="flex flex-wrap items-center gap-2"><strong>{suppliers.find(s=>s.id===r.supplier_id)?.name}</strong><span>Agreed: {financialNumber(r.amount)}</span>{currentRent!==Number(r.amount)&&<span>Current: {financialNumber(currentRent)}</span>}<span className={posted?'text-emerald-700':'text-amber-700'}>{posted?'Posted':'Not posted'}</span></div>
   <div className="mt-2 flex flex-wrap gap-2">
    {!posted&&<button className="btn-primary" disabled={!can('rent')||!costAccount} onClick={()=>void action('transport_post_supplier_bill',{p_rent_id:r.id,p_date:date,p_cost_account_id:costAccount,p_with_tax:withTax,p_reference:reference})}>Post Rent</button>}
    {posted&&<button className="btn" disabled={!can('adjustment')} onClick={()=>{setSide('supplier');setRentId(r.id);setRevised(String(currentRent));setReason('');setMode('correction')}}>Edit Rent</button>}
    {posted&&<button className="btn-primary" disabled={!can('settlement')} onClick={()=>{setSide('supplier');setParty(r.supplier_id);setAllocationAmounts({});setFifo('')}}>Pay Rent</button>}
   </div>
  </div>})}
 </fieldset>}
 {(mode==='customer'||mode==='supplier')&&settlements.filter(s=>side==='customer'?s.trans_type==='Customer Receipt':s.trans_type==='Supplier Payment').length>0&&<fieldset className="my-3 rounded border p-3"><legend className="font-semibold">Posted Payments / Receipts</legend><div className="space-y-1">{settlements.filter(s=>side==='customer'?s.trans_type==='Customer Receipt':s.trans_type==='Supplier Payment').map(s=><div key={s.id} className="flex flex-wrap items-center gap-2 rounded bg-slate-50 p-2"><strong>{s.entry_no}</strong><span>{s.entry_date}</span><span>{financialNumber(s.payment_amount)}</span><span>{s.payment_mode}</span><button className="btn" disabled={!can('settlement')} onClick={()=>{setCorrectSettlement(s);setCorrectAmount(String(s.payment_amount));setReason('');setDate(new Date().toISOString().slice(0,10));setCashAccount(s.cash_account_id??'')}}>Correct {s.trans_type==='Customer Receipt'?'Receipt':'Payment'}</button></div>)}</div></fieldset>}
 {correctSettlement&&<fieldset className="my-3 rounded border border-amber-200 bg-amber-50 p-3"><legend className="font-semibold">Correct Posted {correctSettlement.trans_type}</legend><p className="mb-2">Original voucher {correctSettlement.entry_no} remains in history. NAVILO posts a reversal and a corrected canonical voucher.</p><div className="flex flex-wrap items-end gap-2"><label>Correct amount<input className="input w-28" type="number" min="0.01" step="0.01" value={correctAmount} onChange={e=>setCorrectAmount(e.target.value)}/></label><label>Cash / Bank<select className="input" value={cashAccount} onChange={e=>setCashAccount(e.target.value)}><option value="">Select account</option>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="btn-primary" disabled={!can('settlement')||!cashAccount||!reason.trim()||Number(correctAmount)<=0||Number(correctAmount)===Number(correctSettlement.payment_amount)} onClick={()=>void action('transport_correct_settlement',{p_journal_entry_id:correctSettlement.id,p_new_amount:Number(correctAmount),p_date:date,p_account_id:cashAccount,p_method:method,p_reason:reason,p_reference:reference}).then(saved=>{if(saved)setCorrectSettlement(null)})}>Post Correction</button><button className="btn" disabled={busy} onClick={()=>setCorrectSettlement(null)}>Cancel</button></div></fieldset>}
 {(mode==='customer'||mode==='supplier')&&shown.length>0&&<fieldset className="my-3 rounded border p-3"><legend className="font-semibold">Receive Payment / Pay Supplier</legend>
 <div className="mb-2 flex flex-wrap gap-2"><label>Side <select className="input" value={side} onChange={e=>{setSide(e.target.value as 'customer'|'supplier');setAllocationAmounts({});setFifo('')}}><option value="customer">Customer</option><option value="supplier">Supplier / Owner</option></select></label>
 {side==='supplier'&&<label>Supplier <select className="input" value={party} onChange={e=>setParty(e.target.value)}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 <label>Cash / Bank <select className="input" value={cashAccount} onChange={e=>setCashAccount(e.target.value)}><option value="">Select account</option>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div>
 <table className="w-full text-left"><thead><tr><th>Document</th><th>Billed including VAT</th><th>Paid</th><th>Outstanding</th><th>Credit / Refund</th><th>Allocate</th><th/></tr></thead><tbody>{shown.map(b=><tr key={b.order_id} className="border-t"><td>{b.order_no}</td><td>{financialNumber(b.billed_gross)}</td><td>{financialNumber(Number(b.paid_gross)-Number(b.refunded_gross))}</td><td>{financialNumber(b.outstanding_gross)}</td><td>{financialNumber(b.credit_gross)}</td><td><input aria-label={`Allocation ${b.order_no}`} className="input w-24" type="number" min="0" max={b.outstanding_gross} step="0.01" value={allocationAmounts[b.order_id]??''} onChange={e=>setAllocationAmounts(v=>({...v,[b.order_id]:e.target.value}))}/></td><td><button className="btn" disabled={!can('settlement')||!cashAccount||Number(b.credit_gross)<=0||!reason.trim()} onClick={()=>void action('transport_refund_service_credit',{p_side:side,p_order_id:b.order_id,p_date:date,p_cash_account_id:cashAccount,p_amount:Number(b.credit_gross),p_reason:reason})}>{side==='customer'?'Refund Credit':'Recover Credit'}</button></td></tr>)}</tbody></table>
 <div className="mt-2 flex items-end gap-2"><button className="btn-primary" disabled={!can('settlement')||!cashAccount||!selectedParty||!Object.values(allocationAmounts).some(v=>Number(v)>0)} onClick={()=>void action('transport_settle_documents',{p_side:side,p_party_id:selectedParty,p_date:date,p_account_id:cashAccount,p_method:method,p_reference:reference,p_allocations:shown.filter(b=>Number(allocationAmounts[b.order_id])>0).map(b=>({document_id:b.order_id,amount:Number(allocationAmounts[b.order_id])}))})}>Post Selected Allocations</button><a className="btn text-blue-700" href="/reports/transport">Bulk selection / reviewed FIFO across Trips</a></div>
 </fieldset>}
 {mode==='correction'&&<fieldset className="my-3 rounded border p-3"><legend className="font-semibold">Rate Correction / Adjustment</legend><p className="mb-2">Customer Rate and Supplier Rent follow the same rule: before posting, a finalized value can be changed with a reason; after posting, correction creates separate canonical debit/credit evidence and preserves the original bill/invoice and payments.</p>
 <div className="flex flex-wrap items-end gap-2"><label>Rate side<select className="input" value={side} onChange={e=>setSide(e.target.value as 'customer'|'supplier')}><option value="customer">Customer</option><option value="supplier">Supplier</option></select></label>{side==='supplier'&&<label>Supplier rent <select className="input" value={rentId} onChange={e=>setRentId(e.target.value)}><option value="">Select rent</option>{rents.map(r=><option key={r.id} value={r.id}>{suppliers.find(s=>s.id===r.supplier_id)?.name} / {financialNumber(r.amount)}</option>)}</select></label>}<span>Original posted rate: {financialNumber(side==='customer'?current.customer_rate:rent?.amount)} · Current revised rate: {financialNumber(oldRate)}</span><label>New rate excluding VAT <input className="input w-32" type="number" min="0" step="0.01" value={revised} onChange={e=>setRevised(e.target.value)}/></label><span>Difference: {revised!==''&&oldRate!=null?financialNumber(Number(revised)-Number(oldRate)):''}</span><button className="btn-primary" disabled={!can('adjustment')||!reason.trim()||revised===''||(side==='supplier'&&!rentId)} onClick={()=>void (side==='supplier'&&!postedRents.has(rentId)?action('transport_finalize_supplier_rent',{p_rent_id:rentId,p_amount:Number(revised),p_reason:reason}):side==='customer'&&!current.customer_rate_locked?action('transport_finalize_customer_rate',{p_trip_id:trip.id,p_amount:Number(revised),p_source:'manual',p_reason:reason}):action('transport_adjust_rate',{p_trip_id:trip.id,p_side:side,p_new_rate:Number(revised),p_reason:reason,p_date:date,p_rent_id:side==='supplier'?rentId:null,p_reference:reference}))}>{side==='supplier'?(postedRents.has(rentId)?'Post Rent Adjustment':'Save Rent Change'):(current.customer_rate_locked?'Post Rate Adjustment':'Save Rate Change')}</button></div>
 {adjustments.map(a=><details key={a.id} className="mt-2 border-t pt-2"><summary>{a.side} · {financialNumber(a.old_value)} → {financialNumber(a.new_value)} · {financialNumber(a.difference)} · {a.reason} · {a.created_at} · {a.created_by}</summary><p>Reference: {a.reference??'—'}</p><ul>{a.accounting_evidence.map((e,i)=><li key={i}>{e.document_id&&<a className="text-blue-700 underline" href={`/${a.side==='customer'?'sales':'purchase'}/${e.document_id}`}>Adjustment {a.side==='customer'?'invoice':'bill'}</a>}{e.note_id&&<span>Canonical credit/debit note: {e.note_id}</span>}{e.journal_entry_id&&<span> · Journal: {e.journal_entry_id}</span>}</li>)}</ul></details>)}
 </fieldset>}
 {mode==='driver'&&<fieldset className="my-3 rounded border p-3"><legend className="font-semibold">Driver Account / Hisaab</legend><div className="mb-2 flex items-end gap-2"><label>Agreed driver pay <input className="input w-28" type="number" min="0" step="0.01" value={agreedPay} onChange={e=>setAgreedPay(e.target.value)}/></label><button className="btn" disabled={!can('driver')||agreedPay===''||!reason.trim()||Number(current.driver_accrued)>0||Number(current.driver_paid)>0} onClick={()=>void action('transport_set_driver_pay',{p_trip_id:trip.id,p_amount:Number(agreedPay),p_reason:reason})}>Record Agreed Pay</button></div><p>Attribute existing posted Employee Payroll accruals and salary payments. Employee mapping and available amounts are checked by the server.</p><div className="mt-2 flex flex-wrap items-end gap-2"><label>Evidence type <select className="input" value={payrollKind} onChange={e=>{setPayrollKind(e.target.value as 'accrual'|'payment');setPayrollSource('')}}><option value="accrual">Salary accrual</option><option value="payment">Salary payment</option></select></label><label>Canonical voucher <select className="input" value={payrollSource} onChange={e=>setPayrollSource(e.target.value)}><option value="">Select voucher</option>{payroll.filter(p=>p.kind===payrollKind).map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Trip attribution amount <input className="input w-28" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="btn" disabled={!can('driver')||!payrollSource||Number(amount)<=0} onClick={()=>void action('attribute_transport_driver_account',{p_trip_id:trip.id,p_source_id:payrollSource,p_amount:Number(amount),p_kind:payrollKind})}>Apply to Trip</button><a className="text-blue-700 underline" href="/accounting">Open canonical accounting</a></div></fieldset>}
 </section></div>;
}
