import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {financialNumber} from './transportFinancialTypes';
type P={opening_balance:number;trip_pay:number;allowance:number;bonus:number;other_earning:number;loan_deduction:number;other_deduction:number;payments:number;closing_balance:number;locked:boolean;entry_no?:string};
export default function TransportDriverMonthlyKhata({employeeId,onChanged}:{employeeId:string;onChanged?:()=>void}){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[p,setP]=useState<P|null>(null),[kind,setKind]=useState('allowance'),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(!employeeId){setP(null);return}setError('');const {data,error}=await supabase.rpc('transport_driver_month_preview',{p_employee_id:employeeId,p_month:month+'-01'});if(error)setError(error.message);else setP(data as P)}
 useEffect(()=>{void load()},[employeeId,month]);
 async function add(){if(!employeeId||!amount)return;setBusy(true);const {error}=await supabase.rpc('transport_driver_add_adjustment',{p_employee_id:employeeId,p_month:month+'-01',p_kind:kind,p_amount:Number(amount),p_note:note||null});setBusy(false);if(error){setError(error.message);return}setAmount('');setNote('');await load();onChanged?.()}
 async function post(){if(!employeeId||!window.confirm('Post and LOCK this driver month?'))return;setBusy(true);const {error}=await supabase.rpc('transport_driver_post_month',{p_employee_id:employeeId,p_month:month+'-01'});setBusy(false);if(error){setError(error.message);return}await load();onChanged?.()}
 if(!employeeId)return <div className="my-3 rounded border bg-slate-50 p-3 text-sm">Select a driver to review monthly khata.</div>;
 const cells:[string,number|undefined][]=[['Opening / last month',p?.opening_balance],['Trip pay',p?.trip_pay],['Allowance',p?.allowance],['Bonus',p?.bonus],['Other earning',p?.other_earning],['Loan deduction',p?.loan_deduction],['Other deduction',p?.other_deduction],['Paid',p?.payments],['Closing payable',p?.closing_balance]];
 return <section className="my-3 rounded border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Driver Monthly Khata</h3><p className="text-xs text-slate-500">Trip Register pay + adjustments + payments. Posting locks the month and creates the accounting voucher.</p></div><label className="text-sm">Month <input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>{error&&<p className="my-2 text-red-700">{error}</p>}<div className="my-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-5">{cells.map(([k,v])=><div key={k} className="rounded border bg-slate-50 p-2"><div className="text-[11px] text-slate-500">{k}</div><strong>{financialNumber(Number(v||0))}</strong></div>)}</div>{p?.locked?<div className="rounded border border-emerald-300 bg-emerald-50 p-2 text-sm font-semibold text-emerald-800">POSTED & LOCKED {p.entry_no||''}</div>:<div className="flex flex-wrap items-end gap-2"><label className="text-xs">Adjustment<select className="input" value={kind} onChange={e=>setKind(e.target.value)}><option value="allowance">Allowance</option><option value="bonus">Bonus</option><option value="loan_deduction">Loan deduction</option><option value="other_earning">Other earning</option><option value="other_deduction">Other deduction</option></select></label><label className="text-xs">Amount<input className="input w-32" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="text-xs">Note<input className="input" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn" disabled={busy||!amount} onClick={()=>void add()}>Add</button><button className="btn-primary" disabled={busy||!p} onClick={()=>void post()}>Post & Lock Month</button></div>}</section>;
}