import { useEffect,useMemo,useState } from "react";
import { Plus,Search } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";

type Kind="vehicles"|"drivers";
type Row={id:string;name:string;detail:string;owner:string;active:boolean};
export default function TransportMaster({kind}:{kind:Kind}){
 const{activeCompany,activeBusinessUnit}=useAuth();const[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(""),[error,setError]=useState(""),[show,setShow]=useState(false);
 const[form,setForm]=useState({name:"",detail:"",owner:"",mobile:""});
 const load=async()=>{setError("");if(kind==="vehicles"){const{data,error}=await supabase.from("transport_vehicles").select("id,vehicle_no,truck_type,owner_name,is_active").order("vehicle_no");if(error)return setError(error.message);setRows((data??[]).map(x=>({id:x.id,name:x.vehicle_no,detail:x.truck_type??"",owner:x.owner_name??"",active:x.is_active})));}else{const{data,error}=await supabase.from("transport_drivers").select("id,driver_name,driver_code,mobile,owner_name,is_active").order("driver_name");if(error)return setError(error.message);setRows((data??[]).map(x=>({id:x.id,name:x.driver_name,detail:[x.driver_code,x.mobile].filter(Boolean).join(" · "),owner:x.owner_name??"",active:x.is_active})));}};
 useEffect(()=>{void load()},[kind,activeCompany?.company_id,activeBusinessUnit?.business_unit_id]);
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?rows.filter(r=>[r.name,r.detail,r.owner].some(v=>v.toLowerCase().includes(s))):rows},[rows,q]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(!activeCompany?.company_id||!activeBusinessUnit?.business_unit_id)return setError("Select an active Transport business unit.");if(!form.name.trim())return setError(kind==="vehicles"?"Vehicle number is required.":"Driver name is required.");const base={company_id:activeCompany.company_id,business_unit_id:activeBusinessUnit.business_unit_id};const{error}=kind==="vehicles"?await supabase.from("transport_vehicles").insert({...base,vehicle_no:form.name.trim(),truck_type:form.detail.trim()||null,owner_name:form.owner.trim()||null}):await supabase.from("transport_drivers").insert({...base,driver_name:form.name.trim(),driver_code:form.detail.trim()||null,mobile:form.mobile.trim()||null,owner_name:form.owner.trim()||null});if(error)return setError(error.message);setForm({name:"",detail:"",owner:"",mobile:""});setShow(false);await load();};
 const toggle=async(r:Row)=>{const{error}=await supabase.from(kind==="vehicles"?"transport_vehicles":"transport_drivers").update({is_active:!r.active}).eq("id",r.id);if(error)setError(error.message);else await load();};
 const vehicle=kind==="vehicles";
 return <div className="space-y-4"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-black">{vehicle?"Vehicles":"Drivers"}</h1><p className="mt-1 text-sm text-slate-500">Transport Master Data · {activeBusinessUnit?.business_unit_name??"Transport"}</p></div><button className="btn-primary" onClick={()=>setShow(v=>!v)}><Plus className="h-4 w-4"/>Add {vehicle?"Vehicle":"Driver"}</button></div></section>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{show&&<form onSubmit={save} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-4"><label className="text-xs font-bold">{vehicle?"Vehicle No":"Driver Name"}<input className="input mt-1 w-full" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="text-xs font-bold">{vehicle?"Truck Type":"Driver Code"}<input className="input mt-1 w-full" value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})}/></label>{!vehicle&&<label className="text-xs font-bold">Mobile<input className="input mt-1 w-full" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label>}<label className="text-xs font-bold">Owner / Sponsor<input className="input mt-1 w-full" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label></div><div className="mt-4 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn-primary">Save</button></div></form>}<section className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><div className="relative max-w-xl"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input className="input w-full pl-9" placeholder={"Search "+(vehicle?"vehicle, type or owner":"driver, code, mobile or owner")} value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr>{[vehicle?"Vehicle No":"Driver Name",vehicle?"Truck Type":"Code / Mobile","Owner / Sponsor","Status","Action"].map(h=><th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id} className="border-t"><td className="px-3 py-2 font-bold">{r.name}</td><td className="px-3 py-2">{r.detail||"—"}</td><td className="px-3 py-2">{r.owner||"—"}</td><td className="px-3 py-2">{r.active?"Active":"Inactive"}</td><td className="px-3 py-2"><button className="btn-secondary" onClick={()=>void toggle(r)}>{r.active?"Disable":"Enable"}</button></td></tr>):<tr><td colSpan={5} className="p-6 text-center text-slate-500">No records.</td></tr>}</tbody></table></div></section></div>;
}