// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import TransportMaster from './TransportMaster';
const mock=vi.hoisted(()=>({rpc:vi.fn(),insert:vi.fn(),update:vi.fn(),vehicles:[] as any[]}));
vi.mock('@/auth/AuthContext',()=>({useAuth:()=>({activeCompany:{company_id:'c',enabled_modules:['transport'],membership_role:'company_owner'},activeBusinessUnit:{business_unit_id:'b',business_unit_type:'transport',enabled_modules:['transport'],membership_role:'company_owner'},isPlatformOwner:false})}));
vi.mock('@/components/DataTable',()=>({default:({rows,columns}:any)=><div>{rows.map((r:any)=><div key={r.id}>{columns.map((c:any)=><span key={c.key}>{c.render(r)}</span>)}</div>)}</div>}));
vi.mock('@/components/MasterSummaryStrip',()=>({default:()=>null}));
vi.mock('@/components/MasterActionButton',()=>({default:()=>null}));
vi.mock('./useTransportMasterClient',()=>({default:()=>client}));
const client:any={rpc:mock.rpc,from:(table:string)=>{const q:any={select:()=>q,order:()=>q,eq:()=>q,range:()=>Promise.resolve({data:table==='suppliers'?[{id:'s',name:'Owner',is_active:true}]:table==='transport_truck_types'?[{id:'tt',name:'Flatbed',is_active:true}]:table==='transport_vehicles'?mock.vehicles:[],error:null}),single:()=>Promise.resolve({data:{id:'v'},error:null}),insert:(p:any)=>{mock.insert(table,p);return q},update:(p:any)=>{mock.update(table,p);return q}};return q}};
beforeEach(()=>{mock.vehicles=[];mock.rpc.mockReset();mock.rpc.mockResolvedValue({data:'v',error:null});mock.insert.mockReset();mock.update.mockReset()});afterEach(cleanup);
function view(kind:'vehicles'|'drivers'){render(<MemoryRouter><TransportMaster kind={kind}/></MemoryRouter>)}
describe('Structured Transport master forms',()=>{
 it('creates a Vehicle with Truck Type, Supplier and explicit dated history atomically',async()=>{view('vehicles');await waitFor(()=>expect(screen.getByRole('button',{name:'Add Vehicle'})).toBeTruthy());fireEvent.click(screen.getByRole('button',{name:'Add Vehicle'}));await screen.findByRole('option',{name:'Flatbed'});fireEvent.change(screen.getByLabelText('Vehicle No / Plate No *'),{target:{value:'ABC-1'}});fireEvent.change(screen.getByLabelText('Truck Type'),{target:{value:'tt'}});fireEvent.change(screen.getByLabelText('Ownership Type'),{target:{value:'supplier'}});fireEvent.change(screen.getByLabelText('Supplier *'),{target:{value:'s'}});fireEvent.change(screen.getByLabelText('Ownership Effective From *'),{target:{value:'2026-10-01'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(mock.rpc).toHaveBeenCalledWith('transport_create_vehicle_master',{p_vehicle_no:'ABC-1',p_truck_type_id:'tt',p_owner_type:'supplier',p_supplier_id:'s',p_effective_from:'2026-10-01'}));expect(mock.insert).not.toHaveBeenCalled()});
 it('saves Supplier Driver details without a permanent Vehicle or mandatory Employee',async()=>{view('drivers');fireEvent.click(screen.getByRole('button',{name:'Add Driver'}));await screen.findByRole('option',{name:'Supplier Driver'});fireEvent.change(screen.getByLabelText('Driver Name *'),{target:{value:'Driver One'}});fireEvent.change(screen.getByLabelText('Driver Type'),{target:{value:'supplier'}});await screen.findByRole('option',{name:'Owner'});fireEvent.change(screen.getByLabelText('Supplier *'),{target:{value:'s'}});fireEvent.change(screen.getByLabelText('Driving Licence No'),{target:{value:'LIC-1'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(mock.insert).toHaveBeenCalledWith('transport_drivers',expect.objectContaining({driver_name:'Driver One',driver_type:'supplier',supplier_id:'s',driving_licence_no:'LIC-1'})));expect(mock.insert.mock.calls[0][1]).not.toHaveProperty('vehicle_id');expect(mock.insert.mock.calls[0][1]).toHaveProperty('employee_id',null)});
 it('keeps current owner out of direct Vehicle edits',async()=>{mock.vehicles=[{id:'v',vehicle_no:'ABC',truck_type_id:'tt',ownership_type:'supplier',supplier_id:'s',owner_name:'Owner',is_active:true}];view('vehicles');await screen.findByRole('button',{name:/Edit/});fireEvent.click(screen.getByRole('button',{name:/Edit/}));expect(screen.queryByLabelText('Ownership Type')).toBeNull();expect(screen.getByRole('link',{name:'Change through Vehicle Ownership History'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(mock.update).toHaveBeenCalledWith('transport_vehicles',{vehicle_no:'ABC',truck_type_id:'tt'}));});
});
