import {useEffect,useState} from 'react';
import {useAuth} from '@/auth/AuthContext';
import {supabase} from '@/lib/supabase';
import NaviloDateInput from '@/components/NaviloDateInput';
import ConfigurableReport from '../transport/ConfigurableReport';
export default function CashFlowStatement(){
 const {activeCompany,activeBusinessUnit}=useAuth();const [from,setFrom]=useState(`${new Date().getFullYear()}-01-01`);const [to,setTo]=useState(new Date().toISOString().slice(0,10));const [report,setReport]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;setLoading(true);setError('');if(!from||!to||from>to){setError('Valid From and To dates required');setLoading(false);return}void supabase.rpc('accounting_cash_flow_report',{p_from:from,p_to:to}).then(({data,error})=>{if(live){setReport(data);setLoading(false);if(error)setError(error.message)}});return()=>{live=false}},[from,to,activeCompany?.company_id,activeBusinessUnit?.business_unit_id]);
 const names:Record<string,string>={operating:'Operating activities',investing:'Investing activities',financing:'Financing activities',unclassified:'Unclassified / mixed vouchers'};
 return <div className="space-y-3"><h1 className="text-xl font-semibold">Cash Flow Statement</h1><p className="text-xs">Direct method · Posted cash and bank movements. Transfers between cash/bank accounts cancel out. Non-cash transactions are excluded. Mixed or unknown account classifications are shown separately for review.</p><div className="flex gap-2"><label>From<NaviloDateInput className="input" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<NaviloDateInput className="input" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p role="status">Loading posted cash flow…</p>:!error&&report&&<><ConfigurableReport module="accounting" preferenceKey={`${activeCompany?.company_id}:cash-flow`} report={{title:'Cash Flow Statement',description:`${activeCompany?.company_name||''} / ${activeBusinessUnit?.business_unit_name||''} · ${from} to ${to} · Company base currency · Reconciliation difference ${Number(report.difference||0).toFixed(2)}`,columns:['Activity','Posted vouchers','Cash movement'],rows:[['Opening cash and bank','',Number(report.opening)],...['operating','investing','financing','unclassified'].map(category=>{const row=report.rows.find((r:any)=>r.category===category);return [names[category],Number(row?.vouchers||0),Number(row?.amount||0)]}),['TOTAL / Net change','',Number(report.movement)],['Closing cash and bank','',Number(report.closing)]]}}/>{Math.abs(Number(report.difference))>=0.005&&<p role="alert">Cash flow does not reconcile to the posted ledger. Review the canonical journals and account mappings.</p>}<p className="text-xs">Open Accounting → Day Book or General Ledger to inspect the source vouchers. Unclassified amounts remain in the cash reconciliation.</p></>}</div>;
}
