import {currentCurrency} from "@/components/ui";
import {fetchAllPages} from "@/lib/fetchAllPages";
import {formatNaviloDate} from "@/lib/naviloDate";
import { escapePrintHtml, createPrintDocument, registerPrintSource, printTableMarkup } from "@/lib/printDocument";
import NaviloDateInput from '@/components/NaviloDateInput';
import SearchableSelect from "@/components/SearchableSelect";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CheckCircle2, FileDown, Loader2, Plus, Printer, RefreshCw, Search } from "lucide-react";
import jsPDF from "jspdf";
import { supabase } from "@/lib/supabase";

type TransactionType = "salary_payment" | "expense_payment" | "loan_received" | "loan_repayment" | "capital_received" | "drawings_payment" | "other_receipt" | "other_payment";
type Account = { id:string; code:string; name:string; type:"asset"|"liability"|"equity"|"revenue"|"expense"; account_role?:string|null; detail_type?:string|null; is_group?:boolean|null; is_active?:boolean|null; allow_manual_entries?:boolean|null };
type Employee = { id:string; employee_code?:string|null; name:string; phone?:string|null; designation?:string|null; department?:string|null };
type PartySuggestion = { id:string; name:string; source:string };
type Lender = { id:string; name:string; phone?:string|null };
type Voucher = { id:string; entry_no:string; entry_date:string; description:string; party_name?:string|null; payment_mode?:string|null };
type SalarySummary = { salary_account_id?:string;driver_salary_account?:boolean; salary_advance?:number; basic_salary?:number; trip_pay?:number; configured:boolean; monthly_salary:number; effective_from?:string; previous_balance:number; paid_in_month:number; total_payable:number; remaining_balance:number };
type PostedVoucher = { entryNo:string; date:string; transactionType:string; counterAccount:string; cashBankAccount:string; amount:number; partyName:string; reference:string; notes:string; employeeCode?:string; designation?:string; department?:string; salaryMonth?:string; monthlySalary?:number; previousBalance?:number; paidBeforeThisPayment?:number; totalPayable?:number; remainingBalance?:number; isSalary?:boolean };

const CONTROLLED_MAPPING_KEYS = new Set(["accounts_receivable","accounts_payable","inventory","input_vat","output_vat","cogs","cash","bank"]);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const currentMonth=()=>today().slice(0,7);
const money=(v:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const TYPES=[
 {value:"salary_payment",label:"Salary Payment",partyLabel:"Employee"},{value:"expense_payment",label:"Expense Payment",partyLabel:"Paid To"},{value:"loan_received",label:"Loan Received",partyLabel:"Lender"},{value:"loan_repayment",label:"Loan Repayment",partyLabel:"Lender"},{value:"capital_received",label:"Capital Received",partyLabel:"Owner"},{value:"drawings_payment",label:"Owner Drawings",partyLabel:"Owner"},{value:"other_receipt",label:"Other Receipt",partyLabel:"Received From"},{value:"other_payment",label:"Other Payment",partyLabel:"Paid To"},
] as const;
const isCashBank=(a:Account)=>a.type==="asset"&&(a.detail_type==="Cash on Hand"||a.detail_type==="Bank Account"||a.account_role==="cash"||a.account_role==="bank");

export default function GeneralCashBankPanel(){
 const [accounts,setAccounts]=useState<Account[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[expensePayees,setExpensePayees]=useState<PartySuggestion[]>([]),[lenders,setLenders]=useState<Lender[]>([]),[mappedIds,setMappedIds]=useState<Record<string,string>>({}),[history,setHistory]=useState<Voucher[]>([]);
 const [transactionType,setTransactionType]=useState<TransactionType>("salary_payment"),[transactionDate,setTransactionDate]=useState(today()),[counterAccountId,setCounterAccountId]=useState(""),[cashBankAccountId,setCashBankAccountId]=useState(""),[partyName,setPartyName]=useState(""),[amount,setAmount]=useState(""),[reference,setReference]=useState(""),[notes,setNotes]=useState(""),[search,setSearch]=useState("");
 const [employeeId,setEmployeeId]=useState(""),[employeeSearch,setEmployeeSearch]=useState(""),[showEmployeeResults,setShowEmployeeResults]=useState(false),[showPartyResults,setShowPartyResults]=useState(false);
 const [lenderId,setLenderId]=useState(""),[showNewLender,setShowNewLender]=useState(false),[newLenderName,setNewLenderName]=useState(""),[newLenderPhone,setNewLenderPhone]=useState(""),[savingLender,setSavingLender]=useState(false);
 const [salaryMonth,setSalaryMonth]=useState(currentMonth()),[salarySummary,setSalarySummary]=useState<SalarySummary|null>(null),[salaryLoading,setSalaryLoading]=useState(false),[monthlySalarySetup,setMonthlySalarySetup]=useState(""),[salaryEffectiveFrom,setSalaryEffectiveFrom]=useState(today()),[savingSalaryProfile,setSavingSalaryProfile]=useState(false),[showSalaryBalances,setShowSalaryBalances]=useState(true);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null),[lastVoucher,setLastVoucher]=useState<PostedVoucher|null>(null);
 const selectedType=TYPES.find(x=>x.value===transactionType)||TYPES[0];
 const selectedEmployee=employees.find(e=>e.id===employeeId);
 const selectedLender=lenders.find(l=>l.id===lenderId);
 const cashBankAccounts=useMemo(()=>accounts.filter(isCashBank),[accounts]);
 const counterAccounts=useMemo(()=>{const controlled=new Set(Object.entries(mappedIds).filter(([k])=>CONTROLLED_MAPPING_KEYS.has(k)).map(([,id])=>id));return accounts.filter(a=>{if(isCashBank(a))return false;const d=String(a.detail_type||"").toLowerCase(),n=a.name.toLowerCase();if(transactionType==="salary_payment"&&salarySummary?.driver_salary_account)return a.id===salarySummary.salary_account_id;if(transactionType==="salary_payment")return a.type==="expense"&&(a.id===mappedIds.salary_expense||d==="salaries"||n.includes("salary"));if(transactionType==="expense_payment")return a.type==="expense"&&a.id!==mappedIds.salary_expense&&a.id!==mappedIds.cogs&&!d.includes("cost of goods")&&d!=="cogs"&&d!=="salaries"&&!n.includes("cost of goods sold")&&!n.includes("salary");if(transactionType==="loan_received"||transactionType==="loan_repayment")return a.type==="liability"&&(d==="loan payable"||n.includes("loan payable"));if(transactionType==="capital_received")return a.type==="equity"&&!d.includes("retained")&&!d.includes("draw")&&!n.includes("retained earnings")&&!n.includes("draw");if(transactionType==="drawings_payment")return a.type==="equity"&&(d.includes("draw")||n.includes("draw"));if(transactionType==="other_receipt")return !controlled.has(a.id)&&!d.includes("retained")&&(a.type==="revenue"||a.type==="liability"||a.type==="equity");if(transactionType==="other_payment")return !controlled.has(a.id)&&!d.includes("retained")&&(a.type==="expense"||a.type==="asset"||a.type==="liability"||a.type==="equity");return false})},[accounts,mappedIds,transactionType,salarySummary?.driver_salary_account,salarySummary?.salary_account_id]);
 const filteredEmployees=useMemo(()=>employees.filter(e=>!employeeSearch.trim()||`${e.name} ${e.employee_code||""} ${e.designation||""}`.toLowerCase().includes(employeeSearch.toLowerCase())).slice(0,12),[employees,employeeSearch]);
 const filteredPayees=useMemo(()=>expensePayees.filter(p=>!partyName.trim()||`${p.name} ${p.source}`.toLowerCase().includes(partyName.toLowerCase())).slice(0,12),[expensePayees,partyName]);
 const filteredHistory=useMemo(()=>history.filter(r=>!search.trim()||[r.entry_no,r.entry_date,r.party_name,r.description].join(" ").toLowerCase().includes(search.toLowerCase())),[history,search]);

 const historyPrintRoot=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const root=historyPrintRoot.current;if(!root)return;return registerPrintSource(root,async()=>{
   const all=await fetchAllPages<Voucher>((from,to)=>supabase.from('journal_entries').select('id,entry_no,entry_date,description,party_name,payment_mode').eq('status','posted').eq('trans_type','General Cash/Bank').order('entry_date',{ascending:false}).order('id').range(from,to));
   const q=search.trim().toLowerCase(),filtered=all.filter(row=>!q||[row.entry_no,row.entry_date,row.party_name,row.description].join(' ').toLowerCase().includes(q));
   return printTableMarkup('General Cash / Bank History',['Voucher','Date','Description','Party'],filtered.map(row=>[row.entry_no,formatNaviloDate(row.entry_date),row.description,row.party_name||'—']),'Complete posted history matching the search.');
 });},[search]);
 const load=useCallback(async()=>{setLoading(true);try{const [ar,er,tr,lr,mr,hr]=await Promise.all([supabase.from("chart_of_accounts").select("id,code,name,type,account_role,detail_type,is_group,is_active,allow_manual_entries").eq("is_active",true).eq("is_group",false).eq("allow_manual_entries",true).order("code"),supabase.from("employees").select("id,employee_code,name,phone,designation,department").eq("is_active",true).order("name"),supabase.from("transporters").select("id,name").order("name"),supabase.from("loan_parties").select("id,name,phone").eq("is_active",true).order("name"),supabase.from("account_mappings").select("mapping_key,account_id"),supabase.from("journal_entries").select("id,entry_no,entry_date,description,party_name,payment_mode").eq("status","posted").eq("trans_type","General Cash/Bank").order("entry_date",{ascending:false}).limit(100)]);if(ar.error)throw ar.error;if(er.error)throw er.error;if(lr.error)throw lr.error;if(hr.error)throw hr.error;setAccounts((ar.data||[]) as Account[]);setEmployees((er.data||[]) as Employee[]);setLenders((lr.data||[]) as Lender[]);const m:Record<string,string>={};(mr.data||[]).forEach((r:any)=>{if(r.mapping_key&&r.account_id)m[r.mapping_key]=r.account_id});setMappedIds(m);setExpensePayees((tr.data||[]).map((r:any)=>({id:r.id,name:r.name,source:"Transporter"})));setHistory((hr.data||[]) as Voucher[]);const first=(ar.data||[]).find((a:any)=>isCashBank(a));if(first)setCashBankAccountId(x=>x||first.id);if(m.salary_expense)setCounterAccountId(x=>x||m.salary_expense)}catch(e:any){setError(e.message||"Failed to load general transactions.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setCounterAccountId(transactionType==="salary_payment"?(mappedIds.salary_expense||""):"");setPartyName("");setEmployeeId("");setEmployeeSearch("");setLenderId("");setSalarySummary(null);setShowPartyResults(false)},[transactionType,mappedIds.salary_expense]);
 useEffect(()=>{if((transactionType==="loan_received"||transactionType==="loan_repayment")&&counterAccounts.length===1)setCounterAccountId(counterAccounts[0].id)},[transactionType,counterAccounts]);

 const salarySummaryGeneration=useRef(0);
 const loadSalarySummary=useCallback(async(id:string,month:string)=>{const token=++salarySummaryGeneration.current;if(!id||!month){setSalarySummary(null);return}setSalaryLoading(true);setError(null);try{const {data,error:e}=await supabase.rpc("get_employee_salary_summary",{p_employee_id:id,p_salary_month:`${month}-01`} as any);if(e)throw e;if(token!==salarySummaryGeneration.current)return;const s=(data||{}) as any;setSalarySummary({salary_account_id:s.salary_account_id,driver_salary_account:Boolean(s.driver_salary_account),salary_advance:Number(s.salary_advance||0),basic_salary:Number(s.basic_salary||0),trip_pay:Number(s.trip_pay||0),configured:Boolean(s.configured),monthly_salary:Number(s.monthly_salary||0),effective_from:s.effective_from||undefined,previous_balance:Number(s.previous_balance||0),paid_in_month:Number(s.paid_in_month||0),total_payable:Number(s.total_payable||0),remaining_balance:Number(s.remaining_balance||0)});setMonthlySalarySetup(s.configured?String(s.monthly_salary??" ").trim():"");setSalaryEffectiveFrom(s.effective_from||today());if(s.driver_salary_account&&s.salary_account_id)setCounterAccountId(s.salary_account_id)}catch(e:any){if(token===salarySummaryGeneration.current){setSalarySummary(null);setError(e.message||"Failed to load salary balance.")}}finally{if(token===salarySummaryGeneration.current)setSalaryLoading(false)}},[]);
 useEffect(()=>{if(transactionType==="salary_payment"&&employeeId)void loadSalarySummary(employeeId,salaryMonth);else {salarySummaryGeneration.current++;setSalarySummary(null);setSalaryLoading(false)}return()=>{salarySummaryGeneration.current++}},[transactionType,employeeId,salaryMonth,loadSalarySummary]);

 const saveSalaryProfile=async()=>{setSavingSalaryProfile(true);setError(null);try{const v=Number(monthlySalarySetup);if(!employeeId||!Number.isFinite(v)||v<=0||!salaryEffectiveFrom)throw new Error("Enter monthly salary and effective date.");const {error:e}=await supabase.rpc("set_employee_salary_profile",{p_employee_id:employeeId,p_monthly_salary:v,p_effective_from:salaryEffectiveFrom} as any);if(e)throw e;setSuccess("Employee salary setup saved.");await loadSalarySummary(employeeId,salaryMonth)}catch(e:any){setError(e.message||"Failed to save salary setup.")}finally{setSavingSalaryProfile(false)}};
 const saveLender=async()=>{setSavingLender(true);setError(null);try{if(!newLenderName.trim())throw new Error("Enter lender name.");const {data,error:e}=await supabase.rpc("create_loan_party",{p_name:newLenderName.trim(),p_phone:newLenderPhone.trim()||null,p_notes:null} as any);if(e)throw e;await load();if(data)setLenderId(String(data));setNewLenderName("");setNewLenderPhone("");setShowNewLender(false);setSuccess("Lender saved.")}catch(e:any){setError(e.message||"Failed to save lender.")}finally{setSavingLender(false)}};

 const post=async()=>{setSaving(true);setError(null);setSuccess(null);try{const v=Number(amount);if(!transactionDate||!cashBankAccountId||!Number.isFinite(v)||v<=0)throw new Error("Complete all required transaction fields.");let data:any;if(transactionType==="salary_payment"){if(salaryLoading)throw new Error("Wait for salary balance to load.");if(!counterAccountId)throw new Error("Select salary account.");if(!employeeId||!selectedEmployee)throw new Error("Select an employee.");if(!salarySummary?.configured&&!salarySummary?.driver_salary_account)throw new Error("Configure monthly salary before posting.");const r=await supabase.rpc("post_salary_payment",{p_employee_id:employeeId,p_salary_month:`${salaryMonth}-01`,p_transaction_date:transactionDate,p_salary_account_id:counterAccountId,p_cash_bank_account_id:cashBankAccountId,p_amount:v,p_reference:reference.trim()||null,p_notes:notes.trim()||null} as any);if(r.error)throw r.error;data=r.data}else if(transactionType==="loan_received"||transactionType==="loan_repayment"){if(!lenderId||!selectedLender)throw new Error("Select a lender or add a new lender first.");const r=await supabase.rpc("post_loan_party_transaction",{p_lender_id:lenderId,p_transaction_type:transactionType,p_transaction_date:transactionDate,p_cash_bank_account_id:cashBankAccountId,p_amount:v,p_reference:reference.trim()||null,p_notes:notes.trim()||null} as any);if(r.error)throw r.error;data=r.data}else{if(!counterAccountId)throw new Error("Select transaction account.");if(transactionType==="expense_payment"&&!partyName.trim())throw new Error("Paid To is required.");const r=await supabase.rpc("post_general_cash_bank_transaction",{p_transaction_type:transactionType,p_transaction_date:transactionDate,p_counter_account_id:counterAccountId,p_cash_bank_account_id:cashBankAccountId,p_amount:v,p_party_name:partyName.trim()||null,p_reference:reference.trim()||null,p_notes:notes.trim()||null} as any);if(r.error)throw r.error;data=r.data}
 const counter=accounts.find(a=>a.id===counterAccountId),cash=accounts.find(a=>a.id===cashBankAccountId);const entryNo=String(data?.entry_no||data||"Posted");const voucherParty=transactionType==="salary_payment"?(selectedEmployee?.name||""):(transactionType==="loan_received"||transactionType==="loan_repayment"?(selectedLender?.name||""):partyName.trim());setLastVoucher({entryNo,date:transactionDate,transactionType:selectedType.label,counterAccount:counter?.name||((transactionType==="loan_received"||transactionType==="loan_repayment")?"Loan Payable":""),cashBankAccount:cash?.name||"",amount:v,partyName:voucherParty,reference:reference.trim(),notes:notes.trim(),isSalary:transactionType==="salary_payment",employeeCode:selectedEmployee?.employee_code||undefined,designation:selectedEmployee?.designation||undefined,department:selectedEmployee?.department||undefined,salaryMonth:transactionType==="salary_payment"?salaryMonth:undefined,monthlySalary:Number(data?.monthly_salary||salarySummary?.monthly_salary||0),previousBalance:Number(data?.previous_balance||0),paidBeforeThisPayment:Number(data?.paid_before_this_payment||0),totalPayable:Number(data?.total_payable_before_payment||0),remainingBalance:Number(data?.remaining_balance||0)});setSuccess(`Transaction posted: ${entryNo}`);setAmount("");setReference("");setNotes("");if(transactionType!=="salary_payment")setPartyName("");await load();if(transactionType==="salary_payment"&&employeeId)await loadSalarySummary(employeeId,salaryMonth)}catch(e:any){setError(e.message||"Failed to post transaction.")}finally{setSaving(false)}};

 const salaryRows=(v:PostedVoucher,showBalances:boolean)=>{const rows:[string,string][]=[["Voucher",v.entryNo],["Employee",v.partyName],["Employee Code",v.employeeCode||"-"],["Designation",v.designation||"-"],["Department",v.department||"-"],["Salary Month",v.salaryMonth||"-"],["Basic Salary",`${currentCurrency()} ${money(v.monthlySalary||0)}`],["Payment Date",v.date],["Cash / Bank",v.cashBankAccount],["Amount Paid Now",`${currentCurrency()} ${money(v.amount)}`]];if(showBalances)rows.push(["Previous Balance",`${currentCurrency()} ${money(v.previousBalance||0)}`],["Paid Earlier This Month",`${currentCurrency()} ${money(v.paidBeforeThisPayment||0)}`],["Total Payable Before Payment",`${currentCurrency()} ${money(v.totalPayable||0)}`],[Number(v.remainingBalance||0)<0?"Salary Advance":"Remaining Balance",`${currentCurrency()} ${money(Math.abs(v.remainingBalance||0))}`]);rows.push(["Reference",v.reference||"-"],["Notes",v.notes||"-"]);return rows};
 const printVoucher=(v:PostedVoucher)=>{const showBalances=v.isSalary?showSalaryBalances:true;const title=v.isSalary?"SALARY PAYMENT SLIP":"GENERAL CASH / BANK VOUCHER";const rows=v.isSalary?salaryRows(v,showBalances):[["Voucher",v.entryNo],["Date",v.date],["Type",v.transactionType],[selectedType.partyLabel,v.partyName||"-"],["Transaction Account",v.counterAccount],["Cash / Bank",v.cashBankAccount],["Amount",`${currentCurrency()} ${money(v.amount)}`],["Reference",v.reference||"-"],["Notes",v.notes||"-"]] as [string,string][];const w=createPrintDocument();if(!w)return;w.document.write(`<html><head><title>${escapePrintHtml(v.entryNo)}</title><style>body{font-family:Arial;padding:36px;color:#111}h1{text-align:center;margin-bottom:8px}.sub{text-align:center;color:#555;margin-bottom:24px}.row{display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid #ddd;padding:9px 0}.row span:last-child{text-align:right}.sig{display:flex;justify-content:space-between;margin-top:70px;font-size:12px}</style></head><body><h1>${title}</h1>${rows.map(r=>`<div class="row"><b>${escapePrintHtml(r[0])}</b><span>${escapePrintHtml(r[1])}</span></div>`).join("")}<div class="sig"><span>Prepared By __________</span><span>Authorized By __________</span><span>${v.isSalary?"Employee Signature":"Received By"} __________</span></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};
 const pdf=(v:PostedVoucher)=>{const showBalances=v.isSalary?showSalaryBalances:true;const rows=v.isSalary?salaryRows(v,showBalances):[["Voucher",v.entryNo],["Date",v.date],["Type",v.transactionType],[selectedType.partyLabel,v.partyName||"-"],["Transaction Account",v.counterAccount],["Cash / Bank",v.cashBankAccount],["Amount",`${currentCurrency()} ${money(v.amount)}`],["Reference",v.reference||"-"],["Notes",v.notes||"-"]] as [string,string][];const d=new jsPDF();d.setFontSize(16);d.text(v.isSalary?"SALARY PAYMENT SLIP":"GENERAL CASH / BANK VOUCHER",105,18,{align:"center"});d.setFontSize(10);rows.forEach((r,i)=>{d.text(String(r[0]),18,34+i*9);d.text(String(r[1]),78,34+i*9)});d.save(`${v.entryNo}.pdf`)};
 const remainingPreview=salarySummary?.driver_salary_account?Number(salarySummary.remaining_balance||0)-Math.max(Number(amount)||0,0):Math.max(Number(salarySummary?.total_payable||0)-Math.max(Number(amount)||0,0),0);
 const isLoan=transactionType==="loan_received"||transactionType==="loan_repayment";

 return <div className="space-y-5"><div className="rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-bold">General Cash</h2><p className="text-slate-500">Salary, expenses, loans, capital and other receipts/payments with automatic accounting.</p></div><div className="grid gap-4 p-5 md:grid-cols-2">
 <label className="font-semibold">Transaction Type<SearchableSelect nativeCompatibility preserveLabel className="mt-2 w-full rounded-lg border p-3" value={transactionType} onChange={e=>setTransactionType(e.target.value as TransactionType)}>{TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</SearchableSelect></label><label className="font-semibold">Date<NaviloDateInput className="mt-2 w-full rounded-lg border p-3" type="date" value={transactionDate} onChange={e=>setTransactionDate(e.target.value)}/></label>
 <div className="relative"><label className="font-semibold">{selectedType.partyLabel}</label>{transactionType==="salary_payment"?<><input className="mt-2 w-full rounded-lg border p-3" placeholder="Search employee" value={employeeSearch} onFocus={()=>setShowEmployeeResults(true)} onChange={e=>{setEmployeeSearch(e.target.value);setEmployeeId("");setPartyName(e.target.value);setShowEmployeeResults(true)}}/>{showEmployeeResults&&<div className="absolute z-30 mt-1 max-h-56 w-full overflow-auto rounded-lg border bg-white shadow">{filteredEmployees.map(e=><button type="button" className="block w-full p-3 text-left hover:bg-slate-50" key={e.id} onClick={()=>{setEmployeeId(e.id);setPartyName(e.name);setEmployeeSearch(e.name);setShowEmployeeResults(false)}}>{e.name}{e.designation?<span className="ml-2 text-xs text-slate-400">{e.designation}</span>:null}</button>)}</div>}</>:isLoan?<><div className="mt-2 flex gap-2"><SearchableSelect nativeCompatibility preserveLabel className="w-full rounded-lg border p-3" value={lenderId} onChange={e=>setLenderId(e.target.value)}><option value="">Select lender...</option>{lenders.map(l=><option key={l.id} value={l.id}>{l.name}{l.phone?` · ${l.phone}`:""}</option>)}</SearchableSelect><button type="button" className="rounded-lg border px-3" onClick={()=>setShowNewLender(v=>!v)} title="Add lender"><Plus className="h-4 w-4"/></button></div>{showNewLender&&<div className="mt-2 grid gap-2 rounded-lg border bg-slate-50 p-3"><input className="rounded-lg border bg-white p-2" placeholder="New lender name" value={newLenderName} onChange={e=>setNewLenderName(e.target.value)}/><input className="rounded-lg border bg-white p-2" placeholder="Phone (optional)" value={newLenderPhone} onChange={e=>setNewLenderPhone(e.target.value)}/><button type="button" className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white" disabled={savingLender} onClick={()=>void saveLender()}>{savingLender?"Saving...":"Save Lender"}</button></div>}</>:transactionType==="expense_payment"?<><input className="mt-2 w-full rounded-lg border p-3" placeholder="Search payee or type a name" value={partyName} onFocus={()=>setShowPartyResults(true)} onChange={e=>{setPartyName(e.target.value);setShowPartyResults(true)}}/>{showPartyResults&&filteredPayees.length>0&&<div className="absolute z-30 mt-1 w-full rounded-lg border bg-white shadow">{filteredPayees.map(p=><button type="button" className="block w-full p-3 text-left" key={p.id} onClick={()=>{setPartyName(p.name);setShowPartyResults(false)}}>{p.name} <span className="text-xs text-slate-400">{p.source}</span></button>)}</div>}</>:<input className="mt-2 w-full rounded-lg border p-3" placeholder="Name" value={partyName} onChange={e=>setPartyName(e.target.value)}/>}</div>
 {transactionType==="salary_payment"&&<label className="font-semibold">Salary Month<input className="mt-2 w-full rounded-lg border p-3" type="month" value={salaryMonth} onChange={e=>setSalaryMonth(e.target.value)}/></label>}
 <div><label className="font-semibold">Transaction Account</label><div className="mt-2"><SearchableSelect value={counterAccountId} onChange={e=>setCounterAccountId(e.target.value)} searchPlaceholder="Type to search account..."><option value="">Select account...</option>{counterAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></div>{isLoan&&<p className="mt-1 text-xs text-slate-500">Loan transactions use the dedicated Loan Payable liability account.</p>}</div><div><label className="font-semibold">Cash / Bank</label><div className="mt-2"><SearchableSelect value={cashBankAccountId} onChange={e=>setCashBankAccountId(e.target.value)} searchPlaceholder="Type to search account..."><option value="">Select cash/bank...</option>{cashBankAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></div></div>
 {transactionType==="salary_payment"&&employeeId&&salaryLoading&&<div className="md:col-span-2 rounded-lg bg-slate-50 p-4 text-slate-600">Loading salary balance...</div>}
 {transactionType==="salary_payment"&&employeeId&&!salaryLoading&&salarySummary&&!salarySummary.configured&&<div className="md:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="mb-3 font-bold text-amber-900">Basic salary setup required for {selectedEmployee?.name}</div><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Monthly Salary<input type="number" min="0" step="0.01" className="mt-1 w-full rounded-lg border bg-white p-3" value={monthlySalarySetup} onChange={e=>setMonthlySalarySetup(e.target.value)}/></label><label className="text-sm font-semibold">Effective From<NaviloDateInput type="date" className="mt-1 w-full rounded-lg border bg-white p-3" value={salaryEffectiveFrom} onChange={e=>setSalaryEffectiveFrom(e.target.value)}/></label></div><button type="button" onClick={saveSalaryProfile} disabled={savingSalaryProfile} className="mt-3 rounded-lg bg-amber-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{savingSalaryProfile?"Saving...":"Save Salary Setup"}</button></div>}
 {transactionType==="salary_payment"&&(salarySummary?.configured||salarySummary?.driver_salary_account)&&<div className="md:col-span-2 rounded-xl border bg-slate-50 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div className="font-bold">{salarySummary.driver_salary_account?"Salary Balance Preview":"Salary Balance"} — {selectedEmployee?.name}</div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={showSalaryBalances} onChange={e=>setShowSalaryBalances(e.target.checked)}/> Show balance on salary slip</label></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><div><span className="text-xs text-slate-500">Monthly Salary</span><div className="font-bold">{currentCurrency()} {money(salarySummary.monthly_salary)}</div></div><div><span className="text-xs text-slate-500">Previous Balance</span><div className="font-bold">{currentCurrency()} {money(salarySummary.previous_balance)}</div></div><div><span className="text-xs text-slate-500">Paid This Month</span><div className="font-bold">{currentCurrency()} {money(salarySummary.paid_in_month)}</div></div><div><span className="text-xs text-slate-500">Total Payable</span><div className="font-bold">{currentCurrency()} {money(salarySummary.total_payable)}</div></div><div><span className="text-xs text-slate-500">Paid Now</span><div className="font-bold">{currentCurrency()} {money(Number(amount)||0)}</div></div><div><span className="text-xs text-slate-500">{remainingPreview<0?"Salary advance":"Remaining payable"}</span><div className="font-bold text-rose-700">{currentCurrency()} {money(Math.abs(remainingPreview))}</div></div></div></div>}
 <label className="font-semibold">Amount<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="font-semibold">Reference<input className="mt-2 w-full rounded-lg border p-3" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="font-semibold md:col-span-2">Notes<textarea className="mt-2 w-full rounded-lg border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 {error&&<div className="md:col-span-2 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{success&&<div className="md:col-span-2 rounded-lg bg-emerald-50 p-3 text-emerald-700">{success}</div>}<button type="button" onClick={post} disabled={saving||loading||salaryLoading||Boolean(transactionType==="salary_payment"&&!salarySummary?.configured&&!salarySummary?.driver_salary_account)} className="md:col-span-2 rounded-lg bg-blue-600 p-3 font-semibold text-white disabled:opacity-50">{saving?<Loader2 className="mx-auto animate-spin"/>:<><CheckCircle2 className="mr-2 inline h-5 w-5"/>Post Transaction</>}</button>{lastVoucher&&<div className="md:col-span-2 flex flex-wrap gap-2"><button type="button" onClick={()=>printVoucher(lastVoucher)} className="rounded-lg border px-4 py-2"><Printer className="mr-2 inline h-4 w-4"/>{lastVoucher.isSalary?"Print Salary Slip":"Print Voucher"}</button><button type="button" onClick={()=>pdf(lastVoucher)} className="rounded-lg border px-4 py-2"><FileDown className="mr-2 inline h-4 w-4"/>PDF</button></div>}
 </div></div><div ref={historyPrintRoot} className="rounded-xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-lg font-bold">General Transaction History</h3><p className="text-sm text-slate-500">Search posted vouchers.</p></div><button onClick={load} className="rounded-lg border p-2"><RefreshCw className="h-4 w-4"/></button></div><div data-report-filters className="relative mb-3"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input className="w-full rounded-lg border py-2 pl-9 pr-3" placeholder="Search voucher, name, date..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Voucher</th><th className="p-2">Date</th><th className="p-2">Description</th><th className="p-2">Party</th></tr></thead><tbody>{filteredHistory.map(r=><tr className="border-b" key={r.id}><td className="p-2">{r.entry_no}</td><td className="p-2">{r.entry_date}</td><td className="p-2">{r.description}</td><td className="p-2">{r.party_name||"-"}</td></tr>)}</tbody></table></div></div></div>
}
