import SearchableSelect from "@/components/SearchableSelect";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Printer, RotateCcw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ErrorBanner, LoadingState, PageHeader, formatDate } from "@/components/ui";
import PrintLayout, { type PrintItemRow } from "@/components/PrintLayout";
import { triggerPrint } from "@/lib/exportUtils";

type NoteType = "sales_credit" | "purchase_debit";
interface Order { id:string; order_no:string; order_date:string; total:number; party_name:string; }
interface InvoiceLine { id:string; item_id:string; godown_id:string|null; qty:number; rate:number; tax_percent:number; item_name:string; returned:number; returnQty:string; }
interface Note { id:string; note_no:string; note_type:NoteType; note_date:string; party_name:string; reason:string; subtotal:number; tax_total:number; total:number; sales_order_id:string|null; purchase_order_id:string|null; fbr_invoice_no:string|null; fbr_qr_payload:string|null; fbr_verification_url:string|null; }
type PrintState = { note:Note; sourceNo:string; items:PrintItemRow[]; company:any };

const money=(value:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0);

export default function ReturnNotes(){
 const [type,setType]=useState<NoteType>("sales_credit"); const [orders,setOrders]=useState<Order[]>([]); const [orderId,setOrderId]=useState(""); const [lines,setLines]=useState<InvoiceLine[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [noteDate,setNoteDate]=useState(new Date().toISOString().slice(0,10)); const [reason,setReason]=useState(""); const [loading,setLoading]=useState(true); const [posting,setPosting]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [printState,setPrintState]=useState<PrintState|null>(null);

 const load=useCallback(async()=>{ setLoading(true); setError(""); const isSale=type==="sales_credit"; const [orderResult,noteResult]=await Promise.all([
  supabase.from(isSale?"sales_orders":"purchase_orders").select(isSale?"id,order_no,order_date,total,tax_percent,customer:customers(name)":"id,order_no,order_date,total,tax_percent,supplier:suppliers(name)").eq("status","posted").order("order_date",{ascending:false}),
  supabase.from("return_notes").select("id,note_no,note_type,note_date,party_name,reason,subtotal,tax_total,total,sales_order_id,purchase_order_id,fbr_invoice_no,fbr_qr_payload,fbr_verification_url").eq("note_type",type).order("note_date",{ascending:false}).limit(100)
 ]); if(orderResult.error)setError(orderResult.error.message); else setOrders((orderResult.data??[]).map((row:any)=>({...row,party_name:row.customer?.name??row.supplier?.name??"—"}))); if(noteResult.error)setError(c=>c||noteResult.error!.message); else setNotes((noteResult.data??[]) as Note[]); setLoading(false); },[type]);
 useEffect(()=>{setOrderId("");setLines([]);void load();},[load]);
 useEffect(()=>{ if(!orderId){setLines([]);return;} void(async()=>{setError("");const isSale=type==="sales_credit";const {data,error:lineError}=await supabase.from(isSale?"sales_order_lines":"purchase_order_lines").select(isSale?"id,item_id,godown_id,qty,unit_price,tax_percent,item:items(name)":"id,item_id,godown_id,qty,unit_cost,item:items(name)").eq("order_id",orderId).order("id");if(lineError){setError(lineError.message);return;}const ids=(data??[]).map((r:any)=>r.id);let returned=new Map<string,number>();if(ids.length){const {data:prior,error:priorError}=await supabase.from("return_note_lines").select("original_line_id,qty").in("original_line_id",ids);if(priorError){setError(priorError.message);return;}returned=(prior??[]).reduce((m:Map<string,number>,r:any)=>m.set(r.original_line_id,(m.get(r.original_line_id)??0)+Number(r.qty)),new Map());}const selected:any=orders.find(o=>o.id===orderId);setLines((data??[]).map((r:any)=>({id:r.id,item_id:r.item_id,godown_id:r.godown_id,qty:Number(r.qty),rate:Number(isSale?r.unit_price:r.unit_cost),tax_percent:Number(isSale?r.tax_percent:selected?.tax_percent??0),item_name:r.item?.name??"Unknown item",returned:returned.get(r.id)??0,returnQty:""})));})(); },[orderId,orders,type]);
 const totals=useMemo(()=>lines.reduce((s,l)=>{const q=Number(l.returnQty||0),net=q*l.rate;return{net:s.net+net,tax:s.tax+net*l.tax_percent/100};},{net:0,tax:0}),[lines]);

 async function postNote(){const selected=lines.filter(l=>Number(l.returnQty)>0);if(!orderId)return setError("Select the original posted invoice.");if(!reason.trim())return setError("Return reason is required.");if(!selected.length)return setError("Enter at least one return quantity.");const invalid=selected.find(l=>Number(l.returnQty)>l.qty-l.returned||!l.godown_id);if(invalid)return setError(`${invalid.item_name}: quantity exceeds remaining quantity or godown is missing.`);if(!window.confirm(`Post ${type==="sales_credit"?"Sales Credit Note":"Purchase Debit Note"} for ${money(totals.net+totals.tax)}?`))return;setPosting(true);setError("");setSuccess("");const {data,error:rpcError}=await supabase.rpc("create_and_post_return_note",{p_note_type:type,p_order_id:orderId,p_note_date:noteDate,p_reason:reason.trim(),p_lines:selected.map(l=>({line_id:l.id,qty:Number(l.returnQty)}))});if(rpcError)setError(rpcError.message);else{setSuccess(`${data.note_no} posted successfully.`);setReason("");setOrderId("");setLines([]);await load();}setPosting(false);}

 async function printNote(note:Note){setError("");const source=orders.find(o=>o.id===(note.sales_order_id??note.purchase_order_id));const [lineRes,companyRes]=await Promise.all([supabase.from("return_note_lines").select("qty,unit_rate,tax_percent,line_subtotal,tax_amount,line_total,item:items(name,hs_code,unit)").eq("note_id",note.id),supabase.from("company_settings").select("*").maybeSingle()]);if(lineRes.error)return setError(lineRes.error.message);const items:PrintItemRow[]=(lineRes.data??[]).map((l:any)=>({name:l.item?.name??"Item",description:"Return adjustment",qty:Number(l.qty),unitPrice:Number(l.unit_rate),lineTotal:Number(l.line_subtotal),taxPercent:Number(l.tax_percent||0),taxAmount:Number(l.tax_amount||0),hsCode:l.item?.hs_code??null,unit:l.item?.unit??null}));setPrintState({note,sourceNo:source?.order_no??"—",items,company:companyRes.data??{}});window.setTimeout(()=>{triggerPrint("#return-note-print-root");window.setTimeout(()=>setPrintState(null),300);},150);}

 if(loading)return <LoadingState/>;
 return <div className="space-y-4">
  <PageHeader title="Credit / Debit Notes" subtitle="Invoice-linked returns with automatic stock and accounting adjustment." action={<div className="flex items-center gap-2"><span data-navilo-standard-tools-host className="contents"/></div>}/>
  {error&&<ErrorBanner message={error}/>} {success&&<div className="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}
  <div className="card p-5" data-no-print data-no-export>
   <div className="mb-4 flex gap-2"><button className={type==="sales_credit"?"btn btn-primary":"btn btn-secondary"} onClick={()=>setType("sales_credit")}>Sales Credit Note</button><button className={type==="purchase_debit"?"btn btn-primary":"btn btn-secondary"} onClick={()=>setType("purchase_debit")}>Purchase Debit Note</button></div>
   <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Original posted invoice<SearchableSelect className="input mt-1 w-full" value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Select invoice</option>{orders.map(o=><option key={o.id} value={o.id}>{o.order_no} — {o.party_name} — {money(o.total)}</option>)}</SearchableSelect></label><label className="text-sm font-medium">Note date<input className="input mt-1 w-full" type="date" value={noteDate} onChange={e=>setNoteDate(e.target.value)}/></label><label className="text-sm font-medium">Mandatory reason<input className="input mt-1 w-full" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Damaged / rejected / rate correction"/></label></div>
   {orderId&&<div className="mt-5 overflow-x-auto"><table className="table"><thead><tr><th>Item</th><th className="text-right">Invoice Qty</th><th className="text-right">Already Returned</th><th className="text-right">Remaining</th><th className="text-right">Rate</th><th className="w-32 text-right">Return Qty</th></tr></thead><tbody>{lines.map((l,i)=><tr key={l.id}><td>{l.item_name}{!l.godown_id&&<div className="text-xs text-red-600">Godown missing</div>}</td><td className="text-right">{l.qty}</td><td className="text-right">{l.returned}</td><td className="text-right font-medium">{l.qty-l.returned}</td><td className="text-right">{money(l.rate)}</td><td><input className="input w-28 text-right" type="number" min="0" max={l.qty-l.returned} step="0.001" value={l.returnQty} onChange={e=>setLines(c=>c.map((x,n)=>n===i?{...x,returnQty:e.target.value}:x))}/></td></tr>)}</tbody></table><div className="mt-4 flex items-center justify-end gap-5"><div className="text-right text-sm"><div>Net: {money(totals.net)}</div><div>VAT: {money(totals.tax)}</div><div className="text-lg font-bold">Total: {money(totals.net+totals.tax)}</div></div><button className="btn btn-primary" disabled={posting} onClick={postNote}><RotateCcw size={16}/>{posting?"Posting...":"Post Return Note"}</button></div></div>}
  </div>
  <section className="card overflow-hidden" data-report-content data-navilo-customizable="true"><div className="border-b px-5 py-3"><div className="navilo-report-title font-semibold">{type==="sales_credit"?"Posted Sales Credit Notes":"Posted Purchase Debit Notes"}</div><div className="mt-1 text-xs text-slate-500">{notes.length} posted note{notes.length===1?"":"s"}</div></div><div className="overflow-x-auto"><table className="table"><thead><tr><th>Note</th><th>Date</th><th>Party</th><th>Type</th><th>Reason</th><th className="text-right">Total</th><th data-no-print data-no-export>Action</th></tr></thead><tbody>{notes.length?notes.map(note=><tr key={note.id}><td className="font-medium">{note.note_no}</td><td>{formatDate(note.note_date)}</td><td>{note.party_name}</td><td>{note.note_type==="sales_credit"?"Sales Credit":"Purchase Debit"}</td><td>{note.reason}</td><td className="text-right font-medium">{money(note.total)}</td><td data-no-print data-no-export><button className="btn btn-secondary" data-direct-print onClick={()=>void printNote(note)}><Printer size={15}/>Print Note</button></td></tr>):<tr><td colSpan={7} className="py-10 text-center text-slate-500">No posted return notes.</td></tr>}</tbody></table></div></section>
  {printState&&<div id="return-note-print-root" className="hidden print:block"><PrintLayout voucherTitle={printState.note.note_type==="sales_credit"?"Sales Credit Note":"Purchase Debit Note"} voucherNo={printState.note.note_no} voucherDate={printState.note.note_date} company={{name:printState.company.company_name??printState.company.name??"NAVILO",address:printState.company.address??"",phone:printState.company.phone??"",email:printState.company.email??"",taxId:printState.company.strn??printState.company.ntn??printState.company.tax_id??"",logoUrl:printState.company.logo_url??""}} party={{name:printState.note.party_name}} items={printState.items} chargeBreakdown={[]} itemsTotal={Number(printState.note.subtotal)} chargesTotal={0} taxAmount={Number(printState.note.tax_total)} showTaxSummary={Number(printState.note.tax_total)>0} grandTotal={Number(printState.note.total)} extraFields={[{label:"Original Invoice",value:printState.sourceNo},{label:"Reason",value:printState.note.reason},...(printState.note.fbr_invoice_no?[{label:"FBR Reference",value:printState.note.fbr_invoice_no}]:[])]} documentNotice="Posted adjustment document. Original invoice remains locked; accounting and stock entries are linked to this note." visibility={{showQrCode:false}}/></div>}
 </div>;
}
