import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, GitBranch, Loader2 } from "lucide-react";
import { Link } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import { formatDate } from "@/components/ui";

type LinkRow={id:string;source_type:string;source_id:string;target_type:string;target_id:string;relation_type:string;created_at:string};
type NodeRow={document_type:string;document_id:string;document_no:string;document_date:string;status:string};
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const route=(type:string,id:string)=>type==="sales_invoice"?`/sales/${id}`:type==="purchase_invoice"?`/purchase/${id}`:type==="journal_entry"?`/accounting/${id}`:type==="return_note"?"/accounting/returns":type==="gate_pass"?"/cutting/gate-pass":type==="order_book"?"/sales/order-book":null;

export default function DocumentTraceability({documentType,documentId}:{documentType:string;documentId:string}){
  const[links,setLinks]=useState<LinkRow[]>([]),[nodes,setNodes]=useState<NodeRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!documentId)return;setLoading(true);setError("");const l=await supabase.from("transaction_links").select("id,source_type,source_id,target_type,target_id,relation_type,created_at").or(`source_id.eq.${documentId},target_id.eq.${documentId}`).order("created_at");if(l.error){setError(l.error.message);setLoading(false);return;}const rows=(l.data||[]) as LinkRow[];setLinks(rows);const ids=[...new Set(rows.flatMap(x=>[x.source_id,x.target_id]))];if(ids.length){const n=await supabase.from("commercial_document_nodes").select("document_type,document_id,document_no,document_date,status").in("document_id",ids);if(n.error)setError(n.error.message);else setNodes((n.data||[]) as NodeRow[]);}else setNodes([]);setLoading(false);},[documentId]);
  useEffect(()=>{void load();},[load]);
  const nodeMap=useMemo(()=>new Map(nodes.map(n=>[`${n.document_type}:${n.document_id}`,n])),[nodes]);
  const describe=(type:string,id:string)=>nodeMap.get(`${type}:${id}`)||{document_type:type,document_id:id,document_no:id.slice(0,8),document_date:"",status:"linked"};
  return <section className="card mt-5 p-5"><div className="flex items-center gap-2"><GitBranch className="h-5 w-5 text-indigo-700"/><div><h2 className="font-bold text-slate-900">Document Chain / دستاویز سلسلہ</h2><p className="text-xs text-slate-500">Order, invoice, stock, return, payment and accounting evidence linked without changing posted records.</p></div></div>{loading?<div className="flex items-center justify-center py-8 text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading chain...</div>:error?<div className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>:!links.length?<div className="mt-4 rounded-lg border border-dashed p-5 text-center text-sm text-slate-500">No linked downstream or upstream document yet.</div>:<div className="mt-4 space-y-2">{links.map(x=>{const s=describe(x.source_type,x.source_id),t=describe(x.target_type,x.target_id),sr=route(s.document_type,s.document_id),tr=route(t.document_type,t.document_id);return <div key={x.id} className="grid items-center gap-2 rounded-lg border bg-slate-50 p-3 md:grid-cols-[1fr_auto_1fr]"><Doc node={s} href={sr} current={x.source_id===documentId&&x.source_type===documentType}/><div className="flex items-center justify-center gap-2 text-xs font-semibold text-indigo-700"><span>{label(x.relation_type)}</span><ArrowRight className="h-4 w-4"/></div><Doc node={t} href={tr} current={x.target_id===documentId&&x.target_type===documentType}/></div>})}</div>}</section>;
}
function Doc({node,href,current}:{node:NodeRow;href:string|null;current:boolean}){const body=<div className={`rounded-md p-2 ${current?"bg-indigo-50 ring-1 ring-indigo-200":"bg-white"}`}><div className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label(node.document_type)}{current?" · Current":""}</div><div className="font-semibold text-slate-900">{node.document_no||node.document_id.slice(0,8)}</div><div className="text-xs text-slate-500">{node.document_date?formatDate(node.document_date):""}{node.status?` · ${label(node.status)}`:""}</div></div>;return href?<Link to={href} className="block hover:opacity-80">{body}</Link>:body;}
