import { Children, Fragment, isValidElement, useEffect, useMemo, useRef, useState, type ChangeEvent, type ReactElement, type ReactNode, type SelectHTMLAttributes } from "react";
import { Check, ChevronDown, Search } from "lucide-react";

type FlatOption={value:string;label:string;disabled:boolean;group?:string};
type Props=SelectHTMLAttributes<HTMLSelectElement>&{children:ReactNode;searchPlaceholder?:string;emptyText?:string};

function nodeText(node:ReactNode):string{if(node==null||typeof node==="boolean")return"";if(typeof node==="string"||typeof node==="number")return String(node);if(Array.isArray(node))return node.map(nodeText).join("");if(isValidElement(node))return nodeText((node as ReactElement<any>).props?.children);return""}
function flattenOptions(children:ReactNode,group?:string):FlatOption[]{const out:FlatOption[]=[];Children.forEach(children,child=>{if(!isValidElement(child))return;const el=child as ReactElement<any>;if(el.type===Fragment){out.push(...flattenOptions(el.props.children,group));return}if(el.type==="optgroup"){out.push(...flattenOptions(el.props.children,String(el.props.label??"")));return}if(el.type==="option"){const raw=el.props.value??"";const explicit=el.props.label==null?"":String(el.props.label);const childLabel=nodeText(el.props.children).trim();out.push({value:String(raw),label:explicit.trim()||childLabel||String(raw),disabled:Boolean(el.props.disabled),group});return}if(el.props?.children)out.push(...flattenOptions(el.props.children,group))});return out}
function stripLeadingAccountCode(label:string){return label.replace(/^\s*[A-Z]{0,4}[-/]?\d{2,10}(?:[./-]\d+)?\s*(?:[-–—:|]\s*)+/,"").trim()||label}

export default function SearchableSelect({children,value,defaultValue,onChange,disabled,className="",searchPlaceholder="Type to search...",emptyText="No matching option",multiple,size,name,id,"aria-label":ariaLabel,...rest}:Props){
  if(multiple||(typeof size==="number"&&size>1))return <select {...rest} name={name} id={id} aria-label={ariaLabel} multiple={multiple} size={size} value={value} defaultValue={defaultValue} onChange={onChange} disabled={disabled} className={className}>{children}</select>;
  const options=useMemo(()=>flattenOptions(children),[children]);
  const controlled=value==null?undefined:String(value);
  const[internal,setInternal]=useState(controlled??(defaultValue==null?"":String(defaultValue)));
  const selectedValue=controlled??internal;
  const[open,setOpen]=useState(false),[query,setQuery]=useState(""),[activeIndex,setActiveIndex]=useState(0),[nearbyAccount,setNearbyAccount]=useState(false);
  const rootRef=useRef<HTMLDivElement|null>(null),buttonRef=useRef<HTMLButtonElement|null>(null),inputRef=useRef<HTMLInputElement|null>(null);
  useEffect(()=>{if(controlled!==undefined)setInternal(controlled)},[controlled]);
  const explicitAccount=useMemo(()=>{const h=[name,id,ariaLabel,searchPlaceholder].filter(Boolean).join(" ").toLowerCase();return h.includes("account")||h.includes("اکاؤنٹ")},[name,id,ariaLabel,searchPlaceholder]);
  useEffect(()=>{const host=rootRef.current;if(!host)return;const t=(host.parentElement?.querySelector("label")?.textContent??"").toLowerCase();setNearbyAccount(t.includes("account")||t.includes("اکاؤنٹ"))},[children]);
  const accountContext=explicitAccount||nearbyAccount;const visibleLabel=(label:string)=>accountContext?stripLeadingAccountCode(label):label;
  useEffect(()=>{const close=(e:MouseEvent)=>{if(!rootRef.current?.contains(e.target as Node)){setOpen(false);setQuery("")}};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
  const selected=useMemo(()=>options.find(o=>o.value===selectedValue)??options.find(o=>o.value==="")??null,[options,selectedValue]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return options.filter(o=>o.value!==""||!q).filter(o=>!q||`${o.label} ${visibleLabel(o.label)} ${o.group??""}`.toLowerCase().includes(q)).slice(0,150)},[options,query,accountContext]);
  const emit=(next:string)=>{if(!onChange)return;const target={value:next,name:name??"",id:id??""} as unknown as HTMLSelectElement;onChange({target,currentTarget:target} as ChangeEvent<HTMLSelectElement>)};
  const commit=(next:string)=>{const opt=options.find(o=>o.value===next);if(!opt||opt.disabled||disabled)return;setInternal(next);emit(next);setOpen(false);setQuery("");requestAnimationFrame(()=>buttonRef.current?.focus())};
  const openMenu=()=>{if(disabled)return;setOpen(v=>!v);setQuery("");const i=options.findIndex(o=>o.value===selectedValue&&!o.disabled);setActiveIndex(i>=0?i:Math.max(0,options.findIndex(o=>!o.disabled)));requestAnimationFrame(()=>inputRef.current?.focus())};
  const keyDown=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==="Escape"){e.preventDefault();setOpen(false);buttonRef.current?.focus();return}if(!filtered.length)return;if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();const d=e.key==="ArrowDown"?1:-1;let n=activeIndex;for(let i=0;i<filtered.length;i++){n=(n+d+filtered.length)%filtered.length;if(!filtered[n]?.disabled)break}setActiveIndex(n)}else if(e.key==="Enter"){e.preventDefault();const o=filtered[activeIndex]??filtered.find(x=>!x.disabled);if(o)commit(o.value)}};
  const display=selected?visibleLabel(selected.label):(selectedValue||"Select...");
  return <div ref={rootRef} className="relative min-w-0 w-full overflow-visible">
    <select {...rest} name={name} id={id} aria-label={ariaLabel} value={selectedValue} onChange={e=>{setInternal(e.target.value);onChange?.(e)}} disabled={disabled} className="sr-only" tabIndex={-1} aria-hidden="true">{children}</select>
    <button ref={buttonRef} type="button" disabled={disabled} onClick={openMenu} className={`${className} flex min-h-8 w-full items-center justify-between gap-2 text-left text-slate-900 disabled:cursor-not-allowed disabled:opacity-60`} aria-haspopup="listbox" aria-expanded={open}><span className={`min-w-0 flex-1 truncate ${selectedValue?"text-slate-900":"text-slate-500"}`}>{display}</span><ChevronDown className={`h-3.5 w-3.5 shrink-0 text-slate-400 transition-transform ${open?"rotate-180":""}`}/></button>
    {open&&<div className="absolute left-0 right-0 top-full z-[9999] mt-1 overflow-hidden rounded-md border border-slate-200 bg-white shadow-xl">
      <div className="border-b border-slate-100 p-2"><div className="flex h-8 items-center gap-2 rounded-md border border-slate-300 bg-white px-2 focus-within:border-blue-500 focus-within:ring-1 focus-within:ring-blue-500"><Search className="h-3.5 w-3.5 shrink-0 text-slate-400"/><input ref={inputRef} value={query} onChange={e=>{setQuery(e.target.value);setActiveIndex(0)}} onKeyDown={keyDown} placeholder={searchPlaceholder} className="min-w-0 flex-1 border-0 bg-transparent text-[13px] text-slate-900 outline-none placeholder:text-slate-400" autoComplete="off"/></div></div>
      <div role="listbox" className="max-h-56 overflow-auto p-1">{!filtered.length?<div className="px-3 py-4 text-center text-[12px] text-slate-500">{emptyText}</div>:filtered.map((o,i)=><button key={`${o.group??""}:${o.value}:${i}`} type="button" role="option" aria-selected={o.value===selectedValue} disabled={o.disabled} onMouseEnter={()=>setActiveIndex(i)} onMouseDown={e=>e.preventDefault()} onClick={()=>commit(o.value)} className={`flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-left text-[13px] ${i===activeIndex?"bg-blue-50 text-blue-700":"text-slate-700 hover:bg-slate-50"} disabled:cursor-not-allowed disabled:opacity-40`}><span className="min-w-0 flex-1">{o.group&&<span className="mr-1 text-[10px] font-semibold uppercase tracking-wide text-slate-400">{o.group} ·</span>}<span className="break-words">{visibleLabel(o.label)||o.value||"—"}</span></span>{o.value===selectedValue&&<Check className="h-3.5 w-3.5 shrink-0"/>}</button>)}</div>
    </div>}
  </div>
}
