import { useEffect,useState } from "react";import { Headphones,MessageCircle,Send,X } from "lucide-react";import { supabase } from "@/lib/supabase";import { useAuth } from "@/auth/AuthContext";
type Ticket={id:string;ticket_no:string;subject:string;category:string;priority:string;status:string;updated_at:string};
type Msg={id:string;body:string;is_owner_reply:boolean;created_at:string};
export default function SupportCenter({owner=false}:{owner?:boolean}){
 const{activeCompany}=useAuth();const[open,setOpen]=useState(owner),[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<Msg[]>([]),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[category,setCategory]=useState("issue"),[busy,setBusy]=useState(false);
 const load=async()=>{let q=supabase.from("support_tickets").select("id,ticket_no,subject,category,priority,status,updated_at").order("updated_at",{ascending:false}).limit(100);if(!owner&&activeCompany?.company_id)q=q.eq("company_id",activeCompany.company_id);const{data}=await q;setTickets((data??[]) as Ticket[])};
 useEffect(()=>{if(open||owner)void load()},[open,owner,activeCompany?.company_id]);
 useEffect(()=>{if(!selected){setMessages([]);return}void supabase.from("support_messages").select("id,body,is_owner_reply,created_at").eq("ticket_id",selected).order("created_at").then(({data})=>setMessages((data??[]) as Msg[]))},[selected]);
 const create=async()=>{if(!subject.trim()||!body.trim())return;setBusy(true);const{data,error}=await supabase.rpc("create_support_ticket",{p_subject:subject,p_category:category,p_message:body});setBusy(false);if(!error){setSubject("");setBody("");await load();setSelected(data as string)}};
 const reply=async()=>{if(!selected||!body.trim())return;setBusy(true);const{error}=await supabase.rpc("reply_support_ticket",{p_ticket_id:selected,p_message:body,p_status:owner?"waiting_for_client":null});setBusy(false);if(!error){setBody("");const{data}=await supabase.from("support_messages").select("id,body,is_owner_reply,created_at").eq("ticket_id",selected).order("created_at");setMessages((data??[]) as Msg[]);await load()}};
 const active=tickets.find(t=>t.id===selected);
 if(!open&&!owner)return <button type="button" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-[200] flex items-center gap-2 rounded-full bg-slate-900 px-4 py-3 text-sm font-bold text-white shadow-xl hover:bg-slate-800"><Headphones className="h-4 w-4"/>Support</button>;
 return <div className={owner?"rounded-xl border border-slate-200 bg-white shadow-sm":"fixed inset-0 z-[500] flex items-end justify-end bg-slate-950/20 p-4"}>
  <div className={owner?"":"flex h-[min(680px,90vh)] w-full max-w-4xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"}>
   <div className={owner?"grid min-h-[560px] grid-cols-[300px_1fr]":"contents"}>
    <aside className="border-r border-slate-200 bg-slate-50"><div className="flex items-center justify-between border-b p-3"><div className="font-black text-slate-900">Support {owner?"Inbox":"Center"}</div>{!owner&&<button onClick={()=>setOpen(false)}><X className="h-4 w-4"/></button>}</div>
     <div className="max-h-[600px] overflow-auto">{tickets.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={"block w-full border-b p-3 text-left hover:bg-white "+(selected===t.id?"bg-white":"")}><div className="flex justify-between gap-2 text-[11px] font-bold text-slate-500"><span>{t.ticket_no}</span><span>{t.status.replaceAll("_"," ")}</span></div><div className="mt-1 truncate text-sm font-bold text-slate-800">{t.subject}</div></button>)}</div>
    </aside>
    <main className="flex min-w-0 flex-col">
     {!active&&!owner?<div className="p-5"><h3 className="font-black text-slate-900">How can we help?</h3><div className="mt-3 grid grid-cols-2 gap-2"><input className="input col-span-2" placeholder="Subject" value={subject} onChange={e=>setSubject(e.target.value)}/><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="issue">Issue</option><option value="help">Help</option><option value="request">Request</option><option value="suggestion">Suggestion</option></select></div><textarea className="input mt-2 min-h-32 w-full" placeholder="Describe your issue or request…" value={body} onChange={e=>setBody(e.target.value)}/><button className="btn-primary mt-3" disabled={busy||!subject.trim()||!body.trim()} onClick={()=>void create()}><Send className="h-4 w-4"/>Submit Ticket</button></div>:active?<><header className="border-b p-4"><div className="text-xs font-bold text-slate-500">{active.ticket_no} · {active.status.replaceAll("_"," ")}</div><div className="font-black text-slate-900">{active.subject}</div></header><div className="flex-1 space-y-3 overflow-auto bg-slate-50 p-4">{messages.map(m=><div key={m.id} className={"max-w-[80%] rounded-xl p-3 text-sm shadow-sm "+(m.is_owner_reply?"ml-auto bg-slate-900 text-white":"bg-white text-slate-800")}><div>{m.body}</div><div className="mt-1 text-[10px] opacity-60">{new Date(m.created_at).toLocaleString()}</div></div>)}</div><div className="border-t bg-white p-3"><textarea className="input min-h-20 w-full" placeholder="Write a reply…" value={body} onChange={e=>setBody(e.target.value)}/><button className="btn-primary mt-2" disabled={busy||!body.trim()} onClick={()=>void reply()}><MessageCircle className="h-4 w-4"/>Reply</button></div></>:<div className="flex flex-1 items-center justify-center text-sm text-slate-400">Select a support ticket</div>}
    </main>
   </div>
  </div>
 </div>
}