import { useEffect,useState } from "react";
import { Bell, ChevronLeft, Headphones, Inbox, LifeBuoy, MessageCircle, Paperclip, Plus, Send, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/auth/AuthContext";

type Ticket={id:string;ticket_no:string;subject:string;category:string;priority:string;status:string;updated_at:string};
type Attachment={id:string;message_id:string;file_name:string;storage_path:string;mime_type:string|null;file_size:number};
type Msg={id:string;body:string;is_owner_reply:boolean;created_at:string};
const statusTone:Record<string,string>={open:"bg-blue-50 text-blue-700",in_progress:"bg-amber-50 text-amber-700",waiting_for_client:"bg-violet-50 text-violet-700",resolved:"bg-emerald-50 text-emerald-700",closed:"bg-slate-100 text-slate-600"};
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function SupportCenter({owner=false}:{owner?:boolean}){
 const{activeCompany}=useAuth();
 const[open,setOpen]=useState(owner),[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<string|null>(null);
 const[messages,setMessages]=useState<Msg[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]),[files,setFiles]=useState<File[]>([]),[unread,setUnread]=useState(0),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[category,setCategory]=useState("issue"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const loadUnread=async()=>{const{data}=await supabase.rpc("support_unread_summary");setUnread(Number((data as {count?:number}|null)?.count??0))};
 const load=async()=>{let q=supabase.from("support_tickets").select("id,ticket_no,subject,category,priority,status,updated_at").order("updated_at",{ascending:false}).limit(100);if(!owner&&activeCompany?.company_id)q=q.eq("company_id",activeCompany.company_id);const{data,error:e}=await q;if(e)setError("Support tickets could not be loaded.");else setTickets((data??[]) as Ticket[])};
 const loadMessages=async(id:string)=>{const[{data,error:e},{data:a}]=await Promise.all([supabase.from("support_messages").select("id,body,is_owner_reply,created_at").eq("ticket_id",id).order("created_at"),supabase.from("support_attachments").select("id,message_id,file_name,storage_path,mime_type,file_size").eq("ticket_id",id).order("created_at")]);if(e)setError("Conversation could not be loaded.");else{setMessages((data??[]) as Msg[]);setAttachments((a??[]) as Attachment[])}};
 useEffect(()=>{void loadUnread();const timer=window.setInterval(()=>{void loadUnread();if(open||owner)void load()},15000);return()=>window.clearInterval(timer)},[open,owner,activeCompany?.company_id]);
 useEffect(()=>{if(open||owner)void load()},[open,owner,activeCompany?.company_id]);
 useEffect(()=>{if(!selected){setMessages([]);return}void (async()=>{await supabase.rpc("mark_support_ticket_read",{p_ticket_id:selected});await Promise.all([loadMessages(selected),loadUnread()])})()},[selected]);
 const resetNew=()=>{setSelected(null);setSubject("");setBody("");setFiles([]);setCategory("issue");setError("")};
 const chooseFiles=(list:FileList|null)=>{const next=Array.from(list??[]);if(next.some(f=>f.size>10485760)){setError("Each attachment must be 10 MB or smaller.");return}setFiles(next.slice(0,5));setError("")};
 const uploadFiles=async(ticketId:string,messageId:string)=>{if(!files.length)return;const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Authentication required");for(const file of files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${user.id}/${ticketId}/${crypto.randomUUID()}-${safe}`;const{error:ue}=await supabase.storage.from("support-attachments").upload(path,file,{contentType:file.type||"application/octet-stream",upsert:false});if(ue)throw ue;const{error:re}=await supabase.rpc("register_support_attachment",{p_ticket_id:ticketId,p_message_id:messageId,p_file_name:file.name,p_storage_path:path,p_mime_type:file.type||"application/octet-stream",p_file_size:file.size});if(re){await supabase.storage.from("support-attachments").remove([path]);throw re}}setFiles([])};
 const openAttachment=async(a:Attachment)=>{const{data,error:e}=await supabase.storage.from("support-attachments").createSignedUrl(a.storage_path,60);if(e||!data?.signedUrl){setError("Attachment could not be opened.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const create=async()=>{if(!subject.trim()||!body.trim())return;setBusy(true);setError("");const{data,error:e}=await supabase.rpc("create_support_ticket_v2",{p_subject:subject,p_category:category,p_message:body});if(e){setBusy(false);setError("Ticket could not be submitted. Please try again.");return}try{const x=data as {ticket_id:string;message_id:string};await uploadFiles(x.ticket_id,x.message_id);setSubject("");setBody("");await load();setSelected(x.ticket_id)}catch{setError("Ticket was created, but an attachment could not be uploaded.")}finally{setBusy(false)}};
 const reply=async()=>{if(!selected||!body.trim())return;setBusy(true);setError("");const{data,error:e}=await supabase.rpc("reply_support_ticket_v2",{p_ticket_id:selected,p_message:body,p_status:owner?"waiting_for_client":null});if(e){setBusy(false);setError("Reply could not be sent. Please try again.");return}try{await uploadFiles(selected,data as string);setBody("");await Promise.all([loadMessages(selected),load(),loadUnread()])}catch{setError("Reply was sent, but an attachment could not be uploaded.")}finally{setBusy(false)}};
 const active=tickets.find(t=>t.id===selected);
 if(!open&&!owner)return <button type="button" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-[200] flex items-center gap-2 rounded-xl border border-slate-800 bg-slate-900 px-4 py-2.5 text-[13px] font-extrabold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-slate-800"><Headphones className="h-4 w-4"/>Support{unread>0&&<span className="ml-1 grid min-w-5 place-items-center rounded-full bg-red-500 px-1.5 py-0.5 text-[10px] font-black text-white">{unread>99?"99+":unread}</span>}</button>;

 const shell=<div className="flex h-full min-h-0 w-full overflow-hidden bg-white">
  <aside className="flex w-[260px] shrink-0 flex-col border-r border-slate-200 bg-slate-50/80">
   <div className="border-b border-slate-200 px-4 py-4">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-900 text-white"><Headphones className="h-4.5 w-4.5"/></div><div><div className="flex items-center gap-2 text-[15px] font-black text-slate-900">Support {owner?"Inbox":"Center"}{unread>0&&<span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2 py-0.5 text-[9px] font-black text-red-600"><Bell className="h-3 w-3"/>{unread} new</span>}</div><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{owner?"Client assistance":"NAVILO Help Desk"}</div></div></div>{!owner&&<button onClick={()=>setOpen(false)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-200 hover:text-slate-700"><X className="h-4 w-4"/></button>}</div>
    {!owner&&<button onClick={resetNew} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-3 py-2.5 text-xs font-extrabold text-white shadow-sm hover:bg-blue-700"><Plus className="h-4 w-4"/>New Support Ticket</button>}
   </div>
   <div className="flex items-center justify-between px-4 pb-2 pt-4"><span className="flex items-center gap-1.5 text-[11px] font-extrabold uppercase tracking-wider text-slate-500"><Inbox className="h-3.5 w-3.5"/>{owner?"All tickets":"My tickets"}</span><span className="rounded-full bg-slate-200 px-2 py-0.5 text-[10px] font-black text-slate-600">{tickets.length}</span></div>
   <div className="min-h-0 flex-1 overflow-y-auto px-2 pb-3">{tickets.length===0?<div className="m-2 rounded-lg border border-dashed border-slate-200 bg-white p-4 text-center text-xs text-slate-400">No support tickets yet.</div>:tickets.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={"mb-1 w-full rounded-lg border px-3 py-2.5 text-left transition "+(selected===t.id?"border-blue-200 bg-white shadow-sm":"border-transparent hover:bg-white")}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black tracking-wide text-slate-400">{t.ticket_no}</span><span className={"rounded-full px-2 py-0.5 text-[9px] font-extrabold "+(statusTone[t.status]??statusTone.closed)}>{label(t.status)}</span></div><div className="mt-1.5 truncate text-[12px] font-extrabold text-slate-800">{t.subject}</div><div className="mt-1 flex items-center justify-between text-[10px] font-medium text-slate-400"><span>{label(t.category)}</span><span>{new Date(t.updated_at).toLocaleDateString()}</span></div></button>)}</div>
   <div className="border-t border-slate-200 p-3"><div className="rounded-lg bg-blue-50 p-3"><div className="flex gap-2"><LifeBuoy className="mt-0.5 h-4 w-4 shrink-0 text-blue-600"/><div><div className="text-[11px] font-extrabold text-slate-800">Need assistance?</div><div className="mt-0.5 text-[10px] leading-4 text-slate-500">Create a ticket and keep the full conversation in one place.</div></div></div></div></div>
  </aside>
  <main className="flex min-w-0 flex-1 flex-col bg-white">
   {error&&<div className="mx-6 mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">{error}</div>}
   {!active&&!owner?<div className="flex-1 overflow-y-auto"><div className="mx-auto w-full max-w-3xl px-7 py-7">
    <div className="mb-6"><div className="text-[11px] font-extrabold uppercase tracking-[.16em] text-blue-600">NAVILO Support</div><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-900">How can we help?</h2><p className="mt-1 text-sm text-slate-500">Tell us what you need. Your request will stay linked to this support ticket.</p></div>
    <div className="rounded-xl border border-slate-200 bg-slate-50/40 p-5 shadow-sm">
     <div><label className="text-xs font-extrabold text-slate-700">Subject <span className="text-red-500">*</span></label><input maxLength={150} className="input mt-1.5 w-full bg-white" placeholder="Briefly describe your issue or request" value={subject} onChange={e=>setSubject(e.target.value)}/><div className="mt-1 text-right text-[10px] text-slate-400">{subject.length}/150</div></div>
     <div className="mt-3"><label className="text-xs font-extrabold text-slate-700">Category <span className="text-red-500">*</span></label><select className="input mt-1.5 w-full bg-white sm:w-64" value={category} onChange={e=>setCategory(e.target.value)}><option value="issue">Issue / Problem</option><option value="help">Help / Guidance</option><option value="request">Service Request</option><option value="suggestion">Suggestion</option></select></div>
     <div className="mt-4"><label className="text-xs font-extrabold text-slate-700">Message <span className="text-red-500">*</span></label><textarea maxLength={10000} className="input mt-1.5 min-h-40 w-full resize-y bg-white leading-6" placeholder="Describe the issue or request. Include what you were doing, what you expected, and what happened." value={body} onChange={e=>setBody(e.target.value)}/><div className="mt-1 text-right text-[10px] text-slate-400">{body.length}/10000</div></div>
     <div className="mt-3 flex flex-wrap items-center gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-extrabold text-slate-600 hover:bg-slate-50"><Paperclip className="h-3.5 w-3.5"/>Attach files<input type="file" multiple className="hidden" accept=".png,.jpg,.jpeg,.webp,.pdf,.txt,.csv,.xlsx,.xls,.docx" onChange={e=>chooseFiles(e.target.files)}/></label>{files.map(f=><span key={f.name+f.size} className="max-w-48 truncate rounded-md bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">{f.name}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-200 pt-4"><div className="text-[11px] text-slate-400">Required fields are marked with *</div><button className="btn-primary flex items-center gap-2 px-5 py-2.5" disabled={busy||!subject.trim()||!body.trim()} onClick={()=>void create()}><Send className="h-4 w-4"/>{busy?"Submitting…":"Submit Ticket"}</button></div>
    </div>
   </div></div>:active?<><header className="flex items-start justify-between gap-4 border-b border-slate-200 px-6 py-4"><div className="min-w-0"><button onClick={()=>setSelected(null)} className="mb-2 inline-flex items-center gap-1 text-[11px] font-bold text-slate-400 hover:text-slate-700"><ChevronLeft className="h-3.5 w-3.5"/>Back to tickets</button><div className="flex items-center gap-2"><span className="text-[11px] font-black text-blue-600">{active.ticket_no}</span><span className={"rounded-full px-2 py-0.5 text-[10px] font-extrabold "+(statusTone[active.status]??statusTone.closed)}>{label(active.status)}</span></div><h2 className="mt-1 truncate text-lg font-black text-slate-900">{active.subject}</h2><div className="mt-1 text-[11px] font-semibold text-slate-400">{label(active.category)} · Priority {label(active.priority)}</div></div></header>
    <div className="min-h-0 flex-1 overflow-y-auto bg-slate-50/70 px-6 py-5"><div className="mx-auto max-w-3xl space-y-3">{messages.map(m=><div key={m.id} className={"flex "+(m.is_owner_reply?"justify-end":"justify-start")}><div className={"max-w-[78%] rounded-xl border px-4 py-3 text-[13px] leading-5 shadow-sm "+(m.is_owner_reply?"border-slate-800 bg-slate-900 text-white":"border-slate-200 bg-white text-slate-700")}><div className="mb-1 text-[10px] font-extrabold uppercase tracking-wide opacity-60">{m.is_owner_reply?"NAVILO Support":"Client"}</div><div className="whitespace-pre-wrap">{m.body}</div>{attachments.filter(a=>a.message_id===m.id).map(a=><button key={a.id} onClick={()=>void openAttachment(a)} className="mt-2 flex max-w-full items-center gap-2 rounded-lg border border-current/15 bg-white/10 px-2.5 py-2 text-left text-[10px] font-bold hover:bg-white/20"><Paperclip className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{a.file_name}</span><span className="shrink-0 opacity-60">{(a.file_size/1024).toFixed(0)} KB</span></button>)}<div className="mt-2 text-[9px] font-medium opacity-50">{new Date(m.created_at).toLocaleString()}</div></div></div>)}</div></div>
    <div className="border-t border-slate-200 bg-white px-6 py-4"><div className="mx-auto max-w-3xl"><textarea maxLength={10000} className="input min-h-20 w-full resize-y" placeholder="Write a reply…" value={body} onChange={e=>setBody(e.target.value)}/><div className="mt-3 flex flex-wrap items-center gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-extrabold text-slate-600 hover:bg-slate-50"><Paperclip className="h-3.5 w-3.5"/>Attach files<input type="file" multiple className="hidden" accept=".png,.jpg,.jpeg,.webp,.pdf,.txt,.csv,.xlsx,.xls,.docx" onChange={e=>chooseFiles(e.target.files)}/></label>{files.map(f=><span key={f.name+f.size} className="max-w-48 truncate rounded-md bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">{f.name}</span>)}</div><div className="mt-2 flex items-center justify-between"><span className="text-[10px] text-slate-400">{body.length}/10000</span><button className="btn-primary flex items-center gap-2 px-4 py-2" disabled={busy||!body.trim()} onClick={()=>void reply()}><MessageCircle className="h-4 w-4"/>{busy?"Sending…":"Send Reply"}</button></div></div></div></>:<div className="grid flex-1 place-items-center bg-slate-50/50 p-8"><div className="text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-white text-slate-400 shadow-sm"><MessageCircle className="h-5 w-5"/></div><div className="mt-3 text-sm font-extrabold text-slate-700">Select a support ticket</div><div className="mt-1 text-xs text-slate-400">Choose a conversation from the inbox to view and reply.</div></div></div>}
  </main>
 </div>;

 if(owner)return <div className="h-[min(680px,calc(100vh-190px))] min-h-[520px] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{shell}</div>;
 return <div className="fixed inset-0 z-[500] flex items-center justify-center bg-slate-950/35 p-4 backdrop-blur-[1px]"><div className="h-[min(720px,92vh)] w-full max-w-5xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl">{shell}</div></div>;
}
