import { useEffect, useRef, useState } from "react";
import { Download, FileText, Languages, Printer, Settings2, Sheet, Table2 } from "lucide-react";
import { useLocation } from "react-router-dom";
import { useAuth } from "@/auth/AuthContext";
import { hasPermission, type ModuleKey } from "@/auth/permissions";
import { exportDomReportToCSV, exportDomReportToExcel, exportDomReportToWord, triggerPrint } from "@/lib/exportUtils";
import UserLanguagePreference from "@/components/UserLanguagePreference";

function cleanTitle(value:string){return value.replace(/\s*\/\s*[\u0600-\u06FF].*$/,"").replace(/[^a-z0-9]+/gi,"-").replace(/^-+|-+$/g,"").toLowerCase()||"navilo-export";}
function currentPageTitle(){const root=document.querySelector<HTMLElement>("[data-report-content]")||document.querySelector<HTMLElement>("#navilo-main-content")||document.body;return root.querySelector<HTMLElement>("h1,h2,.page-title")?.textContent?.replace(/\s+/g," ").trim()||document.title||"NAVILO";}
function currentExportRoot(){return document.querySelector<HTMLElement>("[data-report-content]")||document.querySelector<HTMLElement>("#navilo-main-content");}
function normalizeActionLabel(value:string){return value.replace(/\s+/g," ").replace(/\.(xlsx|xls|csv|docx|doc|pdf)\b/gi,"").replace(/[()]/g,"").trim().toLowerCase();}
function moduleForPath(pathname:string):ModuleKey{if(pathname==="/")return"dashboard";if(pathname.startsWith("/sales/report"))return"reports";if(pathname.startsWith("/sales/charges"))return"master";if(pathname.startsWith("/sales"))return"sales";if(pathname.startsWith("/purchase"))return"purchase";if(pathname.startsWith("/master-data"))return"master";if(pathname.startsWith("/godown"))return"inventory";if(pathname.startsWith("/production")||pathname.startsWith("/cutting"))return"production";if(pathname.startsWith("/transport"))return"transport";if(pathname.startsWith("/reports"))return"reports";if(pathname.startsWith("/accounting"))return"accounting";if(pathname.startsWith("/settings"))return"settings";return"dashboard";}
function isReportPath(pathname:string){return pathname.startsWith("/reports")||pathname.startsWith("/sales/report")||/\/(trial-balance|profit-loss|balance-sheet|cash-flow|day-book|audit-trail|ledgers|payroll|loans|vat-register|customer-invoice-statement|aging|register)/i.test(pathname);}
const duplicateGenericActions=new Set(["export","export excel","export csv","export word","excel","csv","word","pdf","print","print pdf","print / pdf","pdf / print","download excel","download csv","download word"]);

/** NAVILO-wide permission-aware tools. Reports get a dedicated compact accounting toolbar; forms keep simple actions. */
export default function UniversalDataTools(){
 const{pathname}=useLocation();const{activeCompany,activeBusinessUnit,isPlatformOwner}=useAuth();
 const[open,setOpen]=useState(false),[languageOpen,setLanguageOpen]=useState(false),[customizeOpen,setCustomizeOpen]=useState(false),[compact,setCompact]=useState(()=>localStorage.getItem("navilo-report-density")!=="standard");const ref=useRef<HTMLDivElement|null>(null);const reportMode=isReportPath(pathname),journalList=pathname==="/accounting";
 const role=activeBusinessUnit?.membership_role??activeCompany?.membership_role,module=moduleForPath(pathname),permissions=activeBusinessUnit?.permissions??activeCompany?.permissions;
 const canExport=isPlatformOwner||hasPermission(role,module,"export",permissions,false),canPrint=isPlatformOwner||hasPermission(role,module,"print",permissions,false);
 useEffect(()=>{const main=document.querySelector<HTMLElement>("#navilo-main-content");if(!main)return;if(reportMode)main.dataset.naviloScreenType="report";else delete main.dataset.naviloScreenType;return()=>delete main.dataset.naviloScreenType;},[reportMode,pathname]);
 useEffect(()=>{if(!reportMode)return;const root=currentExportRoot();if(root)root.dataset.naviloReportDensity=compact?"compact":"standard";localStorage.setItem("navilo-report-density",compact?"compact":"standard");},[reportMode,pathname,compact]);
 useEffect(()=>{const main=document.querySelector<HTMLElement>("#navilo-main-content");if(!main)return;const suppress=()=>main.querySelectorAll<HTMLElement>("button,a,[role='button']").forEach(el=>{if(el.closest("[data-navilo-global-data-tools]")||el.dataset.naviloKeepLocalAction==="true")return;const label=normalizeActionLabel(el.textContent||el.getAttribute("aria-label")||el.getAttribute("title")||"");if(duplicateGenericActions.has(label)){el.style.display="none";el.dataset.naviloDuplicateGlobalAction="true";}});suppress();const observer=new MutationObserver(suppress);observer.observe(main,{childList:true,subtree:true,characterData:true});return()=>observer.disconnect();},[pathname]);
 useEffect(()=>{if(!journalList)return;const style=document.createElement("style");style.textContent='button[title^="Print journal voucher"]{display:none!important}';document.head.appendChild(style);return()=>style.remove();},[journalList]);
 useEffect(()=>{if(!open&&!languageOpen&&!customizeOpen)return;const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node)){setOpen(false);setLanguageOpen(false);setCustomizeOpen(false);}};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[open,languageOpen,customizeOpen]);
 const exportCurrent=(type:"excel"|"csv"|"word")=>{if(!canExport)return;const root=currentExportRoot();if(!root)return;const title=currentPageTitle(),filename=cleanTitle(title);if(type==="excel")exportDomReportToExcel(filename,root,title);if(type==="csv")exportDomReportToCSV(filename,root,title);if(type==="word")exportDomReportToWord(filename,root,title);setOpen(false);};
 const printCurrent=()=>{if(!canPrint)return;setOpen(false);triggerPrint(document.querySelector("[data-report-content]")?"[data-report-content]":"#navilo-main-content");};
 const base=reportMode?"navilo-report-tool":"inline-flex h-9 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-[12px] font-bold text-slate-700 shadow-sm hover:bg-slate-50";
 return <div className={reportMode?"navilo-report-toolbar":"relative flex items-center gap-2"} ref={ref} data-no-print data-no-export data-navilo-global-data-tools>
  <div className="relative"><button type="button" onClick={()=>{setLanguageOpen(v=>!v);setOpen(false);setCustomizeOpen(false);}} className={base} title="My screen language"><Languages className="h-4 w-4"/><span className="hidden xl:inline">Language</span></button>{languageOpen&&<div className="absolute right-0 top-10 z-[80] w-[min(92vw,520px)] rounded-lg border border-slate-200 bg-white p-2 shadow-xl"><UserLanguagePreference/></div>}</div>
  {reportMode&&<div className="relative"><button type="button" onClick={()=>{setCustomizeOpen(v=>!v);setOpen(false);setLanguageOpen(false);}} className={base} title="Customize report"><Settings2 className="h-4 w-4"/><span>Customize</span></button>{customizeOpen&&<div className="absolute right-0 top-10 z-[75] w-64 rounded-lg border border-slate-200 bg-white p-3 text-xs shadow-xl"><div className="mb-2 font-bold text-slate-900">Report display</div><button type="button" onClick={()=>setCompact(v=>!v)} className="flex w-full items-center justify-between rounded-md border border-slate-200 px-3 py-2 text-left font-semibold text-slate-700 hover:bg-slate-50"><span>Row density</span><span className="text-blue-700">{compact?"Compact":"Comfortable"}</span></button><p className="mt-2 text-[11px] leading-4 text-slate-500">Report-specific filters and column controls remain on the report itself; export and print are centralized here.</p></div>}</div>}
  {canExport&&<div className="relative"><button type="button" onClick={()=>{setOpen(v=>!v);setLanguageOpen(false);setCustomizeOpen(false);}} className={base} title="Export current report"><Download className="h-4 w-4"/><span className="hidden xl:inline">Export</span></button>{open&&<div className="absolute right-0 top-10 z-[70] w-48 overflow-hidden rounded-lg border border-slate-200 bg-white py-1 shadow-xl"><button onClick={()=>exportCurrent("excel")} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-semibold hover:bg-slate-50"><Sheet className="h-4 w-4"/>Excel (.xlsx)</button><button onClick={()=>exportCurrent("csv")} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-semibold hover:bg-slate-50"><Table2 className="h-4 w-4"/>CSV (.csv)</button><button onClick={()=>exportCurrent("word")} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-semibold hover:bg-slate-50"><FileText className="h-4 w-4"/>Word (.doc)</button></div>}</div>}
  {canPrint&&<button type="button" onClick={printCurrent} className={base} title="Print preview or save as PDF"><Printer className="h-4 w-4"/><span className="hidden xl:inline">Print / PDF</span></button>}
 </div>;
}
