import { useEffect, useRef, useState } from "react";
import { Download, FileText, Languages, Printer, Settings2, Sheet, Table2 } from "lucide-react";
import { useLocation } from "react-router-dom";
import { useAuth } from "@/auth/AuthContext";
import { hasPermission, type ModuleKey } from "@/auth/permissions";
import { exportDomReportToCSV, exportDomReportToExcel, exportDomReportToWord, triggerPrint } from "@/lib/exportUtils";
import UserLanguagePreference from "@/components/UserLanguagePreference";

function cleanTitle(value: string) { return value.replace(/\s*\/\s*[\u0600-\u06FF].*$/, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "navilo-export"; }
function currentPageTitle() { const root=document.querySelector<HTMLElement>("[data-report-content]")||document.querySelector<HTMLElement>("#navilo-main-content")||document.body;return root.querySelector<HTMLElement>("h1,h2,.page-title")?.textContent?.replace(/\s+/g," ").trim()||document.title||"NAVILO"; }
function currentExportRoot() { return document.querySelector<HTMLElement>("[data-report-content]") || document.querySelector<HTMLElement>("#navilo-main-content"); }
function normalizeActionLabel(value:string){return value.replace(/\s+/g," ").replace(/\.(xlsx|xls|csv|docx|doc|pdf)\b/gi,"").replace(/[()]/g,"").trim().toLowerCase();}
function moduleForPath(pathname:string):ModuleKey{
  if(pathname==="/")return "dashboard"; if(pathname.startsWith("/sales/report"))return "reports"; if(pathname.startsWith("/sales/charges"))return "master"; if(pathname.startsWith("/sales"))return "sales"; if(pathname.startsWith("/purchase"))return "purchase"; if(pathname.startsWith("/master-data"))return "master"; if(pathname.startsWith("/godown"))return "inventory"; if(pathname.startsWith("/production")||pathname.startsWith("/cutting"))return "production"; if(pathname.startsWith("/transport"))return "transport"; if(pathname.startsWith("/reports"))return "reports"; if(pathname.startsWith("/accounting"))return "accounting"; if(pathname.startsWith("/settings"))return "settings"; return "dashboard";
}
function isReportPath(pathname:string){return pathname.startsWith("/reports")||pathname.startsWith("/sales/report")||/\/(trial-balance|profit-loss|balance-sheet|day-book|audit-trail|ledgers|aging|register)/i.test(pathname);}
const duplicateGenericActions=new Set(["export","export excel","export csv","export word","excel","csv","word","pdf","print","print pdf","print / pdf","pdf / print","download excel","download csv","download word"]);

/** Shared permission-aware NAVILO data tools. Financial/management reports use a compact professional toolbar. */
export default function UniversalDataTools() {
  const { pathname } = useLocation(); const {activeCompany,activeBusinessUnit,isPlatformOwner}=useAuth();
  const [open,setOpen]=useState(false),[languageOpen,setLanguageOpen]=useState(false),[compact,setCompact]=useState(()=>localStorage.getItem("navilo-report-density")!=="standard"); const ref=useRef<HTMLDivElement|null>(null); const journalList=pathname==="/accounting",reportMode=isReportPath(pathname);
  const role=activeBusinessUnit?.membership_role??activeCompany?.membership_role,module=moduleForPath(pathname),permissions=activeBusinessUnit?.permissions??activeCompany?.permissions;
  const canExport=isPlatformOwner||hasPermission(role,module,"export",permissions,false),canPrint=isPlatformOwner||hasPermission(role,module,"print",permissions,false);

  useEffect(()=>{if(!reportMode)return;const root=currentExportRoot();if(root)root.dataset.naviloReportDensity=compact?"compact":"standard";localStorage.setItem("navilo-report-density",compact?"compact":"standard");const style=document.createElement("style");style.dataset.naviloProfessionalReport="true";style.textContent='[data-navilo-report-density="compact"] table th,[data-navilo-report-density="compact"] table td{padding-top:.38rem!important;padding-bottom:.38rem!important;font-size:12px!important}';document.head.appendChild(style);return()=>style.remove();},[reportMode,pathname,compact]);
  useEffect(()=>{const main=document.querySelector<HTMLElement>("#navilo-main-content");if(!main)return;const suppress=()=>{main.querySelectorAll<HTMLElement>("button,a,[role='button']").forEach(element=>{if(element.closest("[data-navilo-global-data-tools]")||element.dataset.naviloKeepLocalAction==="true")return;const label=normalizeActionLabel(element.textContent||element.getAttribute("aria-label")||element.getAttribute("title")||"");if(duplicateGenericActions.has(label)){element.style.display="none";element.dataset.naviloDuplicateGlobalAction="true";}});};suppress();const observer=new MutationObserver(suppress);observer.observe(main,{childList:true,subtree:true,characterData:true});return()=>observer.disconnect();},[pathname]);
  useEffect(()=>{if(!journalList)return;const style=document.createElement("style");style.dataset.naviloJournalToolbar="true";style.textContent='button[title^="Print journal voucher"]{display:none!important}';document.head.appendChild(style);return()=>style.remove();},[journalList]);
  useEffect(()=>{if(!open&&!languageOpen)return;const close=(event:MouseEvent)=>{if(ref.current&&!ref.current.contains(event.target as Node)){setOpen(false);setLanguageOpen(false);}};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[open,languageOpen]);

  const exportCurrent=(type:"excel"|"csv"|"word")=>{if(!canExport)return;const root=currentExportRoot();if(!root)return;const title=currentPageTitle(),filename=cleanTitle(title);if(type==="excel")exportDomReportToExcel(filename,root,title);if(type==="csv")exportDomReportToCSV(filename,root,title);if(type==="word")exportDomReportToWord(filename,root,title);setOpen(false);};
  const printCurrent=()=>{if(!canPrint)return;setOpen(false);triggerPrint(document.querySelector("[data-report-content]")?"[data-report-content]":"#navilo-main-content");};
  const base=reportMode?"inline-flex h-8 items-center gap-1.5 rounded-md px-2 text-[11px] font-semibold text-slate-700 hover:bg-slate-100":"inline-flex h-9 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-[12px] font-bold text-slate-700 shadow-sm hover:bg-slate-50";

  return <div className={reportMode?"relative flex items-center gap-1 rounded-lg border border-slate-200 bg-white p-1 shadow-sm":"relative flex items-center gap-2"} ref={ref} data-no-print data-no-export data-navilo-global-data-tools>
    <div className="relative"><button type="button" onClick={()=>{setLanguageOpen(v=>!v);setOpen(false);}} className={base} title="My screen language"><Languages className="h-4 w-4"/><span className="hidden xl:inline">Language</span></button>{languageOpen&&<div className="absolute right-0 top-10 z-[80] w-[min(92vw,520px)] rounded-xl border border-slate-200 bg-white p-2 shadow-2xl"><UserLanguagePreference/></div>}</div>
    {reportMode&&<button type="button" onClick={()=>setCompact(v=>!v)} className={base} title="Customize report density"><Settings2 className="h-4 w-4"/><span className="hidden lg:inline">{compact?"Compact":"Comfortable"}</span></button>}
    {canExport&&<div className="relative"><button type="button" onClick={()=>{setOpen(v=>!v);setLanguageOpen(false);}} className={base} title="Export current report"><Download className="h-4 w-4"/><span className="hidden xl:inline">Export</span></button>{open&&<div className="absolute right-0 top-10 z-[70] w-48 overflow-hidden rounded-lg border border-slate-200 bg-white py-1 shadow-xl"><button type="button" onClick={()=>exportCurrent("excel")} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-semibold text-slate-700 hover:bg-slate-50"><Sheet className="h-4 w-4"/>Excel (.xlsx)</button><button type="button" onClick={()=>exportCurrent("csv")} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-semibold text-slate-700 hover:bg-slate-50"><Table2 className="h-4 w-4"/>CSV (.csv)</button><button type="button" onClick={()=>exportCurrent("word")} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-semibold text-slate-700 hover:bg-slate-50"><FileText className="h-4 w-4"/>Word (.doc)</button></div>}</div>}
    {canPrint&&<button type="button" onClick={printCurrent} className={base} title="Print preview or save as PDF"><Printer className="h-4 w-4"/><span className="hidden xl:inline">Print / PDF</span></button>}
  </div>;
}
