import SearchableSelect from "@/components/SearchableSelect";
import { useEffect, useState } from "react";
import { Languages, Loader2, Save } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { isAllowedBilingualPair, languageDisplayLabel, type LanguageMode } from "@/lib/languageConfig";
import { useCompanyLanguages } from "@/hooks/useCompanyLanguages";

export default function UserLanguagePreference(){
  const {languages,loading:languagesLoading}=useCompanyLanguages();
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState<string|null>(null);
  const [useCompanyDefault,setUseCompanyDefault]=useState(true),[mode,setMode]=useState<LanguageMode>("single"),[primary,setPrimary]=useState("en"),[secondary,setSecondary]=useState("ur");
  useEffect(()=>{void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return;}const{data,error}=await supabase.from("user_language_preferences").select("*").eq("user_id",user.id).maybeSingle();if(error)setError(error.message);if(data){setUseCompanyDefault(data.use_company_default!==false);setMode((data.screen_language_mode||"single") as LanguageMode);setPrimary(data.primary_language||"en");setSecondary(data.secondary_language||"ur");}setLoading(false);})();},[]);
  const enabledCodes=new Set(languages.map(language=>language.code));
  const safePrimary=enabledCodes.has(primary as never)?primary:(languages[0]?.code||"en");
  const secondaryOptions=languages.filter(language=>language.code!==safePrimary);
  const bilingualAvailable=secondaryOptions.length>0;
  const safeMode:LanguageMode=mode==="bilingual"&&bilingualAvailable?"bilingual":"single";
  const save=async()=>{if(!useCompanyDefault&&!enabledCodes.has(safePrimary as never)){setError("The selected language pack is not enabled for this company.");return;}if(!useCompanyDefault&&safeMode==="bilingual"&&!isAllowedBilingualPair(safePrimary,secondary)){setError("Select two different verified company languages.");return;}setSaving(true);setError(null);const{data:{user}}=await supabase.auth.getUser();if(!user){setError("No signed-in user.");setSaving(false);return;}const{error}=await supabase.from("user_language_preferences").upsert({user_id:user.id,use_company_default:useCompanyDefault,screen_language_mode:safeMode,primary_language:safePrimary,secondary_language:safeMode==="bilingual"?secondary:null,updated_at:new Date().toISOString()},{onConflict:"user_id"});setSaving(false);if(error)return setError(error.message);window.dispatchEvent(new Event("navilo-language-changed"));window.dispatchEvent(new Event("navilo:language-changed"));setSaved(true);setTimeout(()=>setSaved(false),2500);};
  if(loading||languagesLoading)return <section className="rounded-xl border border-slate-200 p-4"><Loader2 className="h-4 w-4 animate-spin"/></section>;
  return <section className="rounded-xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-center gap-2 font-bold"><Languages size={18}/>My Language Preference / User Override</div><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={useCompanyDefault} onChange={e=>setUseCompanyDefault(e.target.checked)}/>Use company default languages</label>{!useCompanyDefault&&<div className="mt-3 grid gap-3 md:grid-cols-3"><Select label="Mode" value={safeMode} onChange={v=>{const next=v==="bilingual"&&bilingualAvailable?"bilingual":"single";setMode(next);if(next==="bilingual"&&!secondaryOptions.some(x=>x.code===secondary))setSecondary(secondaryOptions[0].code);}} options={[["single","Single Language"],...(bilingualAvailable?[["bilingual","Bilingual / Two Languages"]]:[])]}/><Select label="Primary" value={safePrimary} onChange={v=>{setPrimary(v);if(mode==="bilingual"&&secondary===v)setSecondary(languages.find(x=>x.code!==v)?.code||v);}} options={languages.map(l=>[l.code,languageDisplayLabel(l.code)])}/>{safeMode==="bilingual"&&<Select label="Secondary" value={secondaryOptions.some(x=>x.code===secondary)?secondary:secondaryOptions[0].code} onChange={setSecondary} options={secondaryOptions.map(l=>[l.code,languageDisplayLabel(l.code)])}/>}</div>}{!useCompanyDefault&&<p className="mt-2 text-xs text-slate-600">This preference changes screens and on-screen reports for this user. Official document, report print, PDF and export language remains controlled by the company.</p>}{!bilingualAvailable&&!useCompanyDefault&&<p className="mt-2 text-xs font-medium text-amber-700">A second verified company language is required for bilingual mode.</p>}{error&&<div className="mt-2 text-xs font-semibold text-red-600">{error}</div>}{saved&&<div className="mt-2 text-xs font-semibold text-emerald-700">User language preference saved.</div>}<button type="button" onClick={()=>void save()} disabled={saving} className="btn btn-secondary mt-3">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save My Language</button></section>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="text-sm font-medium">{label}<SearchableSelect className="input mt-1 w-full" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</SearchableSelect></label>}
