import {useCallback,useEffect,useState} from "react";
import {AlertTriangle,Boxes,ClipboardCheck,Container,MapPin,Play,RefreshCw,Save,Truck} from "lucide-react";
import {PageHeader} from "@/components/ui";
import {supabase} from "@/lib/supabase";
import {useAuth} from "@/auth/AuthContext";

type Summary={company_id:string;business_unit_id:string;item_id:string;item_name:string;warehouse_id:string;godown_id:string;on_hand_qty:number;reserved_qty:number;available_qty:number;minimum_qty:number|null;reorder_qty:number|null;needs_reorder:boolean};
type PostingDoc={id:string;document_no:string;document_type:string;document_date:string;status:string;total_quantity:number;event_type:string|null;stock_movement_count:number|null;total_cost:number|null;accounting_status:string|null;journal_entry_id:string|null};
type Account={id:string;code:string;name:string;type:string};
type PostingSettings={id?:string;valuation_method:"fifo"|"weighted_average";inventory_account_id:string;wip_account_id:string;production_variance_account_id:string;scrap_account_id:string;auto_create_accounting_queue:boolean;is_active:boolean};
const emptySettings:PostingSettings={valuation_method:"weighted_average",inventory_account_id:"",wip_account_id:"",production_variance_account_id:"",scrap_account_id:"",auto_create_accounting_queue:true,is_active:true};
const n=(v:unknown)=>Number(v)||0;
export default function InventoryAdvanced(){
 const{activeCompany,activeBusinessUnit}=useAuth();const companyId=activeCompany?.company_id||"",businessUnitId=activeBusinessUnit?.business_unit_id||"";
 const[rows,setRows]=useState<Summary[]>([]),[docs,setDocs]=useState<PostingDoc[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[settings,setSettings]=useState<PostingSettings>(emptySettings),[counts,setCounts]=useState({lots:0,bins:0,holds:0,transit:0,counts:0}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[saved,setSaved]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const[s,p,a,g,l,b,h,t,c]=await Promise.all([
  supabase.from("inventory_control_summary").select("*").order("item_name"),
  supabase.from("inventory_posting_control_summary").select("*").order("document_date",{ascending:false}).limit(50),
  supabase.from("chart_of_accounts").select("id,code,name,type").eq("is_active",true).eq("is_group",false).eq("allow_manual_entries",true).order("code"),
  supabase.from("inventory_posting_settings").select("id,valuation_method,inventory_account_id,wip_account_id,production_variance_account_id,scrap_account_id,auto_create_accounting_queue,is_active").maybeSingle(),
  supabase.from("inventory_lots").select("id",{count:"exact",head:true}),
  supabase.from("warehouse_bins").select("id",{count:"exact",head:true}).eq("is_active",true),
  supabase.from("goods_receipt_inspections").select("id",{count:"exact",head:true}).in("status",["pending","inspecting"]),
  supabase.from("inventory_control_documents").select("id",{count:"exact",head:true}).eq("status","in_transit"),
  supabase.from("stock_counts").select("id",{count:"exact",head:true}).in("status",["counting","submitted"])
 ]);const failed=[s,p,a,g,l,b,h,t,c].find(x=>x.error);if(failed?.error)setError(failed.error.message);setRows((s.data||[]) as Summary[]);setDocs((p.data||[]) as PostingDoc[]);setAccounts((a.data||[]) as Account[]);setSettings(g.data?{...emptySettings,...g.data,inventory_account_id:g.data.inventory_account_id||"",wip_account_id:g.data.wip_account_id||"",production_variance_account_id:g.data.production_variance_account_id||"",scrap_account_id:g.data.scrap_account_id||""}:emptySettings);setCounts({lots:l.count||0,bins:b.count||0,holds:h.count||0,transit:t.count||0,counts:c.count||0});setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);const shortage=rows.filter(x=>x.needs_reorder);
 const cards=[["Tracked Lots / Heats",counts.lots,Container,"bg-blue-50 text-blue-700"],["Active Bins",counts.bins,MapPin,"bg-violet-50 text-violet-700"],["GRN Awaiting QC",counts.holds,ClipboardCheck,"bg-amber-50 text-amber-700"],["Transfers In Transit",counts.transit,Truck,"bg-cyan-50 text-cyan-700"],["Counts In Progress",counts.counts,Boxes,"bg-slate-100 text-slate-700"]] as const;
 const post=async(d:PostingDoc)=>{setBusy(d.id);setError("");const{error:e}=await supabase.rpc("post_inventory_control_document",{p_document_id:d.id});if(e)setError(e.message);else await load();setBusy("")};
 const account=async(d:PostingDoc)=>{setBusy("a:"+d.id);setError("");const q=await supabase.from("inventory_accounting_queue").select("id").eq("document_id",d.id).maybeSingle();if(q.error||!q.data?.id){setError(q.error?.message||"Accounting queue item was not found.");setBusy("");return}const{error:e}=await supabase.rpc("process_inventory_accounting_queue",{p_queue_id:q.data.id,p_post:true});if(e)setError(e.message);else{setSaved("Manufacturing journal posted to the General Ledger.");await load()}setBusy("")};
 const saveSettings=async()=>{if(!companyId||!businessUnitId){setError("Select an active company and business unit first.");return}if(!settings.inventory_account_id||!settings.wip_account_id){setError("Inventory and Work in Progress accounts are required.");return}setBusy("settings");setError("");setSaved("");const payload={company_id:companyId,business_unit_id:businessUnitId,valuation_method:settings.valuation_method,inventory_account_id:settings.inventory_account_id,wip_account_id:settings.wip_account_id,production_variance_account_id:settings.production_variance_account_id||null,scrap_account_id:settings.scrap_account_id||null,auto_create_accounting_queue:settings.auto_create_accounting_queue,is_active:settings.is_active,updated_at:new Date().toISOString()};const r=settings.id?await supabase.from("inventory_posting_settings").update(payload).eq("id",settings.id):await supabase.from("inventory_posting_settings").insert(payload);if(r.error)setError(r.error.message);else{setSaved("Manufacturing posting configuration saved for this business unit.");await load()}setBusy("")};
 const options=(type?:string)=>accounts.filter(a=>!type||a.type===type).map(a=><option key={a.id} value={a.id} data-search={a.code}>{a.name}</option>);
 return <div className="space-y-5"><PageHeader title="Inventory Advanced Controls" subtitle="Lot & heat traceability · reservations · QC · transfers · stock counts · valuation"/>
  <div className="flex justify-end"><button className="btn-secondary" disabled={loading} onClick={()=>void load()}><RefreshCw className={"h-4 w-4 "+(loading?"animate-spin":"")}/>Refresh</button></div>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {saved&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{saved}</div>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon,tone])=><div key={label} className="rounded-xl border bg-white p-4 shadow-sm"><div className={"mb-3 flex h-9 w-9 items-center justify-center rounded-lg "+tone}><Icon className="h-5 w-5"/></div><div className="text-2xl font-black">{value}</div><div className="text-xs font-semibold text-slate-500">{label}</div></div>)}</div>
  <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4"><h2 className="font-bold">Manufacturing Posting Configuration</h2><p className="text-xs text-slate-500">Company and business-unit specific valuation and ledger mappings. These settings never apply to another customer.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-semibold text-slate-600">Valuation<select className="input mt-1 w-full" value={settings.valuation_method} onChange={e=>setSettings({...settings,valuation_method:e.target.value as PostingSettings["valuation_method"]})}><option value="weighted_average">Weighted average</option><option value="fifo">FIFO</option></select></label><label className="text-xs font-semibold text-slate-600">Inventory Account<select className="input mt-1 w-full" value={settings.inventory_account_id} onChange={e=>setSettings({...settings,inventory_account_id:e.target.value})}><option value="">Select account</option>{options("asset")}</select></label><label className="text-xs font-semibold text-slate-600">Work in Progress<select className="input mt-1 w-full" value={settings.wip_account_id} onChange={e=>setSettings({...settings,wip_account_id:e.target.value})}><option value="">Select account</option>{options("asset")}</select></label><label className="text-xs font-semibold text-slate-600">Production Variance<select className="input mt-1 w-full" value={settings.production_variance_account_id} onChange={e=>setSettings({...settings,production_variance_account_id:e.target.value})}><option value="">Optional</option>{options("expense")}</select></label><label className="text-xs font-semibold text-slate-600">Scrap / Yield Loss<select className="input mt-1 w-full" value={settings.scrap_account_id} onChange={e=>setSettings({...settings,scrap_account_id:e.target.value})}><option value="">Optional</option>{options("expense")}</select></label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.auto_create_accounting_queue} onChange={e=>setSettings({...settings,auto_create_accounting_queue:e.target.checked})}/>Create accounting queue automatically</label><button className="btn-primary" disabled={busy==="settings"} onClick={()=>void saveSettings()}><Save className="h-4 w-4"/>{busy==="settings"?"Saving...":"Save Configuration"}</button></div></section>
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b px-4 py-3"><AlertTriangle className={shortage.length?"text-amber-600":"text-emerald-600"}/><div><h2 className="font-bold">Availability & Reorder Control</h2><p className="text-xs text-slate-500">{shortage.length} location(s) at or below minimum stock</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Item</th><th className="p-3 text-right">On hand</th><th className="p-3 text-right">Reserved</th><th className="p-3 text-right">Available</th><th className="p-3 text-right">Minimum</th><th className="p-3 text-right">Reorder Qty</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.item_id+":"+r.warehouse_id+":"+r.godown_id+":"+i} className="border-t"><td className="p-3 font-bold">{r.item_name}</td><td className="p-3 text-right tabular-nums">{n(r.on_hand_qty).toLocaleString()}</td><td className="p-3 text-right tabular-nums">{n(r.reserved_qty).toLocaleString()}</td><td className="p-3 text-right tabular-nums">{n(r.available_qty).toLocaleString()}</td><td className="p-3 text-right tabular-nums">{r.minimum_qty==null?"—":n(r.minimum_qty).toLocaleString()}</td><td className="p-3 text-right tabular-nums">{r.reorder_qty==null?"—":n(r.reorder_qty).toLocaleString()}</td><td className="p-3"><span className={"rounded-full px-2 py-1 text-xs font-bold "+(r.needs_reorder?"bg-amber-100 text-amber-800":"bg-emerald-100 text-emerald-800")}>{r.needs_reorder?"Reorder":"Healthy"}</span></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-400">No scoped stock rows available.</td></tr>}</tbody></table></div></section>
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b px-4 py-3"><h2 className="font-bold">Controlled Posting Queue</h2><p className="text-xs text-slate-500">Approved documents post stock once; accounting is created and posted through the controlled queue.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Document</th><th className="p-3">Type</th><th className="p-3">Status</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Cost</th><th className="p-3">Accounting</th><th className="p-3"></th></tr></thead><tbody>{docs.map(d=><tr key={d.id} className="border-t"><td className="p-3 font-bold">{d.document_no}<div className="text-xs font-normal text-slate-400">{d.document_date}</div></td><td className="p-3 capitalize">{d.document_type.replaceAll("_"," ")}</td><td className="p-3 capitalize">{d.status.replaceAll("_"," ")}</td><td className="p-3 text-right tabular-nums">{n(d.total_quantity).toLocaleString()}</td><td className="p-3 text-right tabular-nums">{d.total_cost==null?"—":n(d.total_cost).toLocaleString()}</td><td className="p-3 capitalize">{d.accounting_status?.replaceAll("_"," ")||"—"}</td><td className="p-3 text-right"><div className="flex justify-end gap-2">{["approved","in_transit"].includes(d.status)&&<button className="btn-primary h-8" disabled={busy===d.id} onClick={()=>void post(d)}><Play className="h-3.5 w-3.5"/>{d.status==="in_transit"?"Receive":"Post Stock"}</button>}{["ready","journal_created"].includes(d.accounting_status||"")&&<button className="btn-secondary h-8" disabled={busy==="a:"+d.id} onClick={()=>void account(d)}>{busy==="a:"+d.id?"Posting...":"Post Journal"}</button>}</div></td></tr>)}{!loading&&!docs.length&&<tr><td colSpan={7} className="p-8 text-center text-slate-400">No advanced inventory documents yet.</td></tr>}</tbody></table></div></section>
 </div>
}
