import { useEffect,useState } from "react";
import { CreditCard,FileText,Loader2,Plus } from "lucide-react";
import SearchableSelect from "@/components/SearchableSelect";
import { supabase } from "@/lib/supabase";

type Invoice={id:string;invoice_number:string;status:string;issue_date:string;due_date:string;currency_code:string;subtotal:number;tax_amount:number;total_amount:number;paid_amount:number;notes:string|null};
const today=()=>new Date().toISOString().slice(0,10);
const nextMonth=()=>{const d=new Date();d.setDate(d.getDate()+30);return d.toISOString().slice(0,10)};
export default function BillingLedgerControl({companyId}:{companyId:string}){
 const[rows,setRows]=useState<Invoice[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const[invoice,setInvoice]=useState({invoice_number:"",issue_date:today(),due_date:nextMonth(),currency_code:"USD",subtotal:"0",tax_amount:"0",notes:""});
 const[payment,setPayment]=useState({invoice_id:"",amount:"",method:"bank_transfer",reference:""});
 const load=async()=>{const{data,error}=await supabase.from("subscription_invoices").select("id,invoice_number,status,issue_date,due_date,currency_code,subtotal,tax_amount,total_amount,paid_amount,notes").eq("company_id",companyId).order("issue_date",{ascending:false});if(error)throw error;setRows((data??[]) as Invoice[])};
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[companyId]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await fn();await load();setMessage("Billing record saved successfully.")}catch(e){setMessage(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 const createInvoice=()=>run(async()=>{const{error}=await supabase.from("subscription_invoices").insert({company_id:companyId,...invoice,subtotal:Number(invoice.subtotal)||0,tax_amount:Number(invoice.tax_amount)||0,status:"issued"});if(error)throw error;setInvoice({invoice_number:"",issue_date:today(),due_date:nextMonth(),currency_code:invoice.currency_code,subtotal:"0",tax_amount:"0",notes:""})});
 const recordPayment=()=>run(async()=>{const target=rows.find(x=>x.id===payment.invoice_id);if(!target)throw new Error("Select an invoice.");const amount=Number(payment.amount);if(!amount||amount<=0)throw new Error("Enter a valid payment amount.");if(amount>Number(target.total_amount)-Number(target.paid_amount)+0.005)throw new Error("Payment cannot exceed invoice balance.");const{error}=await supabase.from("subscription_payments").insert({company_id:companyId,invoice_id:target.id,amount,currency_code:target.currency_code,method:payment.method,reference:payment.reference||null});if(error)throw error;setPayment({invoice_id:"",amount:"",method:"bank_transfer",reference:""})});
 const open=rows.filter(x=>!["paid","void"].includes(x.status));
 return <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-start gap-2"><CreditCard className="h-5 w-5 text-emerald-700"/><div><h2 className="font-semibold">Billing & Payment Ledger</h2><p className="text-xs text-slate-500">Issue subscription invoices and record verified payments. Balances and payment status update at database level.</p></div></div>{message&&<div className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-xs">{message}</div>}
 <div className="mt-4 rounded-xl border p-3"><div className="flex items-center gap-2 text-sm font-bold"><FileText className="h-4 w-4"/>Issue Invoice</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="Invoice number" value={invoice.invoice_number} onChange={e=>setInvoice({...invoice,invoice_number:e.target.value})}/><input className="input" type="date" value={invoice.issue_date} onChange={e=>setInvoice({...invoice,issue_date:e.target.value})}/><input className="input" type="date" value={invoice.due_date} onChange={e=>setInvoice({...invoice,due_date:e.target.value})}/><input className="input" maxLength={3} placeholder="Currency" value={invoice.currency_code} onChange={e=>setInvoice({...invoice,currency_code:e.target.value.toUpperCase()})}/><input className="input" type="number" min="0" step="0.01" placeholder="Subtotal" value={invoice.subtotal} onChange={e=>setInvoice({...invoice,subtotal:e.target.value})}/><input className="input" type="number" min="0" step="0.01" placeholder="Tax" value={invoice.tax_amount} onChange={e=>setInvoice({...invoice,tax_amount:e.target.value})}/><input className="input lg:col-span-2" placeholder="Notes" value={invoice.notes} onChange={e=>setInvoice({...invoice,notes:e.target.value})}/></div><button className="btn-primary mt-3" disabled={busy||!invoice.invoice_number.trim()} onClick={()=>void createInvoice()}><Plus className="h-4 w-4"/>Issue Invoice</button></div>
 <div className="mt-4 rounded-xl border p-3"><div className="text-sm font-bold">Record Payment</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><SearchableSelect className="input" value={payment.invoice_id} onChange={e=>setPayment({...payment,invoice_id:e.target.value})}><option value="">Select open invoice</option>{open.map(x=><option key={x.id} value={x.id}>{x.invoice_number} · {x.currency_code} {(Number(x.total_amount)-Number(x.paid_amount)).toFixed(2)}</option>)}</SearchableSelect><input className="input" type="number" min="0.01" step="0.01" placeholder="Amount" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><SearchableSelect className="input" value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="bank_transfer">Bank Transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="cheque">Cheque</option><option value="manual">Other / Manual</option></SearchableSelect><input className="input" placeholder="Reference" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></div><button className="btn-primary mt-3" disabled={busy||!payment.invoice_id} onClick={()=>void recordPayment()}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<CreditCard className="h-4 w-4"/>}Record Payment</button></div>
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b text-slate-500"><tr><th className="p-2">Invoice</th><th className="p-2">Issued / Due</th><th className="p-2">Status</th><th className="p-2 text-right">Total</th><th className="p-2 text-right">Paid</th><th className="p-2 text-right">Balance</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-b"><td className="p-2 font-semibold">{x.invoice_number}</td><td className="p-2">{x.issue_date} / {x.due_date}</td><td className="p-2 capitalize">{x.status.replace(/_/g," ")}</td><td className="p-2 text-right">{x.currency_code} {Number(x.total_amount).toFixed(2)}</td><td className="p-2 text-right">{Number(x.paid_amount).toFixed(2)}</td><td className="p-2 text-right font-bold">{(Number(x.total_amount)-Number(x.paid_amount)).toFixed(2)}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-4 text-center text-slate-400">No subscription invoices yet.</td></tr>}</tbody></table></div>
 </section>;
}
