import { useCallback,useEffect,useMemo,useState } from "react";
import { Building2,Loader2,Plus } from "lucide-react";
import SearchableSelect from "@/components/SearchableSelect";
import { supabase } from "@/lib/supabase";
import { invokeEdgeFunction } from "@/lib/invokeEdgeFunction";

type Unit={id:string;name:string;code:string;is_active:boolean};
type Branch={id:string;business_unit_id:string;name:string;code:string;location_type:string;is_active:boolean};
type Limits={max_branches?:number|null};

export default function BranchControl({companyId}:{companyId:string}){
 const[units,setUnits]=useState<Unit[]>([]),[branches,setBranches]=useState<Branch[]>([]),[limit,setLimit]=useState<number|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const[unitId,setUnitId]=useState(""),[name,setName]=useState(""),[code,setCode]=useState(""),[type,setType]=useState("branch");
 const[editingId,setEditingId]=useState<string|null>(null),[editName,setEditName]=useState(""),[editCode,setEditCode]=useState(""),[editType,setEditType]=useState("branch");
 const load=useCallback(async()=>{setLoading(true);setError("");const[u,b,l]=await Promise.all([supabase.from("business_units").select("id,name,code,is_active").eq("company_id",companyId).order("is_default",{ascending:false}).order("name"),supabase.from("operating_locations").select("id,business_unit_id,name,code,location_type,is_active").eq("company_id",companyId).order("name"),supabase.rpc("company_resource_limits",{p_company_id:companyId})]);const e=u.error||b.error||l.error;if(e)setError(e.message);const next=(u.data??[]) as Unit[];setUnits(next);setBranches((b.data??[]) as Branch[]);setLimit(Number.isFinite(Number((l.data as Limits|null)?.max_branches))?Number((l.data as Limits).max_branches):null);setUnitId(x=>next.some(v=>v.id===x)?x:(next.find(v=>v.is_active)?.id??""));setLoading(false)},[companyId]);
 useEffect(()=>{void load()},[load]);
 const activeCount=useMemo(()=>branches.filter(x=>x.is_active).length,[branches]);
 const create=async()=>{if(!unitId||!name.trim()||!code.trim()){setError("Business unit, branch name and branch code are required.");return}setSaving(true);setError("");try{const{error:e}=await supabase.from("operating_locations").insert({company_id:companyId,business_unit_id:unitId,name:name.trim(),code:code.trim().toUpperCase(),location_type:type,is_active:true});if(e)throw e;setName("");setCode("");setType("branch");await load()}catch(e){setError(e instanceof Error?e.message:"Could not create branch.")}finally{setSaving(false)}};
 const startEdit=(branch:Branch)=>{setEditingId(branch.id);setEditName(branch.name);setEditCode(branch.code);setEditType(branch.location_type);setError("")};
 const cancelEdit=()=>{setEditingId(null);setEditName("");setEditCode("");setEditType("branch")};
 const saveEdit=async(branch:Branch)=>{if(!editName.trim()||!editCode.trim()){setError("Branch name and branch code are required.");return}setSaving(true);setError("");try{const{error:e}=await supabase.from("operating_locations").update({name:editName.trim(),code:editCode.trim().toUpperCase(),location_type:editType}).eq("id",branch.id);if(e)throw e;await load();cancelEdit()}catch(e){setError(e instanceof Error?e.message:"Could not update branch.")}finally{setSaving(false)}};
 const removeBranch=async(branch:Branch)=>{if(!window.confirm(`Permanently remove unused branch "${branch.name}"? This is blocked if the branch is referenced.`))return;setSaving(true);setError("");try{await invokeEdgeFunction("platform-admin",{action:"remove_unused_branch",company_id:companyId,branch_id:branch.id});await load()}catch(e){setError(e instanceof Error?e.message:"Could not remove branch.")}finally{setSaving(false)}};
 const toggle=async(branch:Branch)=>{setSaving(true);setError("");try{const{error:e}=await supabase.from("operating_locations").update({is_active:!branch.is_active}).eq("id",branch.id);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Could not update branch.")}finally{setSaving(false)}};
 if(loading)return <section className="rounded-xl border bg-white p-4"><Loader2 className="h-5 w-5 animate-spin"/></section>;
 return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-blue-700"/><div><h2 className="font-semibold text-slate-900">Branches / Operating Locations</h2><p className="text-xs text-slate-500">Branches belong to one business unit. Company admins may manage branches only inside the owner-set branch limit.</p></div></div><div className="rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-600">Active branches <strong>{activeCount}</strong> / <strong>{limit??"Unlimited"}</strong></div></div>{error&&<div className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><SearchableSelect className="input" value={unitId} onChange={e=>setUnitId(e.target.value)}>{units.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id} data-search={x.code}>{x.name}</option>)}</SearchableSelect><input className="input" placeholder="Branch name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Branch code" value={code} onChange={e=>setCode(e.target.value)}/><SearchableSelect className="input" value={type} onChange={e=>setType(e.target.value)}><option value="branch">Branch</option><option value="factory">Factory</option><option value="office">Office</option><option value="yard">Yard</option><option value="site">Site</option></SearchableSelect><button className="btn-primary" disabled={saving||!unitId||(limit!==null&&activeCount>=limit)} onClick={()=>void create()}><Plus className="h-4 w-4"/>Add Branch</button></div>
 <div className="mt-4 space-y-2">{branches.map(branch=>{const unit=units.find(x=>x.id===branch.business_unit_id),editing=editingId===branch.id;return <div key={branch.id} className="rounded-lg border border-slate-200 px-3 py-2">{editing?<div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-semibold text-slate-700">Branch Name<input className="input mt-1 w-full" value={editName} onChange={e=>setEditName(e.target.value)}/></label><label className="text-xs font-semibold text-slate-700">Branch Code<input className="input mt-1 w-full" value={editCode} onChange={e=>setEditCode(e.target.value.toUpperCase())}/></label><label className="text-xs font-semibold text-slate-700">Location Type<SearchableSelect className="input mt-1 w-full" value={editType} onChange={e=>setEditType(e.target.value)}><option value="branch">Branch</option><option value="factory">Factory</option><option value="office">Office</option><option value="yard">Yard</option><option value="site">Site</option></SearchableSelect></label></div><div className="mt-3 flex gap-2"><button className="btn-primary" disabled={saving} onClick={()=>void saveEdit(branch)}>Save Changes</button><button className="btn-secondary" disabled={saving} onClick={cancelEdit}>Cancel</button></div></div>:<div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-semibold text-slate-900">{branch.name}</div><div className="text-xs text-slate-500">{unit?.name??"Unknown business"} · {branch.location_type} · {branch.is_active?"Active":"Disabled"}</div></div><div className="flex gap-2"><button className="btn-secondary h-8" disabled={saving||editingId!==null} onClick={()=>startEdit(branch)}>Edit</button><button className="btn-secondary h-8" disabled={saving||editingId!==null} onClick={()=>void toggle(branch)}>{branch.is_active?"Disable":"Enable"}</button><button className="btn-secondary h-8" disabled={saving||editingId!==null} onClick={()=>void removeBranch(branch)}>Remove</button></div></div>}</div>})}{branches.length===0&&<div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-500">No branches configured yet.</div>}</div>
 </section>;
}
