import { useEffect,useMemo,useState } from "react";
import { CheckCircle2,ChevronLeft,ChevronRight,Loader2,Rocket } from "lucide-react";
import SearchableSelect from "@/components/SearchableSelect";
import { supabase } from "@/lib/supabase";
import { invokeEdgeFunction } from "@/lib/invokeEdgeFunction";

type Plan={id:string;name:string;billing_cycle:string;price:number;currency_code:string;trial_days:number;max_users:number;max_business_units:number|null;max_branches:number|null;module_defaults:string[]};
const MODULES=["dashboard","master","sales","purchase","inventory","production","transport","accounting","reports","settings"];
const LABEL:Record<string,string>={dashboard:"Dashboard",master:"Master Data",sales:"Sales",purchase:"Purchase",inventory:"Inventory",production:"Production",transport:"Transport",accounting:"Accounting",reports:"Reports",settings:"Settings"};
const initial={name:"",code:"",owner_name:"",owner_email:"",password:"",contact_phone:"",address:"",plan_id:"",status:"trial",expires_at:"",business_unit_name:"",business_unit_code:"",business_unit_type:"custom",branch_name:"Head Office",branch_code:"HO",notes:""};

export default function CustomerOnboardingWizard({onComplete}:{onComplete:()=>Promise<void>|void}){
 const[step,setStep]=useState(1),[plans,setPlans]=useState<Plan[]>([]),[form,setForm]=useState(initial),[modules,setModules]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void supabase.from("subscription_plans").select("id,name,billing_cycle,price,currency_code,trial_days,max_users,max_business_units,max_branches,module_defaults").eq("is_active",true).order("price").then(({data,error})=>{if(error){setMessage(error.message);return}const rows=(data??[]) as Plan[];setPlans(rows);if(rows[0]){setForm(v=>({...v,plan_id:rows[0].id}));setModules((rows[0].module_defaults||[]).filter(key=>key!=="transport"))}})},[]);
 const plan=useMemo(()=>plans.find(p=>p.id===form.plan_id),[plans,form.plan_id]);
 const update=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 const valid=step===1?!!(form.name.trim()&&form.code.trim()&&form.owner_email.trim()&&form.password.length>=8):step===2?!!(form.plan_id&&form.expires_at):!!(form.business_unit_name.trim()&&form.business_unit_code.trim()&&form.branch_name.trim()&&form.branch_code.trim()&&modules.length);
 const choosePlan=(id:string)=>{const next=plans.find(p=>p.id===id);update("plan_id",id);if(next){setModules((next.module_defaults||[]).filter(key=>form.business_unit_type==="transport"?key!=="production":key!=="transport"));const d=new Date();d.setDate(d.getDate()+(form.status==="trial"?next.trial_days:(next.billing_cycle==="yearly"?365:30)));update("expires_at",d.toISOString().slice(0,10))}};
 const submit=async()=>{setBusy(true);setMessage("");try{await invokeEdgeFunction("platform-admin",{action:"onboard_company",...form,code:form.code.trim().toUpperCase(),business_unit_code:form.business_unit_code.trim().toUpperCase(),branch_code:form.branch_code.trim().toUpperCase(),expires_at:`${form.expires_at}T23:59:59.999Z`,modules});setMessage("Customer company, owner login, workspace, branch and licence created successfully.");setForm(initial);setModules([]);setStep(1);await onComplete()}catch(e){setMessage(e instanceof Error?e.message:"Onboarding failed")}finally{setBusy(false)}};
 return <section className="rounded-xl border border-indigo-200 bg-white p-4 shadow-sm">
  <div className="flex items-start gap-3"><div className="rounded-lg bg-indigo-100 p-2 text-indigo-700"><Rocket className="h-5 w-5"/></div><div><h2 className="font-semibold text-slate-900">New Customer Onboarding</h2><p className="text-xs text-slate-500">One guided flow creates the tenant, company owner, first workspace, branch and commercial licence.</p></div></div>
  <div className="mt-4 grid grid-cols-3 gap-2">{["Company & Owner","Plan & Licence","Workspace & Modules"].map((x,i)=><div key={x} className={`rounded-lg px-3 py-2 text-center text-xs font-bold ${step===i+1?"bg-indigo-600 text-white":step>i+1?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{step>i+1?<CheckCircle2 className="mr-1 inline h-4 w-4"/>:null}{i+1}. {x}</div>)}</div>
  {message&&<div className={`mt-3 rounded-lg px-3 py-2 text-sm ${message.includes("successfully")?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>{message}</div>}
  {step===1&&<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-semibold">Company Name<input className="input mt-1 w-full" value={form.name} onChange={e=>{update("name",e.target.value);if(!form.business_unit_name)update("business_unit_name",e.target.value)}}/></label><label className="text-xs font-semibold">Company Code<input className="input mt-1 w-full" value={form.code} onChange={e=>{update("code",e.target.value);if(!form.business_unit_code)update("business_unit_code",e.target.value)}}/></label><label className="text-xs font-semibold">Owner Name<input className="input mt-1 w-full" value={form.owner_name} onChange={e=>update("owner_name",e.target.value)}/></label><label className="text-xs font-semibold">Owner Email / Login<input className="input mt-1 w-full" type="email" value={form.owner_email} onChange={e=>update("owner_email",e.target.value)}/></label><label className="text-xs font-semibold">Temporary Password<input className="input mt-1 w-full" type="password" value={form.password} onChange={e=>update("password",e.target.value)}/><span className="mt-1 block font-normal text-slate-500">Minimum 8 characters; customer changes it after first login.</span></label><label className="text-xs font-semibold">Contact Phone<input className="input mt-1 w-full" value={form.contact_phone} onChange={e=>update("contact_phone",e.target.value)}/></label><label className="text-xs font-semibold sm:col-span-2 lg:col-span-3">Address<input className="input mt-1 w-full" value={form.address} onChange={e=>update("address",e.target.value)}/></label></div>}
  {step===2&&<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold">Plan<SearchableSelect className="input mt-1 w-full" value={form.plan_id} onChange={e=>choosePlan(e.target.value)}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</SearchableSelect></label><label className="text-xs font-semibold">Initial Status<SearchableSelect className="input mt-1 w-full" value={form.status} onChange={e=>update("status",e.target.value)}><option value="trial">Trial</option><option value="active">Active</option></SearchableSelect></label><label className="text-xs font-semibold">Licence Expiry<input className="input mt-1 w-full" type="date" value={form.expires_at} onChange={e=>update("expires_at",e.target.value)}/></label><div className="rounded-lg border bg-slate-50 p-3 text-xs"><div className="font-bold">{plan?.name||"Select plan"}</div><div>{plan?.currency_code} {plan?.price||0} / {plan?.billing_cycle}</div><div>{plan?.max_users||0} users · {plan?.max_business_units||"—"} workspaces · {plan?.max_branches||"—"} branches</div></div></div>}
  {step===3&&<div className="mt-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold">Workspace Name<input className="input mt-1 w-full" value={form.business_unit_name} onChange={e=>update("business_unit_name",e.target.value)}/></label><label className="text-xs font-semibold">Workspace Code<input className="input mt-1 w-full" value={form.business_unit_code} onChange={e=>update("business_unit_code",e.target.value)}/></label><label className="text-xs font-semibold">Business Type<SearchableSelect className="input mt-1 w-full" value={form.business_unit_type} onChange={e=>{update("business_unit_type",e.target.value);setModules(v=>v.filter(key=>e.target.value==="transport"?key!=="production":key!=="transport"))}}><option value="steel">Steel / Manufacturing</option><option value="transport">Transport</option><option value="custom">General Business</option></SearchableSelect></label><label className="text-xs font-semibold">First Branch<input className="input mt-1 w-full" value={form.branch_name} onChange={e=>update("branch_name",e.target.value)}/></label><label className="text-xs font-semibold">Branch Code<input className="input mt-1 w-full" value={form.branch_code} onChange={e=>update("branch_code",e.target.value)}/></label></div><div className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-500">Licensed Modules</div><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{MODULES.map(key=><label key={key} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>{LABEL[key]}</span><input type="checkbox" checked={modules.includes(key)} disabled={(key==="production"&&form.business_unit_type==="transport")||(key==="transport"&&form.business_unit_type!=="transport")||key==="dashboard"} onChange={e=>setModules(v=>e.target.checked?[...v,key]:v.filter(x=>x!==key))}/></label>)}</div></div>}
  <div className="mt-5 flex justify-between border-t pt-4"><button className="btn-secondary" disabled={step===1||busy} onClick={()=>setStep(v=>v-1)}><ChevronLeft className="h-4 w-4"/>Back</button>{step<3?<button className="btn-primary" disabled={!valid||busy} onClick={()=>setStep(v=>v+1)}>Continue<ChevronRight className="h-4 w-4"/></button>:<button className="btn-primary" disabled={!valid||busy} onClick={()=>void submit()}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Rocket className="h-4 w-4"/>}Create Customer & Licence</button>}</div>
 </section>;
}
