import { useCallback, useEffect, useState } from "react";
import { Languages, Loader2 } from "lucide-react";
import { supabase } from "@/lib/supabase";

const catalog = [["en","English"],["ur","Urdu"],["ar","Arabic"],["hi","Hindi"],["bn","Bengali"],["fa","Persian"],["tr","Turkish"],["fr","French"],["es","Spanish"],["de","German"],["pt","Portuguese"],["ru","Russian"],["zh","Chinese"],["id","Indonesian"],["ms","Malay"]] as const;
type Row={language_code:string;enabled:boolean;is_verified:boolean};
export default function OwnerLanguageControl({companyId}:{companyId:string}){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.rpc("owner_get_company_language_entitlements",{p_company_id:companyId});setRows((data??[]) as Row[]);setError(error?.message||"");setLoading(false)},[companyId]);
 useEffect(()=>{void load()},[load]); const rowFor=(code:string)=>rows.find(r=>r.language_code===code);
 const toggle=async(code:string,enabled:boolean)=>{setSaving(code);setError("");const current=rowFor(code);if(!current?.is_verified&&enabled){setError("This translation pack is not verified yet. Complete and verify the pack before enabling it for a customer company.");setSaving("");return}const {error}=await supabase.rpc("owner_set_company_language_entitlement",{p_company_id:companyId,p_language_code:code,p_enabled:enabled});setError(error?.message||"");if(!error)await load();setSaving("")};
 return <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><Languages className="h-5 w-5"/><div><h2 className="font-semibold">Language Entitlements</h2><p className="text-xs text-slate-500">Owner controls which verified language packs this company may use. Company users can only choose from enabled packs.</p></div></div>{error&&<div className="mb-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</div>}{loading?<div className="flex items-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading languages...</div>:<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{catalog.map(([code,name])=>{const row=rowFor(code),verified=!!row?.is_verified,enabled=verified&&!!row?.enabled;return <div key={code} className="flex items-center justify-between rounded-lg border border-slate-200 p-3"><div><div className="text-sm font-semibold text-slate-900">{name}</div><div className={`text-[11px] ${verified?"text-emerald-700":"text-amber-700"}`}>{verified?"Verified pack":"Pack pending verification"}</div></div><button type="button" disabled={!verified||saving===code} onClick={()=>void toggle(code,!enabled)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${enabled?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"} disabled:cursor-not-allowed disabled:opacity-50`}>{saving===code?"Saving...":enabled?"Enabled":"Disabled"}</button></div>})}</div>}<p className="mt-3 text-xs text-slate-500">English remains the safe fallback. Bilingual mode may combine any two language packs that are both verified and enabled for the company.</p></section>;
}
