drop policy if exists manufacturing_write_bom_lines on public.bom_lines;
create policy manufacturing_create_bom_lines on public.bom_lines for insert to authenticated with check(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','create')));
create policy manufacturing_edit_bom_lines on public.bom_lines for update to authenticated using(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','edit'))) with check(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','edit')));
create policy manufacturing_delete_bom_lines on public.bom_lines for delete to authenticated using(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','delete')));

drop policy if exists manufacturing_write_routing_operations on public.routing_operations;
create policy manufacturing_create_routing_operations on public.routing_operations for insert to authenticated with check(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','create')));
create policy manufacturing_edit_routing_operations on public.routing_operations for update to authenticated using(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','edit'))) with check(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','edit')));
create policy manufacturing_delete_routing_operations on public.routing_operations for delete to authenticated using(exists(select 1 from public.bom_versions b where b.id=bom_version_id and b.company_id=public.current_company_id() and b.business_unit_id=public.current_business_unit_id() and b.status='draft' and public.has_module_permission(b.company_id,'production','delete')));
