begin;
-- Prevent duplicate salary/trip-pay month posting and keep loan vs other
-- deductions on distinct canonical mappings.
create or replace function public.transport_driver_post_month(p_employee_id uuid,p_month date) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare c uuid:=public.current_company_id();b uuid:=public.current_business_unit_id();loc uuid:=public.current_operating_location_id();m date:=date_trunc('month',p_month)::date;v jsonb;earn numeric;loan_ded numeric;other_ded numeric;exp uuid;payable uuid;loan uuid;other_acc uuid;expn text;payn text;loann text;othern text;je uuid:=gen_random_uuid();jno text;ename text;
begin perform public.transport_finance_assert('driver');perform public.assert_module_permission('accounting','post');
 if exists(select 1 from public.transport_driver_month_closings where company_id=c and business_unit_id=b and operating_location_id=loc and employee_id=p_employee_id and month=m) then raise exception 'Driver month is already posted and locked';end if;
 if exists(select 1 from public.employee_salary_accruals a where a.company_id=c and a.business_unit_id=b and a.employee_id=p_employee_id and a.salary_month=m) then raise exception 'Payroll salary is already accrued for this driver/month. Reverse/correct payroll before posting Transport Driver Khata.';end if;
 v:=public.transport_driver_month_preview(p_employee_id,m);earn:=round(coalesce((v->>'trip_pay')::numeric,0)+coalesce((v->>'allowance')::numeric,0)+coalesce((v->>'bonus')::numeric,0)+coalesce((v->>'other_earning')::numeric,0),2);loan_ded:=round(coalesce((v->>'loan_deduction')::numeric,0),2);other_ded:=round(coalesce((v->>'other_deduction')::numeric,0),2);
 if loan_ded+other_ded>earn+coalesce((v->>'opening_balance')::numeric,0) then raise exception 'Deductions exceed driver payable';end if;
 select account_id into exp from public.account_mappings where company_id=c and mapping_key in('driver_pay_expense','salary_expense','salaries') order by case mapping_key when 'driver_pay_expense' then 0 when 'salary_expense' then 1 else 2 end limit 1;
 select id,name into payable,payn from public.chart_of_accounts where company_id=c and detail_type='Salary Payable' and is_active and not is_group order by created_at limit 1;
 select account_id into loan from public.account_mappings where company_id=c and mapping_key='employee_loan_receivable';select account_id into other_acc from public.account_mappings where company_id=c and mapping_key='employee_other_deduction_receivable';
 select name into expn from public.chart_of_accounts where id=exp and company_id=c;select name into loann from public.chart_of_accounts where id=loan and company_id=c;select name into othern from public.chart_of_accounts where id=other_acc and company_id=c;
 if earn>0 and (exp is null or payable is null) then raise exception 'Driver Pay Expense / Salary Payable account mapping is missing';end if;if loan_ded>0 and loan is null then raise exception 'Employee Loan / Advance Receivable mapping is required for loan deduction';end if;if other_ded>0 and other_acc is null then raise exception 'Other deduction needs dedicated employee_other_deduction_receivable mapping; it cannot post to Employee Loan/Advance Receivable';end if;
 select name into ename from public.employees where id=p_employee_id and company_id=c and is_active;if ename is null then raise exception 'Active driver employee not found';end if;
 jno:='DRV-'||to_char(m,'YYYYMM')||'-'||upper(substr(replace(je::text,'-',''),1,6));
 insert into public.journal_entries(id,user_id,company_id,business_unit_id,operating_location_id,entry_no,entry_date,description,status,payment_mode,party_name,trans_type,created_by,source_module,source_document_type) values(je,public.legacy_data_user_id(),c,b,loc,jno,(m+interval '1 month - 1 day')::date,'Transport driver month closing - '||ename||' - '||to_char(m,'Mon YYYY'),'draft','Accrual',ename,'Driver Month Closing',auth.uid(),'transport','driver_month_closing');
 if earn>0 then insert into public.journal_lines(user_id,company_id,business_unit_id,entry_id,account,account_id,debit,credit,party_name) values(public.legacy_data_user_id(),c,b,je,expn,exp,earn,0,ename),(public.legacy_data_user_id(),c,b,je,payn,payable,0,earn,ename);end if;
 if loan_ded>0 then insert into public.journal_lines(user_id,company_id,business_unit_id,entry_id,account,account_id,debit,credit,party_name) values(public.legacy_data_user_id(),c,b,je,payn,payable,loan_ded,0,ename),(public.legacy_data_user_id(),c,b,je,loann,loan,0,loan_ded,ename);end if;
 if other_ded>0 then insert into public.journal_lines(user_id,company_id,business_unit_id,entry_id,account,account_id,debit,credit,party_name) values(public.legacy_data_user_id(),c,b,je,payn,payable,other_ded,0,ename),(public.legacy_data_user_id(),c,b,je,othern,other_acc,0,other_ded,ename);end if;
 perform public.post_journal_entry(je);
 insert into public.transport_driver_month_closings(company_id,business_unit_id,operating_location_id,employee_id,month,opening_balance,trip_pay,allowance,bonus,other_earning,loan_deduction,other_deduction,payments,closing_balance,journal_entry_id,posted_by) values(c,b,loc,p_employee_id,m,(v->>'opening_balance')::numeric,(v->>'trip_pay')::numeric,(v->>'allowance')::numeric,(v->>'bonus')::numeric,(v->>'other_earning')::numeric,(v->>'loan_deduction')::numeric,(v->>'other_deduction')::numeric,(v->>'payments')::numeric,(v->>'closing_balance')::numeric,je,auth.uid());
 return v||jsonb_build_object('locked',true,'journal_entry_id',je,'entry_no',jno);
end $$;
grant execute on function public.transport_driver_post_month(uuid,date) to authenticated;
commit;
