alter table public.consolidated_sales_invoice_charges add column if not exists quantity numeric not null default 1, add column if not exists rate numeric not null default 0, add column if not exists account_id uuid null, add column if not exists cost_account_id uuid null, add column if not exists charge_type text not null default 'recovery';
create or replace function public.enforce_consolidated_sales_charge_master() returns trigger language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_unit text; v_default_rate numeric:=0; v_is_fixed boolean:=false; v_revenue uuid; v_cost uuid; v_type text:='recovery'; v_base numeric:=0; v_kg numeric:=0; v_pieces numeric:=0; v_qty numeric:=1; v_rate numeric:=0;
begin
select lower(trim(cm.unit)),coalesce(cm.default_rate,0),coalesce(cm.is_fixed,false),cm.revenue_account_id,cm.cost_account_id,coalesce(cm.charge_type,'recovery') into v_unit,v_default_rate,v_is_fixed,v_revenue,v_cost,v_type from public.charge_master cm where cm.charge_key=new.charge_key and cm.is_active=true and cm.applies_to in ('sales','both') limit 1;
if v_unit is null then raise exception 'Active Sales/Both Charge Master entry not found for %',new.charge_key; end if;
select coalesce(sum(coalesce(l.qty,0)*coalesce(l.unit_price,0)),0),coalesce(sum(case when lower(trim(coalesce(i.unit,''))) in ('kg','kgs','kilogram','kilograms') or lower(trim(coalesce(i.unit,''))) like '%kilogram%' or lower(trim(coalesce(i.unit,''))) like '%کلوگرام%' or lower(trim(coalesce(i.unit,''))) like '%کلو گرام%' then coalesce(l.qty,0) when lower(trim(coalesce(i.unit,''))) in ('t','mt','ton','tons','tonne','tonnes') or lower(trim(coalesce(i.unit,''))) like '%metric ton%' or lower(trim(coalesce(i.unit,''))) like '%ٹن%' then coalesce(l.qty,0)*1000 else 0 end),0),coalesce(sum(case when lower(trim(coalesce(i.unit,''))) in ('pc','pcs','piece','pieces') or lower(trim(coalesce(i.unit,''))) like '%piece%' or lower(trim(coalesce(i.unit,''))) like '%عدد%' then coalesce(l.qty,0) else 0 end),0) into v_base,v_kg,v_pieces from public.consolidated_sales_invoice_lines l left join public.items i on i.id=l.item_id where l.invoice_id=new.invoice_id;
v_qty:=case v_unit when 'fixed' then 1 when 'percent' then greatest(v_base,0) when 'per_kg' then greatest(v_kg,0) when 'per_ton' then greatest(v_kg,0)/1000 when 'per_piece' then greatest(v_pieces,0) else 1 end;
if v_is_fixed then v_rate:=greatest(v_default_rate,0); new.amount:=round((case when v_unit='percent' then (v_qty*v_rate)/100 else v_qty*v_rate end)::numeric,2); else if v_unit='percent' then v_rate:=case when v_qty>0 then greatest(coalesce(new.amount,0),0)*100/v_qty else greatest(v_default_rate,0) end; else v_rate:=case when v_qty>0 then greatest(coalesce(new.amount,0),0)/v_qty else greatest(v_default_rate,0) end; end if; end if;
new.quantity:=round(coalesce(v_qty,0)::numeric,3); new.rate:=round(coalesce(v_rate,0)::numeric,4); new.account_id:=v_revenue; new.cost_account_id:=v_cost; new.charge_type:=v_type; return new; end; $$;
drop trigger if exists trg_enforce_consolidated_sales_charge_master on public.consolidated_sales_invoice_charges;
create trigger trg_enforce_consolidated_sales_charge_master before insert or update of charge_key,amount,tax_percent,invoice_id on public.consolidated_sales_invoice_charges for each row execute function public.enforce_consolidated_sales_charge_master();
update public.consolidated_sales_invoice_charges set amount=amount;