-- Synced from verified production migration 20261006195902 (allow_test_purge_remaining_protected_records).
create or replace function public.guard_service_document_line() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare o record;v_module text:=case when tg_table_name='sales_service_lines' then 'sales' else 'purchase' end;
begin
 if coalesce(current_setting('app.maintenance_reset',true),'0')='1' then return case when tg_op='DELETE' then old else new end;end if;
 if tg_op='DELETE' then raise exception 'Service line history is append-only';end if;
 if new.company_id is distinct from public.current_company_id() or new.business_unit_id is distinct from public.current_business_unit_id() or not public.has_module_permission(new.company_id,v_module,case when tg_op='INSERT' then 'create' else 'edit' end) then raise exception 'Service line permission or tenant mismatch';end if;
 if tg_table_name='sales_service_lines' then select company_id,business_unit_id,status,document_kind,invoice_type,tax_percent into o from public.sales_orders where id=new.order_id;else select company_id,business_unit_id,status,document_kind,invoice_type,tax_percent into o from public.purchase_orders where id=new.order_id;if not exists(select 1 from public.chart_of_accounts a where a.id=new.cost_account_id and a.company_id=new.company_id and a.type='expense' and a.is_active and not a.is_group) then raise exception 'Active company service expense account required';end if;end if;
 if o.company_id is distinct from new.company_id or o.business_unit_id is distinct from new.business_unit_id or o.document_kind<>'service' or o.status='posted' or new.tax_percent is distinct from(case when o.invoice_type='Tax Invoice' then o.tax_percent else 0 end) then raise exception 'Draft service document and tax snapshot required';end if;
 if tg_op='UPDATE' and(to_jsonb(new)-'description'-'amount'-'tax_percent'-'cost_account_id') is distinct from(to_jsonb(old)-'description'-'amount'-'tax_percent'-'cost_account_id') then raise exception 'Service line identity is immutable';end if;if tg_op='INSERT' then new.created_by:=auth.uid();end if;return new;end $$;
create or replace function public.transport_number_registry_guard() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin if coalesce(current_setting('app.maintenance_reset',true),'0')='1' then return case when tg_op='DELETE' then old else new end;end if;raise exception 'Issued Transport Trip numbers cannot be changed or removed';end $$;
create or replace function public.protect_customer_history() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin if coalesce(current_setting('app.maintenance_reset',true),'0')='1' then return old;end if;if exists(select 1 from public.sales_orders where customer_id=old.id) or exists(select 1 from public.cutting_orders where customer_id=old.id) or exists(select 1 from public.invoice_payment_allocations where customer_id=old.id) or exists(select 1 from public.journal_lines where party_type='customer' and party_id=old.id) or exists(select 1 from public.party_ledgers where party_type='customer' and party_id=old.id) then raise exception 'Customer has accounting or transaction history. Deactivate the customer instead of deleting it.';end if;return old;end $$;
create or replace function public.protect_supplier_history() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin if coalesce(current_setting('app.maintenance_reset',true),'0')='1' then return old;end if;if exists(select 1 from public.purchase_orders where supplier_id=old.id) or exists(select 1 from public.purchase_payment_allocations where supplier_id=old.id) or exists(select 1 from public.journal_lines where party_type='supplier' and party_id=old.id) or exists(select 1 from public.party_ledgers where party_type='supplier' and party_id=old.id) then raise exception 'Supplier has accounting or transaction history. Deactivate the supplier instead of deleting it.';end if;return old;end $$;
