create or replace function public.sync_return_line_inventory_cost() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_type text;v_qty_on_hand numeric:=0;
begin select note_type into v_type from public.return_notes where id=new.note_id and company_id=new.company_id and business_unit_id=new.business_unit_id; if v_type is null then raise exception 'Return note context was not found.'; end if; select coalesce(sum(quantity),0) into v_qty_on_hand from public.warehouse_stock where company_id=new.company_id and business_unit_id=new.business_unit_id and item_id=new.item_id; if v_type='sales_credit' then perform public.apply_inventory_cost_in(new.item_id,v_qty_on_hand,new.qty,new.cost_rate); elsif v_type='purchase_debit' then if new.qty>v_qty_on_hand then raise exception 'Insufficient on-hand stock for purchase return costing. Available: %, Return: %.',v_qty_on_hand,new.qty; end if; perform public.apply_inventory_cost_out_at_cost(new.item_id,v_qty_on_hand,new.qty,new.cost_rate); end if; return new; end $$;
create or replace function public.sync_consolidated_purchase_inventory_cost() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$
declare r record;v_current numeric;v_old numeric;
begin if old.status is not distinct from 'posted' or new.status is distinct from 'posted' then return new; end if; for r in select l.item_id,sum(coalesce(l.qty,0)) q,sum(coalesce(l.qty,0)*coalesce(l.unit_cost,0)) val from public.consolidated_purchase_invoice_lines l where l.invoice_id=new.id and l.company_id=new.company_id and l.business_unit_id=new.business_unit_id group by l.item_id order by l.item_id loop select coalesce(sum(ws.quantity),0) into v_current from public.warehouse_stock ws where ws.company_id=new.company_id and ws.business_unit_id=new.business_unit_id and ws.item_id=r.item_id; v_old:=greatest(v_current-r.q,0); perform public.apply_inventory_cost_in(r.item_id,v_old,r.q,case when r.q>0 then r.val/r.q else 0 end); end loop; return new; end $$;
drop trigger if exists trg_sync_consolidated_purchase_inventory_cost on public.consolidated_purchase_invoices;
create trigger trg_sync_consolidated_purchase_inventory_cost after update of status on public.consolidated_purchase_invoices for each row when(old.status is distinct from new.status and new.status='posted') execute function public.sync_consolidated_purchase_inventory_cost();
drop trigger if exists trg_return_line_inventory_cost on public.return_note_lines;
create trigger trg_return_line_inventory_cost before insert on public.return_note_lines for each row execute function public.sync_return_line_inventory_cost();
