-- Priority 1: posted-document immutability + RPC ACL + language entitlement RLS hardening.
REVOKE ALL ON FUNCTION public.admin_reopen_posted_invoice(text,uuid,text,date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_invoice_correction_preflight(text,uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_admin_invoice_reversal_journal(text,uuid,text,date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reverse_admin_invoice_stock(text,uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.log_admin_posted_action(uuid,text,text,uuid,text,text,text,jsonb,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.assert_admin_posted_record_control(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.attach_invoice_source_traceability() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.attach_stock_source_traceability() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.navilo_link_posting_traceability() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.navilo_link_return_stock_movement() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.repair_invoice_outstanding_from_posted_activity(uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.delete_draft_purchase_invoice(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.delete_draft_sales_invoice(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_current_company_enabled_languages() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owner_get_company_language_entitlements(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owner_set_company_language_entitlement(uuid,text,boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.preview_next_sales_invoice_number(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_and_post_return_note(text,uuid,date,text,jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_and_post_return_note(text,uuid,date,text,jsonb) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.reverse_manual_journal_entry(uuid,date,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reverse_manual_journal_entry(uuid,date,text) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.reverse_payment_voucher(uuid,date,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reverse_payment_voucher(uuid,date,text) TO authenticated, service_role;
ALTER TABLE public.company_language_entitlements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS company_language_entitlements_select ON public.company_language_entitlements;
DROP POLICY IF EXISTS company_language_entitlements_insert ON public.company_language_entitlements;
DROP POLICY IF EXISTS company_language_entitlements_update ON public.company_language_entitlements;
DROP POLICY IF EXISTS company_language_entitlements_delete ON public.company_language_entitlements;
DROP POLICY IF EXISTS company_language_entitlements_authenticated_select ON public.company_language_entitlements;
CREATE POLICY company_language_entitlements_authenticated_select ON public.company_language_entitlements FOR SELECT TO authenticated USING (company_id = public.current_company_id());
REVOKE ALL ON TABLE public.company_language_entitlements FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.company_language_entitlements FROM authenticated;
GRANT SELECT ON TABLE public.company_language_entitlements TO authenticated;
